LANSA.addComponent({id:"VF_UI047O",ot:"rp",tp:"Reusable Part",de:"\OC=Visual Item",tl:14015000},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")){cL=l.gCL();}var Fd={F1:{nm:"STD_INT",ft:"I",ln:4,dc:0,ec:"J",lb:{"ENG":"Std Integer","FRA":"?","JPN":"?"}[cL],h1:{"ENG":"Standard","FRA":"?","JPN":"?"}[cL],h2:{"ENG":"Integer","FRA":"?","JPN":"?"}[cL],h3:{"ENG":"Field","FRA":"?","JPN":"?"}[cL],de:{"ENG":"Standard Integer field","FRA":"?","JPN":"?"}[cL],dv:0,ia:["FE","RB"]},F2:{nm:"VF_ELSYMN",
ft:"A",ln:50,dc:0,lb:"Image Name",h1:"Image",h2:"Name",h3:"",de:"Image Name",dv:"",ia:["FE"]},F3:{nm:"VF_ELSTAT",ft:"A",ln:1,dc:0,lb:"Standard Char 1",h1:"Standard",h2:"Char",h3:"1",de:"Standard Char 1 State Flag",dv:"",ia:["FE"]}};var cO=l.rC(oI,{an:"PRIM_PANL",fd:Fd,pt:{AssociatedReference1:{da:"rw"},ParentUI047O:{da:"r"},Level:{da:"r"},ChildrenUI047O:{da:"r"}},mt:{zInt_Terminate:{},zInt_Initialize:{ps:{"Text":{pt:"i"},"Hint":{pt:"i"},"ImageName":{pt:"i"},"ImageSource":{pt:"i"},"UseAssociatedReference1":
{pt:"i"},"UseUI047OParent":{pt:"i"},"UseParent":{pt:"i"}}}},ev:{WasClicked:{}},co:function(){cO.aN.call(this);this.aF("VF_UI047O",Fd);var C0=this.cA("USYSTEM","VF_SY001O");var C1=this.cA("USYSTEMCOMMON","VF_SY001X");var C2=this.cR("ATTACHMENTMANAGER","PRIM_ATLM");var C3=this.cR("ATTACHIMAGE","PRIM_ATLI");var C4=this.cR("ATTACHLABEL","PRIM_ATLI");var C5=this.cR("IMAGE","VF_UI005O");var C6=this.cR("LABEL","PRIM_LABL");this.cD("ASSOCIATEDREFERENCE1");this.cD("PARENTUI047O");var C9=this.cF("LEVEL",Fd.F1.Dc);
var C10=this.cR("CHILDRENUI047O","PRIM_ACOL");if((C0!=null)&&(C0.iI()==false)){C0.iC();}if((C1!=null)&&(C1.iI()==false)){C1.iC();}C2.iC();C3.setManage(C5);C3.setParent(C2);C3.setAttachment("LEFT");C3.iC();C4.setManage(C6);C4.setParent(C2);C4.setAttachment("CENTER");C4.iC();C5.setParent(this);C5.setTabStop(false);C5.setHeight(32);C5.iC();C6.setParent(this);C6.setDisplayPosition(2);C6.setTabPosition(2);C6.setTabStop(false);C6.setEllipses("WORD");C6.setHeight(32);C6.setLeft(16);C6.setTop(0);C6.setWidth(129);
C6.iC();C9.aD();C9.iC();C10.setCollects("VF_UI047O");C10.iC();this.setDisplayPosition(1);this.setHeight(32);this.setLeft(0);this.setTabPosition(1);this.setTop(0);this.setWidth(145);this.setLayoutManager(C2);this.aH("CLICK",this,e1);}});function e1(sender,Ps){var r=l.eR(this,cO,"#Com_Owner.Click",35);var P0=Ps.r("HANDLED");r.ln=35;{r.ln=36;this.fE("WASCLICKED");r.ln=37;P0.set(true);}r.ln=38;r.e();};cO.mthZINT_TERMINATE=function(){var m=this.REF,r=l.mR(this,cO,"zInt_Terminate",41);r.ln=41;{r.ln=43;
this.srPARENTUI047O(null);r.ln=44;m.CHILDRENUI047O.mthREMOVEALL();}r.ln=46;r.e();};cO.mthZINT_INITIALIZE=function(p0,p1,p2,p3,p4,p5,p6){var m=this.REF,r=l.mR(this,cO,"zInt_Initialize",50);var P0=r.cP("TEXT","PRIM_DC","UnicodeString");var P1=r.cP("HINT","PRIM_DC","UnicodeString");var P2=r.cPF("IMAGENAME",Fd.F2.Dc);var P3=r.cPF("IMAGESOURCE",Fd.F3.Dc);var P4=r.cPD("USEASSOCIATEDREFERENCE1");var P5=r.cPD("USEUI047OPARENT");var P6=r.cPD("USEPARENT");P0.set(p0);P1.set((p1===u)?(""):(p1));P2.set((p2===u)?(""):(p2));
P3.set((p3===u)?("T"):(p3));P4=(p4===u)?(null):(p4);P5=(p5===u)?(null):(p5);P6=p6;var C0=r.cF("USEIMAGESIZE",Fd.F1.Dc);var C1=r.cR("IMAGESIZEUI005O","PRIM_ALPH");var C2=r.cF("USEITEMHEIGHT",Fd.F1.Dc);C0.iC();C1.iC();C2.iC();r.ln=50;{r.ln=63;this.srASSOCIATEDREFERENCE1(P4);r.ln=65;this.srPARENTUI047O(P5);r.ln=67;m.LEVEL.set(1);r.ln=68;while ( (P5!=null)){r.ln=69;m.LEVEL.set(l.add(m.LEVEL.get(),1));r.ln=70;P5=r.sR("P5",P5.getPARENTUI047O());}r.ln=73;if((m.PARENTUI047O!=null)){r.ln=74;m.PARENTUI047O.getCHILDRENUI047O().mthINSERT(this);
}r.ln=78;C2.set(m.USYSTEM.ref.getCURRENTTHEME().getPOPUPMENU_ITEMHEIGHT());r.ln=79;C0.set(m.USYSTEM.ref.getCURRENTTHEME().getPOPUPMENU_IMAGESIZE());r.ln=81;if(l.n.le(m.USYSTEM.ref.getUIFORMFACTOR(),m.USYSTEM.ref.getUIFORMFACTOR_MEDIUM())){r.ln=82;P1.set("");}else{r.ln=84;P1.set(l.s.Trim(P1.get()));}r.ln=87;this.setParent(P6);this.setHeight(C2.get());this.setThemeDrawStyle("ListItem");this.setHint(P1.get());r.ln=91;{var v1=C0.get();if(r.ln=92,l.n.le(v1,16)){r.ln=93;C1.set("SMALL");}else if(r.ln=94,l.n.le(v1,24))
{r.ln=95;C1.set("MEDIUM");}else if(r.ln=96,l.n.le(v1,32)){r.ln=97;C1.set("LARGE");}else{r.ln=99;C1.set("XLARGE");}r.ln=100;}r.ln=102;m.IMAGE.mthZINT_INTIALIZEIMAGE(P2.get(),P3.get(),"",C1.get(),false,u,u,u,u);r.ln=104;m.ATTACHIMAGE.setMarginLeft(m.USYSTEM.ref.getCURRENTTHEME().getPOPUPMENU_IMAGELEFTPADDING());m.ATTACHIMAGE.setMarginTop(l.div(l.sub(C2.get(),C0.get()),2));r.ln=109;m.LABEL.setCaption(P0.get());m.LABEL.setAlignment("LEFT");m.LABEL.setVerticalAlignment("CENTER");r.ln=111;m.ATTACHLABEL.setMarginLeft(m.USYSTEM.ref.getCURRENTTHEME().getPOPUPMENU_IMAGELEFTPADDING());
m.ATTACHLABEL.setMarginRight(0);r.ln=113;m.LABEL.getStyles().mthADD(m.USYSTEM.ref.getCURRENTTHEME().getPOPUPMENU_FONTSTYLE());}r.ln=115;r.e();};cO.getASSOCIATEDREFERENCE1=function(){return this.REF.ASSOCIATEDREFERENCE1;};cO.setASSOCIATEDREFERENCE1=function(v){this.srASSOCIATEDREFERENCE1(v);};cO.getPARENTUI047O=function(){return this.REF.PARENTUI047O;};cO.getLEVEL=function(){return this.REF.LEVEL.get();};cO.getCHILDRENUI047O=function(){return this.REF.CHILDRENUI047O;};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);
};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"STD_INT"});}{Fd.F2.Dc=function(){this.aN.call(this,Fd.F2);};l.cFC({co:Fd.F2.Dc,an:"PRIM_FLD",fn:"VF_ELSYMN"});}{Fd.F3.Dc=function(){this.aN.call(this,Fd.F3);};l.cFC({co:Fd.F3.Dc,an:"PRIM_FLD",fn:"VF_ELSTAT"});}cO.srASSOCIATEDREFERENCE1=function(rn){this.sR("ASSOCIATEDREFERENCE1",rn);};cO.srPARENTUI047O=function(rn){this.sR("PARENTUI047O",rn);};},{rc:["VF_SY001O","VF_SY001X","VF_UI005O"],rp:["PRIM_PANL","PRIM_ATLM","PRIM_ATLI","PRIM_LABL","PRIM_FLD","PRIM_ACOL","PRIM_HINT"],
dc:["VF_UI047O"],dp:["PRIM_OBJT","PRIM_ALPH"]});