window.LANSA.addSrc("ver",function(e,c,a,b,h){c.pQb=function(){t.w.call(this);this.vf=new c.wd;this.Eqa=this.Xa=null};var t=c.u(c.pQb,c.pd);t.swc=function(){return document.hasFocus()};t.X_c=function(a,r,g){var l=e.re("PRIM_VS","Style"),s=null,f=null;r===h&&(r=0);g===h&&(g=0);if(a){if(0==r&&0==g)a.Tk(!0),s=a.ga;else if(0!=r){var d=a.zA(new c.ja,null);r=a.Ofa.lc[r-1];a.Ef().Ma().Ufb(d,r,a.Nfa,null,null,r.ib());s=r.Gt();if(0!=g&&(g=a.D1a(g-1)))for(var w in r.ib().ut)if(f=r.ib().ut[w],f.hn.wb==g){a.Ef().Ma().Tfb(d,
f.hn,f.hn.J$(),f.hn.jd.cKa(),f.hn.wb.dva(),null);s=f.hn.J$();break}b.ea(d)}s&&(l.yj(s.di),l.Ap(s.eX()),l.Wh(s.wx),l.Uv(s.ZC()),l.wj(s.Dw()),l.sd(s.uv()),l.fg(s.OC()),l.Ln(s.Ct()),l.Mu(s.Aw()),l.Nu(s.Bw()),l.Ku(s.yw()),l.Lu(s.zw()),l.$m(s.pk()),l.Jn(s.dl()),l.lm(s.Am()),l.Kl(s.Al()),l.LI(s.Pd().zv()),l.Rr(s.Pd().Ua()),l.QD(s.Pd().rj()),l.sB(s.Pd().vv()),l.QI(s.Pd().Bv()),l.nM(s.Pd().fD()),l.pM(s.Pd().lD()));f&&(a.Ef().Ma().Dj.cp&&l.wj(a.Ef().Ma().Dj.cp),a.Ef().Ma().Dj.ej&&l.sd(a.Ef().Ma().Dj.ej))}return l};
t.r7c=function(a,b){return a.N3a(b,[[]])};t.Bjc=function(){null.mgd()};t.Hic=function(a,e,g){var l;g===h&&(g=1);l===h&&(l=!0);a=new c.wd(a,e);if((e=b.UT(a))&&e.je()){var s=e.Kh(a),f=new c.Ls(e,s,a,1),d=new c.Ls(e,s,a,1),w=new c.Ls(e,s,a,2);b.EB(a.Db(),a.Eb(),s.Db(),s.Eb());l?(l=b.Q(),e.Lj(f),null==l.Oj?e.So(d):(l=l.Oj.ib(),b.gqb(null,l,s.Db(),s.Eb(),a.Db(),a.Eb())),2==g&&(w=new c.Ls(e,s,a,2),e.Lj(w))):(e.fU(f),e.ima(d));b.ea(f);b.ea(w);b.ea(d)}};t.N7c=function(a,e){var g=new c.wd(a,e),h=b.UT(g);if(h&&
h.je()){var s=h.Kh(g),f=new c.Ls(h,s,g,1),d=new c.Ls(h,s,g,1),w=new c.Ls(h,s,g,1),u=!1;b.EB(g.Db(),g.Eb(),s.Db(),s.Eb());h.Vya(s,h,!1);h.Uya(w);u=w.Rg;u||(h.Lj(f),h.So(d));b.ea(f);b.ea(d);b.ea(w)}};t.ICc=function(a,e){var g=new c.wd(a,e),h=b.UT(g);if(h&&h.je()){var s=h.Kh(g);for(b.EB(g.Db(),g.Eb(),s.Db(),s.Eb());h;)s=h.Kh(g),b.Oac(null,h.ib(),s.Db(),s.Eb(),g.Db(),g.Eb()),h=h.Z()}};t.lWc=function(a,e){var g=new c.wd(a,e),h=b.UT(g);h&&h.je()&&(h=h.Kh(g),b.EB(g.Db(),g.Eb(),h.Db(),h.Eb()))};t.RWc=function(a,
e){(this.Eqa=b.UT(new c.wd(a,e)))&&document.hasFocus()&&(b.dqb(this.Eqa.ib()),this.Eqa=null)};t.WFc=function(a,c){if(""!=a||0!=c){var e=0==c?a.charCodeAt(0):c,h;if(document.hasFocus())h=b.eqb();else if(this.Eqa)h=this.Eqa.ib();else return;b.Lac(null,h,e);""!=a&&b.Mac(null,h,a,a.charCodeAt(0));b.Nac(null,h,e)}};t.AKc=function(a,e){this.vf=new c.wd(this.vf.Db()+(0<a?1:0==a?0:-1),this.vf.Eb()+(0<e?1:0==e?0:-1));if(this.Xa){var g=this.Xa.Kh(this.vf);b.EB(this.vf.Db(),this.vf.Eb(),g.Db(),g.Eb());b.NWb(this.Xa,
g,this.vf)}};t.$Ic=function(a,e,g){g===h&&(g=1);this.vf=new c.wd(a,e);if(this.Xa=b.UT(this.vf))a=!1,e=this.Xa.Kh(this.vf),this.Xa.Sf.Fk&&(new c.ja(this.Xa.Sf.Fk.Re,this.Xa.Sf.Fk.kf,this.Xa.Sf.Fk.Ec,this.Xa.Sf.Fk.Pc)).Ud(e)&&(this.Xa.Sf.Fk.gma(null),a=this.Xa.Sf.Fk.ms),a||(b.EB(this.vf.Db(),this.vf.Eb(),e.Db(),e.Eb()),b.LWb(this.Xa,e,this.vf,g))};t.aJc=function(){if(this.Xa){var a=!1,e=this.Xa.Kh(this.vf);this.Xa.Sf.Fk&&(new c.ja(this.Xa.Sf.Fk.Re,this.Xa.Sf.Fk.kf,this.Xa.Sf.Fk.Ec,this.Xa.Sf.Fk.Pc)).Ud(e)&&
(this.Xa.Sf.Fk.jma(null),a=this.Xa.Sf.Fk.ms);a||(b.EB(this.vf.Db(),this.vf.Eb(),e.Db(),e.Eb()),b.MWb(this.Xa,e,this.vf,1));this.Xa=null}};t.zRc=function(a,e){this.vf=new c.wd(a,e);if(this.Xa=b.UT(this.vf)){var g=this.Xa.Kh(this.vf);b.EB(this.vf.Db(),this.vf.Eb(),g.Db(),g.Eb());b.OWb(this.Xa,g,this.vf,1)}};t.ARc=function(){if(this.Xa){var a=this.Xa.Kh(this.vf);b.EB(this.vf.Db(),this.vf.Eb(),a.Db(),a.Eb());b.PWb(this.Xa,a,this.vf,1);this.Xa=null}};e.yb(c.pQb,"PRIM_VER","Debugger",{Wa:{HasFocus:{f:t.swc}},
Gc:{Crash:function(){this.Bjc()},Click:function(a,b,c){this.Hic(e.aa(a),e.aa(b),c===h?1:e.aa(c))},Touch:function(a,b){this.N7c(e.aa(a),e.aa(b))},Hover:function(a,b){this.ICc(e.aa(a),e.aa(b))},SetCursorPos:function(a,b){this.lWc(e.aa(a),e.aa(b))},SetFocus:function(a,b){this.RWc(a,b)},KeyPress:function(a,b){this.WFc(e.ma(a),b===h?0:e.aa(b))},MouseMove:function(a,b){this.AKc(a,b)},LeftMouseDown:function(a,b,c){this.$Ic(e.aa(a),e.aa(b),c===h?1:e.aa(c))},LeftMouseUp:function(){this.aJc()},RightMouseDown:function(a,
b){this.zRc(a,b)},RightMouseUp:function(){this.ARc()},StyleSnapshot:function(a,b,c){return this.X_c(a,b===h?0:e.aa(b),c===h?0:e.aa(c))},ThemeDrawStyle:function(a,b){return this.r7c(a,e.ma(b))}}})});
