window.LANSA.addSrc("menu",function(e,c,a,b,h){e.Bb("PRIM_TBLO");e.Bb("PRIM_PPNL");e.Bb("PRIM_IMAG");e.Bb("PRIM_SPBN");a.vNa={mfb:16,pfb:16};a.$T={hya:0,vfb:1,wfb:2,qfb:4};a.qI={RZb:0,Oeb:1,Neb:2};a.qI.G={NONE:a.qI.RZb,BREAK:a.qI.Oeb,BARBREAK:a.qI.Neb};a.rI={cfb:25,efb:1,$eb:2,Cyd:4,ffb:8,bfb:16};a.qI={zKc:0};a.gyd=3;a.fyd=2;a.hyd=255;a.kKc=768;a.CZb=256;a.BZb=512;a.sNa=65536;a.tNa=131072;a.Ceb=262144;a.Eeb=524288;a.Deb=1048576;a.IHd=2;a.HHd=2;c.Nxa=function(){t.w.call(this);this.CE=null;this.i7=
a.vNa.mfb;this.cN=a.$T.hya;this.qm=null;this.lc=[];this.WG=new c.Sw;this.jga=new c.tb;this.Sp=new c.yz;this.Lad=new c.Yaa;this.Kad=new c.S3;this.Lad.Zr(this.Sp);this.Kad.Zr(this.Sp);this.WG.ol(this.Sp);this.jga.yj(b.H(255,255,255));this.jga.wj(b.tc().rGb(a.m.Gj));this.jga.$m(1);this.jga.Jn(1);this.jga.lm(1);this.jga.Kl(1);this.WG.Fa(this,a.K.mB,this.coc);this.WG.Cb(this.jga)};var t=c.u(c.Nxa,c.Rw);t.zb=function(){this.lc=null;t.j.zb.call(this)};t.U=function(){null!=this.CE&&this.YU();for(var a=null;null!=
(a=this.lc[0]);)a.Ia(null);b.VJc(this);t.j.U.call(this)};t.Uod=function(){return this.CE};t.Xod=function(){return this.lc};t.Wod=function(){return this.lc.length};t.t$=function(){return this};t.xFc=function(){return 0!=(this.cN&a.$T.wfb)};t.uEc=function(){return 0!=(this.cN&a.$T.qfb)};t.Zod=function(){return 0!=(this.cN&a.$T.vfb)};t.FXc=function(){var b=this.cN&~a.$T.vfb|a.$T.vfb;this.cN!=b&&(this.cN=b,this.fa(a.a.g))};t.R5a=function(){return 0!=(this.i7&a.vNa.pfb)};t.aGd=function(b){b=this.i7&~a.vNa.pfb|
(b?a.vNa.pfb:0);this.i7!=b&&(this.i7=b,this.fa(a.a.g))};t.aca=function(a){this.qm!=a&&(this.qm=a,this.TOa())};t.ruc=function(){return this.qm};t.iT=function(){return this.lc};t.taa=function(){return null!=this.CE||null!=this.Sf};t.Qtd=function(){for(var a,b=this.lc,c=0;c<b.length&&null!=(a=b[c]);c++)if(!0==a.sb())return!0;return!1};t.Cn=function(){null==this.Sf&&this.Ss(b.Ra().Sy(this));return this.Sf};t.t9=function(b){var c=e.Tb();c.Zb("CONTEXT",b);this.za(a.K.mB,c);c.qc()};t.pz=function(b){this.taa()&&
this.YU();b.$b=this;this.eTa(b);b.ya(this,this.bta);this.fa(a.a.g)};t.PDc=function(b){this.taa()&&this.YU();b.$b=this;this.eTa(b);b.ya(this,this.bta);this.fa(a.a.g)};t.Mba=function(b){this.taa()&&this.YU();b.$b=null;b.va(this,this.bta);this.eTa(b);this.fa(a.a.g)};t.cwa=function(){b.Q();this.YU()};t.K1b=function(a){if(null==this.CE){if(null!=this.Sf)this.CE=this.Sf;else{var c=b.Q().Rqa;this.CE=this.Z_a();null!=this.CE&&(c[this.CE]=this)}this.eOa(null,a)}};t.YU=function(){if(null!=this.CE){for(var a,
c=this.lc,d=0;d<c.length&&null!=(a=c[d]);d++){var e=a.ns;a.Ss(null);a.sPc();e&&e.YU()}null!=this.CE&&(null!=this.Sf?(this.Ss(null),this.CE=null):(a=b.Q().Rqa,null!=this.CE&&delete a[this.CE]));this.CE=null;this.Ss(null);b.Q().su(this.WG,!1)}};t.iNc=function(){};t.rgb=function(){};t.eOa=function(a,b){this.WG.mb(new c.ja(0,0,0,5));for(var d,e=0,g=this.lc,h=0;h<g.length&&null!=(d=g[h]);h++)e=this.iha(a,b,d,e)};t.iha=function(a,b,c,e,g){return c.iha(a,b,this,e,g)};t.eyb=function(a){for(var b=!1,c,e=this.lc,
g=0;g<e.length&&null!=(c=e[g]);g++)if(c==a||null!=c.ns&&c.ns.eyb(a)){b=!0;break}return b};t.wBc=function(b){for(var c=!1,d=null,e=this.lc,g=0;g<e.length&&null!=(d=e[g]);g++)if(d.Ob()&&d.je()){var h=d.ns;if(null!=h&&h.wBc(b)){c=!0;break}if(d.lra!=a.W.Gza&&d.lra==b){d.Gh();c=!0;break}}return c};t.Mhd=function(){for(var a=this.lc,b=null,c=null,e=0;e<a.length&&null!=(c=a[e]);e++)if(c.v2()){b=c;break}return b};t.eTa=function(a){var c=this.lc.indexOf(a);-1!=c&&this.lc.splice(c,1);c+=1;if(a.$b==this){0==
a.Ag()&&(a.Xg=this.lc.length+1);var d=a.Ag(),e=0;0<c&&d>c&&d++;for(var g,c=this.lc,h=0;h<c.length&&null!=(g=c[h])&&!(g.Ag()>=d);h++)e++;this.lc.splice(e,0,a)}b.TJc(this)};t.Vla=function(b){b==a.QS&&(this.taa()&&this.YU(),this.a4(),this.fa(a.a.g))};t.a4=function(){for(var b,c=this.lc,d=0;d<c.length&&null!=(b=c[d]);d++)b.Xg=1,b.fa(a.a.g)};t.xyd=function(a){var c=b.Q();return null!=c.Rqa?c.Rqa[a]:null};t.TOa=function(){};t.sOa=function(){b.Q().su(this.WG,!1)};t.rgb=function(){};t.Hu=function(a){this.cN|=
a};t.Yw=function(a){this.cN&=~a};t.Sv=function(a,b){this.cN=this.cN&~a|(b?a:0)};t.MAb=function(b,c){switch(c.Ya){case a.a.ub:this.aca(null)}};t.bta=function(){this.xFc()?this.Hu(a.$T.qfb):this.taa()&&(this.YU(),this.fa(a.a.g))};t.coc=function(){this.rgb(null,this.WG)};e.gd(c.Nxa,"PRIM_MENU",{Wa:{}});c.vdb=function(){p.w.call(this);this.zx=null};var p=c.u(c.vdb,c.Nxa);p.zb=function(){p.j.zb.call(this)};p.U=function(){this.sca(null);p.j.U.call(this)};p.xIb=function(){return this.zx};p.sca=function(b){this.zx!=
b&&(this.zx&&this.zx.BBd(this),b&&b.yud(this),this.fa(a.a.g))};p.iNc=function(){this.t9(null)};p.eOa=function(a,b){this.WG.mb(new c.ja(0,0,0,5));for(var d,e=0,g=this.lc,h=0;h<g.length&&null!=(d=g[h]);h++)e=this.iha(a,b,d,e,!0)};p.Z_a=function(){throw 0;};e.gd(c.vdb,"PRIM_MBAR",{Wa:{}});c.xdb=function(){r.w.call(this);this.mpa=null;this.yqb=0};var r=c.u(c.xdb,c.Nxa);r.zb=function(){r.j.zb.call(this)};r.U=function(){this.TOa();r.j.U.call(this)};r.nFd=function(b){b!=this.yqb&&(this.yqb=b,this.TOa(),
this.fa(a.a.g))};r.ajd=function(){return this.yqb};r.Dsc=function(){null==this.mpa&&(this.mpa=[]);return this.mpa};r.eOa=function(a,b){this.WG.mb(new c.ja(0,0,0,5));for(var d,e=0,g=this.Dsc(),h=0;h<g.length&&null!=(d=g[h]);h++)e=this.iha(a,b,d,e);g=this.lc;for(h=0;h<g.length&&null!=(d=g[h]);h++)e=this.iha(a,b,d,e)};r.Z_a=function(){return b.Qua()};r.lna=function(a,b){a===h&&(a=0);b===h&&(b=0);this.v0b(new c.wd(a,b),null,!0,null)};r.v0b=function(c,e){var d=b.Q(),g=!1,g=d.Oj,l=b.Q().ju;this.t9(e,c);
b.XMa(a.QS);this.aca(e);g&&this.Lr(g,a.Da.mac);null!=l&&l.jY()&&l.eO();this.K1b(this.WG);0<this.WG.Ua()&&(g=d.wwb(!0),this.WG.l5(c.Db(),c.Eb(),a.vj.Ww,h,null),d.wwb(g))};r.TOa=function(){this.YU();if(this.mpa){for(var a;null!=(a=this.mpa[0]);)b.ea(a);this.mpa=null}};r.Ued=function(a,b){var c=b.gja();c&&c.Szd(b.Ph.gK)};e.gd(c.xdb,"PRIM_PMNU",{Wa:{},Gc:{Show:r.lna}});c.WWb=function(){g.w.call(this);this.zx=null};var g=c.u(c.WWb,c.Nxa);g.zb=function(){g.j.zb.call(this)};g.U=function(){this.zx&&this.zx.pkb(null);
g.j.U.call(this)};g.xIb=function(){return this.zx};g.sca=function(b){if(this.zx!=b&&!this.eyb(b)){var c=this.zx;this.zx=b;c&&c.Twb(null);this.zx&&this.zx.Twb(this);this.fa(a.a.g,a.he.Swa)}};g.R5a=function(){var a=g.j.R5a.call(this);a&&(a=this.zx.KFc());return a};g.t$=function(){var a=null;this.zx&&(a=this.zx.t$());return a};g.sOa=function(){g.j.sOa.call(this);this.zx.Z().sOa()};g.Z_a=function(){return b.Qua()};g.m8c=function(){if(null!=this.CE)for(var a,b=this.lc,c=0;c<b.length&&null!=(a=b[c]);c++){var e=
a.ns;e&&e.YU()}};g.rgb=function(b,c){this.Hu(a.$T.wfb);this.t9(null);this.Hu(a.$T.wfb);this.taa()&&this.uEc()&&(this.m8c(),this.eOa(b,c));this.Hu(a.$T.qfb)};e.gd(c.WWb,"PRIM_SMNU",{Wa:{Parent:{f:g.xIb,i:g.sca}}});c.pWb=function(){l.w.call(this);this.$b=null;this.Oe=a.rI.cfb;this.hb=a.qI.zKc;this.We=a.sNa|a.tNa;this.lra=a.W.Gza;this.occ=this.Xg=this.kr=this.iec=this.gK=0;this.A0=this.ta=this.ns=this.$b=null;this.pb=this.xYa="";this.aR=new c.hm;this.nDa=new c.Ns;this.$_=new c.tb;this.HJ=new c.oI;this.N6=
b.$c(null,this.aR,null,null,1,1);this.oDa=b.$c(null,this.HJ,null,null,1,1);this.hqa=b.$c(null,this.nDa,null,null,1,1);this.nDa.Cb(this.$_);this.nDa.Ia(this.aR);this.HJ.Ia(this.aR);this.aR.Fa(this,a.K.nc,this.Tmc);this.mfc()};var l=c.u(c.pWb,c.Rw);l.zb=function(){this.$kc();l.j.zb.call(this)};l.U=function(){this.pkb(null);this.Ia(null);l.j.U.call(this);this.bd(null);this.fXc()};l.$ld=function(){var a="";this.kFc()||null!=this.t$()&&this.t$()instanceof c.xdb?a=this.Kb():this.Btc();return a};l.Kb=function(){return this.pb};
l.bz=function(){return this.Kb().Jo()};l.Btc=function(){this.Kb()};l.xkd=function(){return this.Frb};l.dsd=function(){return!0};l.Dqd=function(){return!0};l.Lpd=function(){return!0};l.Ujb=function(){var a=this.t$();a&&a.FXc()};l.uf=function(){return 0!=(this.We&a.Ceb)?!0:!1};l.v2=function(){return 0!=(this.We&a.Deb)?!0:!1};l.mFd=function(b){b!=this.w9a()&&(this.Oe=this.Oe&~a.rI.$eb|(b?a.rI.$eb:0),this.fa(a.a.g))};l.UC=function(){return this.kr};l.vwc=function(){return this.occ};l.Sxc=function(){var b=
a.qI.RZb;0!=(this.We&a.CZb)?b=a.qI.Oeb:0!=(this.We&a.BZb)&&(b=a.qI.Neb);return b};l.Z=function(){return this.$b};l.t$=function(){var a=null;this.$b&&(a=this.$b.t$());return a};l.cva=function(){return 0!=(this.We&a.Eeb)?!0:!1};l.qrd=function(){return this.lra};l.rrd=function(){return""};l.Wzc=function(){return this.ns};l.C6a=function(){return this.gK};l.Ksd=function(){return this.iec};l.sb=function(){return 0!=(this.We&a.tNa)?!0:!1};l.bc=function(a){this.pb!=a&&(this.pb=a,this.aZ())};l.Qs=function(a){this.Kb().oM(a)};
l.Vg=function(b){var c=this.UC();if(b&&0!=c&&null!=this.Z())for(var d,e=this.Z().lc,g=0;g<e.length&&null!=(d=e[g]);g++)d!=this&&d.UC()==c&&d.Vg(!1);b=b?this.We|a.Ceb:this.We&~a.Ceb;b!=this.We&&(this.We=b,this.fa(a.a.g))};l.DPa=function(b){b=b?this.We|a.Deb:this.We&~a.Deb;b!=this.We&&(this.We=b,this.fa(a.a.g))};l.Ag=function(){return this.Xg};l.tf=function(b){this.w9a()||(null!=this.$b?(this.Xg=b,this.$b.eTa(this)):this.Xg!=b&&(this.Xg=b,this.fa(a.a.g)))};l.je=function(){return 0!=(this.We&a.sNa)?
!0:!1};l.$f=function(b){b=b?this.We|a.sNa:this.We&~a.sNa;b!=this.We&&(this.We=b,this.fa(a.a.g))};l.xZ=function(b){this.kr!=b&&(this.kr=b,this.fa(a.a.g))};l.YWc=function(b){this.occ=b;this.fa(a.a.g)};l.EXc=function(b){var c=this.We&~a.kKc;switch(b){case a.qI.Oeb:c|=a.CZb;break;case a.qI.Neb:c|=a.BZb}c!=this.We&&(this.We=c,this.fa(a.a.g))};l.Ia=function(b){this.$b!=b&&(this.$b&&this.$b.Mba(this),b&&(this.w9a()?b.PDc(this):b.pz(this)),null!=this.ta&&this.Ujb(),this.fa(a.a.g,a.he.Swa))};l.Zjb=function(b){b=
b?this.We|a.Eeb:this.We&~a.Eeb;b!=this.We&&(this.We=b,this.fa(a.a.g))};l.yYc=function(b){this.lra!=b&&(this.lra=b,this.fa(a.a.g))};l.pkb=function(a){this.ns!=a&&(this.ns&&this.ns.sca(null),a&&a.sca(this))};l.EQa=function(b){this.gK!=b&&(this.gK=b,this.fa(a.a.g))};l.iHd=function(a){this.iec=a};l.Ic=function(){return this.ta};l.bd=function(b){this.ta!=b&&(null!=this.ta&&(this.ta.va(this,this.$l),this.ta.Ab()),this.ta=b,null!=this.ta&&(this.ta.ua(),this.ta.ya(this,this.$l)),this.Ujb(),this.fa(a.a.g))};
l.fXc=function(){null!=this.A0&&(null!=this.A0&&(this.A0.va(this,this.uBb),this.A0.Ab()),this.A0=null,null!=this.A0&&(this.A0.ua(),this.A0.ya(this,this.uBb)),this.Ujb(),this.fa(a.a.g))};l.Znd=function(){return this.A0};l.rAc=function(){return this.xYa};l.yZc=function(b){this.xYa!=b&&(this.xYa=b,this.fa(a.a.g,a.he.zGc))};l.vKa=function(){return 0!=(this.Oe&a.rI.efb)?!0:!1};l.zZc=function(b){b!=this.vKa()&&(this.Oe=this.Oe&~a.rI.efb|(b?a.rI.efb:0),this.fa(a.a.g))};l.f7a=function(){return 0!=(this.Oe&
a.rI.ffb)?!0:!1};l.AZc=function(b){b!=this.f7a()&&(this.Oe=this.Oe&~a.rI.ffb|(b?a.rI.ffb:0),this.fa(a.a.g))};l.lrd=function(){return!0};l.Dia=function(){return 0!=(this.Oe&a.rI.bfb)?!0:!1};l.a4b=function(b){b!=this.Dia()&&(this.Oe=this.Oe&~a.rI.bfb|(b?a.rI.bfb:0),this.fa(a.a.g))};l.Nb=function(b){b=b?this.We|a.tNa:this.We&~a.tNa;b!=this.We&&(this.We=b,this.fa(a.a.g))};l.UIb=function(){return this.Rc};l.Cn=function(){null==this.Sf&&this.Ss(b.Ra().Sy(this));return this.Sf};l.Ob=function(){return null!=
this.$b&&this.$b.taa()?!0:!1};l.mvd=function(){return"-"==this.Kb()?!0:!1};l.w9a=function(){return 0!=(this.Oe&a.rI.$eb)?!0:!1};l.KFc=function(){var a=this.vKa();if(a&&this.f7a()){var b=this.Z();b&&(a=b.R5a())}return a};l.kFc=function(){return null!=this.Z()&&this.Z()instanceof c.vdb};l.Gh=function(b){b===h&&(b=null);var c=e.Tb();c.Zb("CONTEXT",b);this.za(a.K.nc,c);c.qc()};l.lJd=function(){if(this.ns)for(var a,b=this.ns.lc,c=0;c<b.length&&null!=(a=b[c]);c++)a.Vg(!1)};l.Twb=function(b){this.ns!=b&&
(this.ns&&(this.ns.zx==this?this.ns.sca(null):(this.fa(a.a.YKc),this.ns.va(this,this.tCb),this.ns=null)),b&&(b.zx!=this?b.sca(this):(this.ns=b,this.ns.ya(this,this.tCb))),this.fa(a.a.g))};l.zyd=function(a){return b.Q().kEa[a]};l.mfc=function(){this.Frb=b.Q().swb();b.Q().kEa[this.Frb]=this};l.iha=function(a,b,c,e){return this.Ffc(b,e)};l.sPc=function(){this.aR.Ia(null)};l.Ffc=function(b,e){if(this.sb()){var d=b.An(),g=null;this.$_.Ap(a.m.Jd);this.$_.yj(a.m.Jd);this.$_.$m(1);this.$_.Jn(1);this.$_.lm(1);
this.$_.Kl(1);this.uf()&&(g=this.cva()?a.Xb.c_b:a.Xb.b_b,this.$_.Ap(a.m.OU),this.$_.yj(a.m.r5));this.Ic()&&(g=this.Ic());this.N6.Ia(d);this.N6.Cp(d.hd(0));this.N6.Bp(d.od(0));this.N6.ci(a.xa.nj);this.N6.Qb(a.Ea.nC);this.N6.jc(a.ka.si);this.N6.Ne(4);this.N6.Ie(2);this.hqa.Ia(d);this.hqa.Cp(d.hd(0));this.hqa.Bp(d.od(0));this.hqa.jc(a.ka.$d);this.hqa.Qb(a.Ea.Zk);this.hqa.Ne(2);this.oDa.Ia(d);this.oDa.Cp(d.hd(0));this.oDa.Bp(d.od(0));this.oDa.jc(a.ka.Kf);this.oDa.Ne(22);this.aR.Ia(b);this.aR.ol(d);this.aR.tf(e+
1);this.aR.dQ(this.vKa()?this.xYa:"");this.HJ.VL(!1);this.HJ.zq(a.ie.YY);this.HJ.eQa(a.BD.eya);this.HJ.bG(a.Ts.rK);this.HJ.bc(this.Kb());this.HJ.Mn(a.xh.Gq);this.HJ.HZ(this.ns?this.ns.WG:null);this.nDa.Yi(g);this.HJ.Tk(!1,!0);d=60+this.HJ.q2();g=10+this.HJ.cua();this.aR.Jc(g);this.nDa.mb(new c.ja(2,2,18,18));this.HJ.mb(new c.ja(22,2,d,18));b.hc(Math.max(b.fb(),d));b.Jc(b.Ua()+this.aR.Ua());null!=this.ns&&this.ns.K1b(this.ns.WG);e++}return e};l.$kc=function(){delete b.Q().kEa[this.Frb];b.Q()};l.qJd=
function(a){this.tf(a);null!=this.$b&&this.$b.a4()};l.aZ=function(){this.fa(a.a.g,a.he.ZOb)};l.Tmc=function(a,b){this.UC()&&this.Vg(!0);this.Gh();this.Z()&&this.Z().sOa();b.HANDLED.set(!0)};l.tCb=function(){this.Ob()&&this.fa(a.a.g)};l.$l=function(b,c){switch(c.Ya){case a.a.ub:case a.a.Vb:this.bd(null)}};l.uBb=function(b,c){switch(c.Ya){case a.a.ub:case a.a.Vb:this.bd(null)}};e.gd(c.pWb,"PRIM_MITM",{Wa:{Parent:{f:l.Z,i:l.Ia},Caption:{f:l.Kb,i:function(a){this.bc(e.ma(a))}},Checked:{f:l.uf,i:function(a){this.Vg(e.Ha(a))}},
Default:{f:l.v2,i:function(a){this.DPa(e.Ha(a))}},GroupIndex:{f:l.UC,i:function(a){this.xZ(e.aa(a))}},HelpContext:{f:l.vwc,i:function(a){this.YWc(e.aa(a))}},MenuBreak:{f:function(){return e.Ja(this.Sxc(),a.qI.G)},i:function(b){this.EXc(e.Ba(b,a.qI.G))}},RadioItem:{f:l.cva,i:function(a){this.Zjb(e.Ha(a))}},SubMenu:{f:l.Wzc,i:l.pkb},ShortCut:{f:function(){return e.Ja(this.lra,a.W.G)},i:function(b){this.yYc(e.Ba(b,a.W.G))}},Tag:{f:l.C6a,i:function(a){this.EQa(e.aa(a))}},Tip:{f:l.rAc,i:function(a){this.yZc(e.ma(a))}},
TipShow:{f:l.vKa,i:function(a){this.zZc(e.Ha(a))}},TipShowOfParent:{f:l.f7a,i:function(a){this.AZc(e.Ha(a))}},Enabled:{f:l.je,i:function(a){this.$f(e.Ha(a))}},Visible:{f:l.sb,i:function(a){this.Nb(e.Ha(a))}},DisplayPosition:{f:l.Ag,i:function(a){this.tf(e.aa(a))}},Image:{f:l.Ic,i:l.bd}}})},{rp:["PRIM_TBLO","PRIM_PPNL","PRIM_IMAG","PRIM_SPBN"]});
