window.LANSA.addSrc("caro",function(e,c,a,b,h){e.Bb("PRIM_UDC");e.Bb("PRIM_IMAG");a.K5={u_b:1,ZKc:0,t_b:1};a.K5.G={DEFAULT:a.K5.u_b,NONE:a.K5.ZKc,BUTTONS:a.K5.t_b};a.py={uC:0,qkc:0,ked:1,jed:2,ied:3,yK:4};a.py.G={PAGE:a.py.yK};a.GBa={P_b:0,NLc:0,OLc:1};a.GBa.G={DEFAULT:a.GBa.P_b,HORIZONTAL:a.GBa.NLc,VERTICAL:a.GBa.OLc};a.HBa={h7b:0,l7c:0,m7c:1};a.HBa.G={DEFAULT:a.HBa.h7b,ANTICLOCKWISE:a.HBa.l7c,CLOCKWISE:a.HBa.m7c};c.rQb=function(a){t.w.call(this);this.oE=a;this.O_=new c.ja;this.c0=1};var t=c.u(c.rQb,
c.yz);t.U=function(){t.j.U.call(this)};t.pe=function(b,c){t.j.pe.call(this,b,c);this.oE.Iw()==a.zm.yt&&this.oE.Ef().Dg()};t.Uoa=function(b,c){t.j.Uoa.call(this,b,c);if(this.oE.Iw()==a.zm.yt){var e=[];e[0]=this.c0;e[1]=this.O_;this.oE.bma(b,c,e);this.c0=e[0];this.O_=e[1]}};t.vA=function(b,c,e){c=[];this.oE.Iw()==a.zm.yt&&this.oE.Ef().Bwa()?(this.O_=this.oE.Mia(),this.c0=1,c=this.oE.vA(c)):c=t.j.vA.call(this,b,c,e);return c};c.MQb=function(a){p.w.call(this);this.oE=a;this.DYa=!1;this.Jra=0};var p=c.u(c.MQb,
c.Cbb);p.svd=function(){return this.DYa};p.Vya=function(a,b,c){p.j.Vya.call(this,a,b,c);this.Jra=this.se()};p.Uya=function(a){var b=this.oE.fb()/this.oE.q7;a.bk(this.Jra!=this.se());p.j.Uya.call(this,a);0<b&&this.Jra!=this.se()&&(this.Jra>this.se()?(a=this.Jra-b*this.oE.p7,a<this.se()||(a=this.se()-(b+this.se()%b))):(a=this.Jra+b*this.oE.p7,a>this.se()||(a=this.se()-(b+this.se()%b),a+=b)),this.Lb(a,0,500));this.oE.kb()};p.wOa=function(a,c,e,g,h,k,l,r,s){if(0!=a){var t=b.Bf(this.se()+a,-(this.fb()-
this.oE.fb()),0);this.DYa=!0;this.Qa(t);this.DYa=!1;s[0]=!0}p.j.wOa.call(this,a,c,e,g,h,k,l,r,s)};c.qQb=function(){r.w.call(this);this.Rc=b.Cd(10,10,400,400);this.Yh=new c.tQb(this);this.qEa=a.K5.u_b;this.JCa=a.py.uC;this.VG=a.GBa.P_b;this.b7=this.ptb=0;this.ntb=75;this.lsb=50;this.ksb=20;this.ui=500;this.Lvb=a.HBa.h7b;this.q7=3;this.p7=1;var e=this.NR=this.MR=this.XV=this.YV=this.ou=this.dga=this.ega=this.T0=this.Wk=null,e=e=null;this.Wk=new c.yz;e=b.rq(this.Wk);e.Nl(a.Rf.jx);e.Jc(1);e=b.zp(this.Wk);
e.Nl(a.Rf.jx);e.hc(1);this.T0=new c.rQb(this);this.ega=b.rq(this.T0);this.ega.Nl(a.Rf.jx);this.ega.Jc(1);this.dga=b.zp(this.T0);this.dga.Nl(a.Rf.jx);this.dga.hc(1);this.ega.Zr(this.T0);this.dga.Zr(this.T0);this.ou=new c.MQb(this);this.ou.mb(new c.ja);this.ou.Bc=this;this.ou.ol(this.T0);this.ou.IU(!1);this.ou.BZ(!1);this.ou.cf(!1);this.ou.yq(!1);this.ou.Fa(this,a.K.jib,this.O1a);this.ou.Fa(this,a.K.aZa,this.Smc);this.ou.O5b(a.bw.Unb);this.YV=new c.Ns;this.YV.mb(new c.ja(0,0,20,90));this.YV.Yi(a.Xb.xic);
this.YV.Fa(this,a.K.nc,this.Snc);this.XV=new c.Ns;this.XV.mb(new c.ja(0,0,20,90));this.XV.Yi(a.Xb.yic);this.XV.Fa(this,a.K.nc,this.Rnc);this.MR=new c.Ns;this.MR.mb(new c.ja(0,0,20,20));this.MR.Yi(a.Xb.vic);this.MR.gg(0);this.MR.Fa(this,a.K.nc,this.Pnc);this.NR=new c.Ns;this.NR.mb(new c.ja(0,0,20,20));this.NR.Yi(a.Xb.wic);this.NR.gg(0);this.NR.Fa(this,a.K.nc,this.Qnc);b.Q().PFa(this.XV);b.Q().QFa(this.XV);b.Q().PFa(this.YV);b.Q().QFa(this.YV);b.Q().PFa(this.MR);b.Q().QFa(this.MR);b.Q().PFa(this.NR);
b.Q().QFa(this.NR);e=b.$c(this.Wk,this.YV,this.Wk.hd(0),this.Wk.od(0),1,1);e.Qb(a.Ea.Zk);e.jc(a.ka.$d);e=b.$c(this.Wk,this.XV,this.Wk.hd(0),this.Wk.od(0),1,1);e.Qb(a.Ea.Oy);e.jc(a.ka.$d);e=b.$c(this.Wk,this.MR,this.Wk.hd(0),this.Wk.od(0),1,1);e.Qb(a.Ea.qW);e.jc(a.ka.$d);e=b.$c(this.Wk,this.NR,this.Wk.hd(0),this.Wk.od(0),1,1);e.Qb(a.Ea.$N);e.jc(a.ka.$d);this.cca(a.zm.Lsa);e=new c.gxa;e=new c.uQb(this,e);this.nIa(e)};var r=c.u(c.qQb,c.Jka);r.U=function(){b.ea(this.T0);this.T0=null;b.ea(this.ega);this.ega=
null;b.ea(this.dga);this.dga=null;r.j.U.call(this)};r.Ds=function(){return this.T0};r.Iw=function(){var b=a.zm.Lsa;switch(this.hP()){case a.py.yK:b=a.zm.yt;break;default:b=this.iJa()}return b};r.Ef=function(){var b=null;switch(this.hP()){case a.py.yK:b=this.ou;break;default:b=r.j.Ef.call(this)}return b};r.Zia=function(){var b=null;switch(this.hP()){case a.py.yK:b=-this.ou.se();break;default:b=r.j.Zia.call(this)}return b};r.AX=function(){var b=null;switch(this.hP()){case a.py.yK:b=-this.ou.He();break;
default:b=r.j.AX.call(this)}return b};r.tyc=function(){return this.q7};r.YXc=function(b){b=Math.max(b,1);this.q7!=b&&(this.q7=b,this.dE(),this.fa(a.a.g))};r.syc=function(){return this.p7};r.XXc=function(b){b=Math.max(b,1);this.p7!=b&&(this.p7=b,this.dE(),this.fa(a.a.g))};r.Apd=function(){return this.qEa};r.hP=function(){var b=this.JCa;b==a.py.qkc&&this.Ob()&&e.Ba("LINEAR",a.py.G);return b};r.Tjd=function(){return this.JCa};r.Fv=function(){return this.VG};r.nod=function(){return this.ptb};r.jod=function(){return this.b7};
r.lod=function(){return this.ntb};r.gmd=function(){return this.lsb};r.fmd=function(){return this.ksb};r.Pia=function(){return this.ui};r.Esd=function(){return this.Lvb};r.QXc=function(b){this.qEa!=b&&(this.qEa=b,this.fa(a.a.g))};r.tVc=function(b){this.JCa!=b&&(this.JCa=b,this.Mg(),this.fa(a.a.g))};r.xU=function(b){this.VG!=b&&(this.VG=b,this.fa(a.a.g))};r.ZFd=function(b){this.ptb!=b&&(this.ptb=b,this.fa(a.a.g))};r.XFd=function(b){this.b7!=b&&(this.b7=b,this.fa(a.a.g))};r.YFd=function(c){c=b.Bf(c,
1,89);this.ntb!=c&&(this.ntb=c,this.fa(a.a.g))};r.BFd=function(b){this.lsb!=b&&(this.lsb=b,this.fa(a.a.g))};r.AFd=function(b){this.ksb!=b&&(this.ksb=b,this.fa(a.a.g))};r.KI=function(b){this.ui!=b&&(this.ui=b,this.fa(a.a.g))};r.hHd=function(b){this.Lvb!=b&&(this.Lvb=b,this.fa(a.a.g))};r.bHb=function(){return this.Es()};r.I$=function(){return b.Ra()};r.xLb=function(){return!1};r.ZS=function(){return"PRIM_CARO<"+this.MK()+">"};r.bX=function(b){0==(this.Bn()&a.jm.Os)&&this.ri(!0);this.ue(b);if(!this.Yc()){var c=
e.Tb();c.Zb("ITEM",b);this.za(a.K.rY,c);c.qc()}};r.cX=function(b){0==(this.Bn()&a.jm.Os)&&this.ri(!0);this.ue(b);if(!this.Yc()){var c=e.Tb();c.Zb("ITEM",b);this.za(a.K.tY,c);c.qc()}};r.k2=function(b){0==(this.Bn()&a.jm.Os)&&this.ri(!0);this.ue(b);if(!this.Yc()){var c=e.Tb();c.Zb("ITEM",b);this.za(a.K.sY,c);c.qc()}};r.az=function(b,c){this.ue(b);b.az(c);if(!c&&!this.Yc()){var g=e.Tb();g.Zb("ITEM",b);g.af("CONTINUE",!0);this.za(a.K.bI,g);g.Nf("CONTINUE");g.qc()}};r.p9=function(b,c){this.ue(b);if(!c&&
!this.Yc()){var g=e.Tb();g.Zb("ITEM",b);g.af("CONTINUE",!0);this.za(a.K.y3,g);c=!g.Nf("CONTINUE");g.qc()}return c};r.IC=function(b){this.ue(b);b.IC();if(!this.Yc()){var c=e.Tb();c.Zb("ITEM",b);this.za(a.K.qL,c);c.qc()}};r.GC=function(b){0==(this.Bn()&a.jm.Os)&&this.ri(!0);this.ue(b);b.GC();if(!this.Yc()){var c=e.Tb();c.Zb("ITEM",b);this.za(a.K.JF,c);c.qc()}};r.HC=function(b){0==(this.Bn()&a.jm.Os)&&this.ri(!0);this.ue(b);b.HC();if(!this.Yc()){var c=e.Tb();c.Zb("ITEM",b);this.za(a.K.pL,c);c.qc()}};
r.Kza=function(b){null!=b&&null!=b.kc&&this.Ef().dwa(b.kc,a.UH.Xja)};r.Jba=function(b){if(this.Ds())switch(this.hP()){case a.py.yK:switch(this.qEa){case a.K5.t_b:this.YV.Ia(this),this.YV.tf(1),this.XV.Ia(this),this.XV.tf(2),this.MR.Ia(this),this.MR.tf(3),this.NR.Ia(this),this.NR.tf(4)}this.ou.Ia(this);this.ou.tf(99);this.ou.bXc(this.ye().$()/this.p7);this.Ob()&&this.Dg();this.ol(this.Wk);b.Iy.qi(b.kc);b.Iy.Ia(this.Ds());b.Iy.bf(b.x4());b.Iy.Ne(b.bPa());b.Iy.Ie(b.Thb());b.Iy.If(0);b.Iy.jc(a.ka.ek);
b.Iy.ci(a.xa.oj);b.Iy.Qb(a.Ea.eF);b.Iy.Cp(this.ega);b.Iy.Bp(this.dga);break;default:this.ou.Ia(null),this.YV.Ia(null),this.XV.Ia(null),this.MR.Ia(null),this.NR.Ia(null),this.ol(null)}r.j.Jba.call(this,b)};r.JKc=function(a){this.d_b(a)};r.KKc=function(a){this.e_b(a)};r.FKc=function(a){this.ifb(a)};r.IKc=function(a){this.jfb(a)};r.HKc=function(a,b){this.GKc(a-1,b)};r.d_b=function(c){switch(this.hP()){case a.py.yK:if(this.Ef().se()==-(this.Ef().fb()-this.fb()))this.ifb(c);else{var d=this.fb()/this.q7,
d=this.Ef().se()-d*this.p7,d=b.Bf(d,-(this.Ef().fb()-this.fb()),0);c?this.Ef().Lb(d,0,1E3):this.Ef().Qa(d)}}};r.e_b=function(c){switch(this.hP()){case a.py.yK:if(0==this.Ef().se())this.jfb(c);else{var d=this.fb()/this.q7,d=this.Ef().se()+d*this.p7,d=b.Bf(d,-(this.Ef().fb()-this.fb()),0);c?this.Ef().Lb(d,0,1E3):this.Ef().Qa(d)}}};r.ifb=function(b){switch(this.hP()){case a.py.yK:b?this.Ef().Lb(0,0,1E3):this.Ef().Qa(0)}};r.jfb=function(b){switch(this.hP()){case a.py.yK:var c=-(this.Ef().fb()-this.fb());
b?this.Ef().Lb(c,0,1E3):this.Ef().Qa(c)}};r.GKc=function(c,d){switch(this.hP()){case a.py.yK:c-=c%this.q7;var e=this.A3(c);e&&e.kc&&(e=-e.kc.se(),e=b.Bf(e,-(this.Ef().fb()-this.fb()),0),d?this.Ef().Lb(e,0,1E3):this.Ef().Qa(e))}};r.dma=function(a){this.bX(a)};r.fma=function(a){this.cX(a)};r.ema=function(a){this.k2(a)};r.$la=function(a,b){this.az(a,b)};r.ama=function(a,b){return this.p9(a,b)};r.Dba=function(a){this.IC(a)};r.cZ=function(b){this.GC(b);this.fa(a.a.g)};r.cma=function(a){this.HC(a)};r.fB=
function(b){var c=null;switch(this.hP()){case a.py.yK:c=r.j.fB.call(this,b)}return c};r.pe=function(a){r.j.pe.call(this,a);if(!this.ou.DYa&&!this.ou.dy()){var d=b.xD(this,null),e=d.lc,g=null,h=a.$()/this.q7,k=this.ou.se(),l=this.fB(new c.wd(Math.abs(k)+10,10));if(0<e.length){for(var p=0;p<e.length&&null!=(g=e[p]);p++)g.kc&&g.kc.hc(h);g=-(h*e.length-a.fb());0>k&&l&&(k=-(h*l.tk()));this.ou.mb(new c.ja(b.Bf(k,g,0),0,h*e.length,a.ba()))}b.ea(d)}};r.Ki=function(){r.j.Ki.call(this);this.Md(a.Gb.NSa)};r.dh=
function(a){var b=null;return b=this.Yh.ng(a,!0,-1,!1)};r.ng=function(){this.Yh.ng(this.MK(),!0,-1,!0)};r.Th=function(a){return this.Yh.Th(!1,a)?"OK":"NR"};r.vn=function(){return this.Yh.cJa()};r.mj=function(){this.Yh.mj()};r.Zl=function(a){this.Yh.Zl(a==h?!0:!1,a)};r.zk=function(){this.Yh.zk()};r.Gl=function(a,b,c){return this.Yh.Gl(a,b,c)};r.sp=function(a){this.mj();for(var b=0;b<a;b++)this.ng()};r.Snc=function(){this.e_b(!0)};r.Rnc=function(){this.d_b(!0)};r.Pnc=function(){this.ifb(!0)};r.Qnc=
function(){this.jfb(!0)};r.Smc=function(){};r.O1a=function(a,b){this.$3a(b.AF("ORIENTATION"))};r.pv=r[a.R.KF]=function(a){var b=this.mF(a.Nc);b&&!b.Pe()&&b.vw(!0,!1,!0);r.j.pv.call(this,a)};e.gd(c.qQb,"PRIM_CARO",{rB:a.Br.tTa,Wa:{CurrentItem:{f:r.rf},FocusItem:{f:r.ag},PageSize:{f:r.tyc,i:function(a){this.YXc(e.aa(a))}},PageScroll:{f:r.syc,i:function(a){this.XXc(e.aa(a))}},CarouselStyle:{f:function(){return e.Ja(this.JCa,a.py.G)},i:function(b){this.tVc(e.Ba(b,a.py.G))}},NavigationStyle:{f:function(){return e.Ja(this.qEa,
a.K5.G)},i:function(b){this.QXc(e.Ba(b,a.K5.G))}}},Gc:{Add:r.dh,Sort:r.m5,FindItem:r.lf,DeleteAll:r.lF,FindReference:r.l9,NextItem:r.JKc,PrevItem:r.KKc,FirstItem:r.FKc,LastItem:r.IKc,MoveToItem:r.HKc},Pw:{ng:r.ng,Th:function(a){return this.Th(e.aa(a)-1)},sp:r.sp,mj:r.mj,vn:r.vn,Zl:function(a){return this.Zl(a?e.aa(a)-1:h)},zk:r.zk,Gl:r.Gl,Zq:r.Zq}});c.uQb=function(a,b){g.w.call(this,a,b)};var g=c.u(c.uQb,c.mxa);g.U=function(){g.j.U.call(this)};g.Sjd=function(){return this.jp.ra()};g.z8=function(a,
b){var c=null,g=null,h=null,k=null;null!=a&&(g=k=e.re(a),null!=g&&(g.Nb(!1),h=g,null!=h&&(c=e.re("PRIM_CARO","CarouselItem"),c.ua())));b[0]=k;b[1]=c;b[2]=g;b[3]=h};g.jO=function(a,b,c,e){this.z8(a,b);null!=b[1]&&this.pz(b[1],b[2],e)};g.pma=function(a){return a};c.tQb=function(a){l.w.call(this,a)};var l=c.u(c.tQb,c.kxa);l.ng=function(a,b,c,e){var g=this.ra(),h=null,h=[];b?g.bHb().jO(a,h,-1,e):g.bHb().jO(a,h,c,e);return h=h[1]};c.sQb=function(){s.w.call(this)};var s=c.u(c.sQb,c.Lka);s.U=function(){s.j.U.call(this)};
s.dh=function(a){var b=null,c=this.ra();c&&(b=c.dh(a),b.Ia(this));return b};s.az=function(c){if(!this.Yc()){var d=e.Tb();d.Zb("ITEM",this);d.af("CONTINUE",!0);this.za(a.K.bI,d);c=!d.Nf("CONTINUE");d.qc()}d=this.gq();null!=d&&b.wk(d,this,"ONITEMCLICK");return c};s.IC=function(){if(!this.Yc()){var c=e.Tb();c.Zb("ITEM",this);this.za(a.K.qL,c);c.qc()}c=this.gq();null!=c&&b.wk(c,this,"ONITEMREALIZING")};s.GC=function(){if(!this.Yc()){var c=e.Tb();c.Zb("ITEM",this);this.za(a.K.JF,c);c.qc()}c=this.gq();
null!=c&&b.wk(c,this,"ONITEMGOTFOCUS")};s.HC=function(){if(!this.Yc()){var c=e.Tb();c.Zb("ITEM",this);this.za(a.K.pL,c);c.qc()}c=this.gq();null!=c&&b.wk(c,this,"ONITEMLOSTFOCUS")};e.yb(c.sQb,"PRIM_CARO","CarouselItem",{Wa:{Design:{f:s.jJa},Carousel:{f:s.ra},Focus:{f:s.Pe,i:s.ze},Position:{f:s.C$},Entry:{f:s.Th},Selected:{f:s.dm,i:function(a){this.UI(e.Ha(a))}},RelatedReference:{f:s.H$,i:s.Nca},Visible:{f:s.sb,i:function(a){this.Nb(e.Ha(a))}}},Gc:{Delete:s.aq}})},{rp:["PRIM_UDC","PRIM_IMAG"]});
