window.LANSA.addSrc("wrtn",function(e,c,a,b,h){function t(a){return null===a?e.Qe:"object"==typeof a?a.mimetype&&a.data&&a.filename?new c.LF(a):"":a}function p(a){if(a===e.Qe)return null;switch(typeof a){case "object":if(a instanceof c.Vi)return a.toString();if(c.No&&a instanceof c.No)return a.x8b();if(a instanceof c.LF)return a.Aqa}return a}function r(b,c,d){var e=document.createElement("form");e.setAttribute("method","post");e.setAttribute("action",b);d==a.eV.$6b&&e.setAttribute("target","_blank");
for(var f in c)c.hasOwnProperty(f)&&(b=document.createElement("input"),b.setAttribute("type","hidden"),b.setAttribute("name",f),b.setAttribute("value",c[f]),e.appendChild(b));document.body.appendChild(e);e.submit()}function g(a){return(a=a.sm)&&"M"==a}function l(a,b){w&&b.append("_SESSIONKEY",w);var d=a.FLD;if(d!==h)for(var f in d){var g=d[f];g!==e.Qe&&(g instanceof c.LF?b.append(f,g.$ia(),g.hh()):b.append(f,p(g)))}d=a.LIST;if(d!==h)for(var k in d){for(var n=d[k],l=n.qo={},u=n.entryCount(),s=1;s<=
u;s++)for(f in n.getEntry(s),1==s&&b.append(k+"..",1),l){var g="000"+s.toString(),g=g.substr(g.length-4),r=k+"."+g+"."+f,g=l[f];g instanceof c.LF?b.append(r,g.$ia(),g.hh()):b.append(r,p(g))}delete n.qo}}function s(a,b){var c=b.webroutine={},d=c.context={};w&&(d["session-key"]=w);u&&(d["session-key-name"]=u);G&&(d["session-key-method"]=G);d=a.FLD;if(d!==h){var e=c.fields={},f;for(f in d)(e[f]={}).value=p(d[f])}d=a.LIST;if(d!==h){var c=c.lists={},g;for(g in d){for(var k=c[g]={},e=k.header=[],k=k.entries=
[],n=d[g],l=n.qo={},s=n.entryCount(),r=1;r<=s;r++){n.getEntry(r);if(1==r)for(f in l){var t={};e.push(t);t.name=f}t=[];k.push(t);for(f in l)t.push(p(l[f]))}delete n.qo}}}function f(a){if(a=a.context)w=a["session-key"],u=a["session-key-name"],G=a["session-key-method"]}function d(a,b,c){function d(a){if(a!=h){var b=a.FLD;f(a.LIST);f(b)}}function f(b){if(b!=h)for(var c in b)if(null===b[c])throw e.cQc(c,a.HXa,a.BXa);}d(b);d(c)}var w=h,u=h,G=h;a.eV={Gmb:0,$6b:1};a.eV.G={CURRENT:a.eV.Gmb,NEW:a.eV.$6b};e.gd(function(){},
"PRIM_WRTN",{});c.Zxa=function(a,b){k.w.call(this);this.HXa=a;this.BXa=b;this.Wtb=this.ctb=""};var k=c.u(c.Zxa,c.pd);k.Und=function(){return this.ctb};k.SFd=function(a){this.ctb=a};k.Wpd=function(){return this.Wtb};k.fGd=function(a){this.Wtb=a};k.vzc=function(){return this.HXa};k.jzc=function(){return this.BXa};k.mz=function(){return b.hkc(this.ctb,b.eJa(),this.HXa,this.BXa,this.Yyc())};k.Yyc=function(){var a=this.Wtb;""==a&&(a=b.dJa());return a};e.yb(c.Zxa,"PRIM_WEB","ServerRequest",{Wa:{ServerModule:{f:k.vzc},
Routine:{f:k.jzc}}});c.$ka=function(a,b){n.w.call(this,a,b)};var n=c.u(c.$ka,c.Zxa);n.TS=function(a,b){this.xFb(a,b,!1,null)};n.j9=function(a,c){this.xFb(a,c,!0,b.mQ())};n.xFb=function(c,k,n,p){function r(c){var d=null;try{d=JSON.parse(c)}catch(g){d=null}if(d){if(c=d.webroutine)if(c=c.messages)for(var n=e.S5a(),l=0;l<c.length;l++)n.dh(c[l],null);if(c=d["vlweb-error"]){var s=a.FQ.AIa;switch(c["message-id"]){case "HM42":case "HM43":s=a.FQ.AGb;G=u=w=h;break;case "HM05":s=a.FQ.zGb}if(!S.m9(s)&&c.message!==
h)throw e.eQc(S.HXa,S.BXa,c.message);}else{n=k;if(d=d.webroutine){l=n.FLD;if(l!==h){var y=d.fields;if(y)for(var z in l)c=y[z],c!==h&&(c=t(c.value),l[z].set(c))}z=n.LIST;if(z!==h&&(n=d.lists))for(s in z)if(l=z[s],l.mj(),c=n[s])for(var y=c.header,A=c.entries,E=0;E<A.length;E++){for(var O=l.qo={},Ja=A[E],D=0;D<Ja.length;D++)c=t(Ja[D]),O[y[D].name]=c;l.ng();delete l.qo}f(d)}S.aX()}}else S.m9(a.FQ.AIa);b.gx(p)}function z(){S.m9(a.FQ.AIa);b.gx(p)}function A(a){a.lengthComputable&&S.hsc(a.loaded,a.total,
e.aa(a.loaded/a.total*100))}function E(a){if(a.lengthComputable){var b=a.loaded/a.total*100;S.dGb(a.loaded,a.total,e.aa(b))}else S.dGb(a.loaded,-1,-1)}var S=this;d(S,c,k);if(g(c)){var ea=new FormData;l(c,ea);b.WMc(this.mz(),ea,r,z,A,E,n)}else ea={},s(c,ea),b.D0b(this.mz(),ea,r,z,A,E,n)};n.m9=function(c){var d=!1,d=e.Tb();d.WN("REASON",c,a.FQ.G);d.af("HANDLED",!1);this.za(a.K.US,d);(d=d.Nf("HANDLED"))||(d=b.sq().$rc(this,c));return d};n.aX=function(){this.za(a.K.Q1)};n.hsc=function(b,c,d){var f=e.Tb();
f.rA("LOADED",b);f.rA("TOTAL",c);f.rA("PROGRESS",d);this.za(a.K.f9c,f)};n.dGb=function(b,c,d){var f=e.Tb();f.rA("LOADED",b);f.rA("TOTAL",c);f.rA("PROGRESS",d);this.za(a.K.Ppc,f)};e.yb(c.$ka,"PRIM_WEB","DataRequest",{Gc:{Execute:n.TS,ExecuteAsync:n.j9}});c.mla=function(b,c){A.w.call(this,b,c);this.Xk=a.eV.Gmb};var A=c.u(c.mla,c.Zxa);A.Yzc=function(){return this.Xk};A.skb=function(a){this.Xk=a};A.TS=function(a,b){d(this,a,b);var c={};w&&(c._SESSIONKEY=w);var e=a.FLD;if(e!==h)for(var f in e)c[f]=p(e[f]);
e=a.LIST;if(e!==h)for(var g in e){for(var k=e[g],n=k.qo={},l=k.entryCount(),u=1;u<=l;u++)for(f in k.getEntry(u),1==u&&(c[g+".."]=1),n){var s="000"+u.toString(),s=s.substr(s.length-4);c[g+"."+s+"."+f]=p(n[f])}delete k.qo}r(this.mz(),c,this.Xk)};e.yb(c.mla,"PRIM_WEB","WebPageRequest",{Wa:{Target:{f:function(){return e.Ja(this.Xk,a.eV.G)},i:function(b){this.skb(e.Ba(b,a.eV.G))}}},Gc:{Execute:A.TS}});c.gla=function(b,c){S.w.call(this,b,c);this.Xk=a.eV.Gmb};var S=c.u(c.gla,c.Zxa);S.Yzc=function(){return this.Xk};
S.skb=function(a){this.Xk=a};S.TS=function(a,b){d(this,a,b);var c={};w&&(c._SESSIONKEY=w);var e=a.FLD;if(e!==h)for(var f in e)c[f]=p(e[f]);e=a.LIST;if(e!==h)for(var g in e){for(var k=e[g],n=k.qo={},l=k.entryCount(),u=1;u<=l;u++)for(f in k.getEntry(u),1==u&&(c[g+".."]=1),n){var s="000"+u.toString(),s=s.substr(s.length-4);c[g+"."+s+"."+f]=p(n[f])}delete k.qo}r(this.mz(),c,this.Xk)};e.yb(c.gla,"PRIM_WEB","ResourceRequest",{Wa:{Target:{f:function(){return e.Ja(this.Xk,a.eV.G)},i:function(b){this.skb(e.Ba(b,
a.eV.G))}}},Gc:{Execute:S.TS}});b.brc=function(b,c){var d=c.webroutine;if(d){var e=b.Ay.Hua(),f=d.fields;if(f){var g=b.uza(e),k;for(k in f){var h=null,n=b.Gi[k];n&&(h=n.kha());if(!h&&g)for(var l in g)if(n=g[l],n.Jh()==k){h=n;break}h&&(n=t(f[k].value),h.set(n))}}if(d=d.lists){var e=b.oRc(e),p;for(p in d){f=null;if(n=b.Gi[p])switch(n.hua()){case a.Br.Jpb:case a.Br.tTa:case a.Br.D_a:f=n}!f&&e&&(f=e[p]);if(f)for(n=d[p],g=n.header,k=n.entries,h=0;h<k.length;h++){l=f.qo={};for(var u=k[h],w=0;w<u.length;w++)n=
t(u[w]),l[g[w].name]=n;f.ng();delete f.qo}}}}};b.$qc=function(a){(a=a.webroutine)&&f(a)}});
