window.LANSA.addSrc("http",function(e,c,a,b,h){c.jeb=function(){t.w.call(this);this.cb=this.qtb=""};var t=c.u(c.jeb,c.pd);t.U=function(){t.j.U.call(this)};t.aja=function(){return this.qtb};t.v4b=function(a){this.qtb=a};t.Ka=function(){return this.cb};t.Va=function(a){this.cb=a};e.yb(c.jeb,"PRIM_WEB","HttpHeader",{Wa:{Key:{f:t.aja,i:function(a){this.v4b(e.ma(a))}},Value:{f:t.Ka,i:function(a){this.Va(e.ma(a))}}}});c.fNa=function(){p.w.call(this);this.eb=[]};var p=c.u(c.fNa,c.pd);p.Dc=function(){return this.eb.length};
p.Ce=function(a){for(var c=0;c<this.Dc();c++){var d=this.hq(c);if(b.hI(d.aja(),a))return d}return null};p.hq=function(a){if(0>a||a>=this.eb.length)throw e.GD(a,this.eb.length);return this.eb[a]};p.dh=function(a,b){var d=new c.jeb;d.v4b(a);d.Va(b);this.eb.push(d)};p.ak=function(){this.eb=[]};p.Mr=function(a){for(var b=!1,c=0;c<this.Dc()&&!(b=this.hq(c).aja()==a);c++);b&&this.eb.splice(c,1)};e.yb(c.fNa,"PRIM_WEB","HttpHeaders",{Wa:{Item:{f:function(a){return this.Ce(a)}},ItemCount:{f:p.Dc}},Gc:{Add:p.dh,
Remove:p.Mr,RemoveAll:p.ak},qg:{vg:"Item"},oq:{wp:function(a){return this.hq(e.aa(a-1))},Lw:p.Dc}});a.GF={f:1,CCc:2,UMc:3,BOc:4,aq:5,S7c:6,QLc:7,fjc:8,fMc:9};a.GF.G={GET:a.GF.f,HEAD:a.GF.CCc,POST:a.GF.UMc,PUT:a.GF.BOc,DELETE:a.GF.aq,TRACE:a.GF.S7c,OPTIONS:a.GF.QLc,CONNECT:a.GF.fjc,PATCH:a.GF.fMc};a.BI={q_b:1,A1b:2,Q1:3,US:4,zxb:5};a.BI.G={NOTEXECUTED:a.BI.q_b,PROCESSING:a.BI.A1b,COMPLETED:a.BI.Q1,FAILED:a.BI.US,CANCELLED:a.BI.zxb};c.QYb=function(){r.w.call(this);this.GYa="";this.y0=null;this.RWa=
a.GF.f;this.fra=null;this.PJ=new c.fNa;this.Cga=a.BI.q_b;this.uvb=0;this.vcc=!1;this.qh=null};var r=c.u(c.QYb,c.pd);r.U=function(){this.y0=null;this.$jb(null);this.qh&&(this.qh.Ab(),this.qh=null);r.j.U.call(this)};r.rb=function(){null==this.qh&&(this.qh=e.Gs(new c.nNa("")),this.qh.ua());return this.qh};r.mz=function(){return this.GYa};r.NZc=function(a){this.GYa=a};r.bpd=function(){return this.RWa};r.IXc=function(a){this.RWa=a};r.u5a=function(){return this.PJ};r.czc=function(){return this.fra};r.$jb=
function(a){null!=this.fra&&this.fra.Ab();this.fra=a;null!=this.fra&&this.fra.ua()};r.Drd=function(){return this.Cga};r.qAc=function(){return this.uvb};r.xZc=function(a){this.uvb=a};r.bod=function(){return this.vcc};r.UFd=function(a){this.vcc=a};r.u6b=function(g,f){var d=this;d.$jb(null);var h=d.y0=new XMLHttpRequest,l=e.Ja(d.RWa,a.GF.G),p=d.mz();h.onreadystatechange=function(){4==h.readyState?(d.$jb(e.Gs(new c.keb(h))),0!==h.status&&(d.Cga=a.BI.Q1,d.za(a.K.Q1),b.gx(f))):d.Cga=a.BI.A1b};h.onerror=
function(){d.Cga=a.BI.US;d.za(a.K.US);b.gx(f)};h.ontimeout=function(){d.Cga=a.BI.US;d.za(a.K.US);b.gx(f)};h.open(l,p,g);g&&(h.timeout=this.uvb);this.afc(h);l="";null!=this.qh&&(l=this.qh.Jo());h.send(l)};r.psa=function(){this.y0!==h&&(this.y0.abort(),this.Cga=a.BI.zxb)};r.TS=function(){this.u6b(!1,null)};r.j9=function(){this.u6b(!0,b.mQ())};r.afc=function(a){var b=this.PJ.Dc();if(0!=b)for(var c=0;c<b;c++){var e=this.PJ.hq(c);a.setRequestHeader(e.aja(),e.Ka())}};e.yb(c.QYb,"PRIM_WEB","HttpRequest",
{Wa:{Url:{f:r.mz,i:function(a){this.NZc(e.ma(a))}},Method:{f:function(){return e.Ja(this.RWa,a.GF.G)},i:function(b){this.IXc(e.Ba(b,a.GF.G))}},Content:{f:r.rb},Response:{f:r.czc},Headers:{f:r.u5a},Status:{f:function(){return e.Ja(this.Cga,a.BI.G)}},Timeout:{f:r.qAc,i:function(a){this.xZc(e.aa(a))}}},Gc:{Cancel:r.psa,Execute:r.TS,ExecuteAsync:r.j9}});c.keb=function(a){g.w.call(this);this.y0=a;this.PJ=new c.fNa;this.qh=null;this.gJc(a.getAllResponseHeaders())};var g=c.u(c.keb,c.pd);g.U=function(){this.y0=
null;this.qh&&(this.qh.Ab(),this.qh=null);g.j.U.call(this)};g.rb=function(){null==this.qh&&(this.qh=e.Gs(new c.nNa(this.y0.responseText)),this.qh.ua());return this.qh};g.Rzc=function(){return this.y0.status};g.Szc=function(){return this.y0.statusText};g.u5a=function(){return this.PJ};g.gJc=function(a){for(var b=0,c="",e="";""!=a;){b=a.indexOf(":");if(-1==b)break;c=a.substring(0,b);a=a.slice(b+2);b=a.indexOf("\r\n");e=a.substring(0,b);a=a.slice(b+2);this.PJ.dh(c,e)}};e.yb(c.keb,"PRIM_WEB","HttpResponse",
{Wa:{Content:{f:g.rb},StatusCode:{f:g.Rzc},StatusText:{f:g.Szc},Headers:{f:g.u5a}}});c.nNa=function(a){l.w.call(this);this.zg=a};var l=c.u(c.nNa,c.pd);l.Jo=function(){return this.zg};l.oM=function(a){this.zg=a};e.yb(c.nNa,"PRIM_WEB","HttpContent",{Wa:{Text:{f:l.Jo,i:function(a){this.oM(e.ma(a))}}},qg:{vg:"Text"}})});
