window.LANSA.addSrc("json",function(e,c,a,b,h){function t(a,b,d){var f=null;if(null===d)f=e.Gs(new c.Vxa(a,b));else switch(typeof d){case "object":f=Array.isArray(d)?e.Gs(new c.kla(a,b)):e.Gs(new c.lla(a,b));f.uyb(d);break;case "number":f=e.Gs(new c.Wxa(a,b,d));break;case "string":f=e.Gs(new c.Xxa(a,b,d));break;case "boolean":f=e.Gs(new c.Uxa(a,b,d))}return f}e.Bb("PRIM_PCOL");a.rD={u3a:0,sFb:1,pFb:2,tFb:3,rFb:4,qFb:5};a.rD.G={NULL:a.rD.u3a,OBJECT:a.rD.sFb,ARRAY:a.rD.pFb,STRING:a.rD.tFb,NUMBER:a.rD.rFb,
BOOLEAN:a.rD.qFb};c.hYb=function(){p.w.call(this);this.zg="";this.QEa=null;this.t1=!1};var p=c.u(c.hYb,c.pd);p.U=function(){this.wQa(null);p.j.U.call(this)};p.izc=function(){return this.QEa};p.wQa=function(a){this.QEa=a};p.OAc=function(){return this.t1};p.HQa=function(a){this.t1=a};p.Jo=function(){return this.t1?JSON.stringify(this.QEa.TK()):this.zg};p.oM=function(a){this.zg=a;var b=null,c=null;try{b=JSON.parse(a)}catch(d){}b?(c=t(this,null,b),this.HQa(!0)):this.HQa(!1);this.wQa(c)};p.ekc=function(){this.wQa(e.Gs(new c.kla(this,
null)));this.HQa(!0);return this.QEa};p.fkc=function(){this.wQa(e.Gs(new c.lla(this,null)));this.HQa(!0);return this.QEa};e.yb(c.hYb,"PRIM_WEB","Json",{Wa:{Text:{f:p.Jo,i:function(a){this.oM(e.ma(a))}},IsValid:{f:p.OAc},RootItem:{f:p.izc}},Gc:{CreateRootArray:p.ekc,CreateRootObject:p.fkc},qg:{vg:"Text"}});c.T3=function(a,b){r.w.call(this);this.uE=a;this.yEa=b};var r=c.u(c.T3,c.pd);r.n$=function(){return a.rD.u3a};r.TK=function(){return null};r.Dc=function(){return 0};r.Ce=function(){return null};
r.Fw=function(){return null};r.Imd=function(){return this.uE};r.wyc=function(){return this.yEa};r.aja=function(){return this.yEa?this.yEa.gIb(this):""};r.gIb=function(){return""};r.tk=function(){return this.yEa?this.yEa.z5a(this):-1};r.z5a=function(){return-1};r.h8=function(){throw e.WPc(JSON.stringify(this.TK()));};r.tZa=function(){throw e.lza(JSON.stringify(this.TK()));};r.jZa=function(){throw e.Ahb(JSON.stringify(this.TK()));};r.Mr=function(){return null};r.ak=function(){};e.yb(c.T3,"PRIM_WEB",
"JsonElement",{Wa:{Key:{f:r.aja},Index:{f:function(){return this.tk()+1}},Type:{f:function(){return e.Ja(this.n$(),a.rD.G)}},Item:{f:function(a){return this.Ce(e.ma(a))}},ItemAt:{f:function(a){return this.Fw(e.aa(a)-1)}},ItemCount:{f:function(){return this.Dc()}},ParentItem:{f:r.wyc}},Gc:{AsString:function(){return this.h8()},AsNumber:function(){return e.mo(this.tZa())},AsBoolean:function(){return this.jZa()},Remove:function(a){return this.Mr(e.ma(a))},RemoveAt:function(a){return this.Nr(e.aa(a)-
1)},RemoveAll:function(){this.ak()}},qg:{vg:"Item"},oq:{wp:function(a){return this.Fw(e.aa(a)-1)},Lw:function(){return this.Dc()}}});c.kla=function(a,b){g.w.call(this,a,b);this.eb=[]};var g=c.u(c.kla,c.T3);g.n$=function(){return a.rD.pFb};g.TK=function(){for(var a=[],b=0;b<this.eb.length;b++)a.push(this.eb[b].TK());return a};g.Fw=function(a){return 0<=a&&a<this.eb.length?this.eb[a]:null};g.Dc=function(){return this.eb.length};g.z5a=function(a){for(var b=0;b<this.eb.length;b++)if(this.eb[b]===a)return b;
return-1};g.uyb=function(a){for(var b=0;b<a.length;b++){var c=t(this.uE,this,a[b]);c&&this.eb.push(c)}};g.a9a=function(){var a=e.Gs(new c.kla(this.uE,this));this.eb.push(a);return a};g.i9a=function(){var a=e.Gs(new c.lla(this.uE,this));this.eb.push(a);return a};g.k9a=function(a){a=e.Gs(new c.Xxa(this.uE,this,a));this.eb.push(a);return a};g.h9a=function(a){a=e.Gs(new c.Wxa(this.uE,this,a));this.eb.push(a);return a};g.d9a=function(a){a=e.Gs(new c.Uxa(this.uE,this,a));this.eb.push(a);return a};g.g9a=
function(){var a=e.Gs(new c.Vxa(this.uE,this));this.eb.push(a);return a};g.Nr=function(a){var b=null;0<=a&&a<this.eb.length&&(b=this.eb[a],this.eb.splice(a,1));return b};g.ak=function(){this.eb=[]};e.yb(c.kla,"PRIM_WEB","JsonArray",{Gc:{InsertArray:g.a9a,InsertObject:g.i9a,InsertNumber:function(a){return this.h9a(e.Us(a))},InsertString:function(a){return this.k9a(e.ma(a))},InsertBoolean:function(a){return this.d9a(e.Ha(a))},InsertNull:g.g9a}});c.lla=function(a,b){l.w.call(this,a,b);this.eb={}};var l=
c.u(c.lla,c.T3);l.n$=function(){return a.rD.sFb};l.TK=function(){var a={},b;for(b in this.eb)a[b]=this.eb[b].TK();return a};l.Ce=function(a){a=this.eb[a];return a===h?null:a};l.Fw=function(a){var b=this.lba();return 0<=a&&a<b.length?this.eb[b[a]]:null};l.Dc=function(){return this.lba().length};l.gIb=function(a){for(var b in this.eb)if(this.eb[b]===a)return b};l.z5a=function(a){var b=-1,c;for(c in this.eb)if(b++,this.eb[c]===a)break;return b};l.uyb=function(a){for(var b in a){var c=t(this.uE,this,
a[b]);c&&(this.eb[b]=c)}this.ZF()};l.ZF=function(){delete this.AE};l.lba=function(){if(this.AE===h){this.AE=[];for(var a in this.eb)this.AE.push(a)}return this.AE};l.a9a=function(a){var b=e.Gs(new c.kla(this.uE,this));this.eb[a]=b;this.ZF();return b};l.i9a=function(a){var b=e.Gs(new c.lla(this.uE,this));this.eb[a]=b;this.ZF();return b};l.k9a=function(a,b){var d=e.Gs(new c.Xxa(this.uE,this,b));this.eb[a]=d;this.ZF();return d};l.d9a=function(a,b){var d=e.Gs(new c.Uxa(this.uE,this,b));this.eb[a]=d;this.ZF();
return d};l.g9a=function(a){var b=e.Gs(new c.Vxa(this.uE,this));this.eb[a]=b;this.ZF();return b};l.h9a=function(a,b){var d=e.Gs(new c.Wxa(this.uE,this,b));this.eb[a]=d;this.ZF();return d};l.Mr=function(a){var b=null;this.eb[a]!==h&&(b=this.eb[a],delete this.eb[a],this.ZF());return b};l.Nr=function(a){var b=this.lba();return 0<=a&&a<b.length?this.Mr(b[a]):null};l.ak=function(){this.eb={};this.ZF()};e.yb(c.lla,"PRIM_WEB","JsonObject",{Gc:{InsertArray:function(a){return this.a9a(e.ma(a))},InsertObject:function(a){return this.i9a(e.ma(a))},
InsertNumber:function(a,b){return this.h9a(e.ma(a),e.Us(b))},InsertString:function(a,b){return this.k9a(e.ma(a),e.ma(b))},InsertBoolean:function(a,b){return this.d9a(e.ma(a),e.Ha(b))},InsertNull:function(a){return this.g9a(e.ma(a))}}});c.Wxa=function(a,b,c){s.w.call(this,a,b);this.cb=c};var s=c.u(c.Wxa,c.T3);s.n$=function(){return a.rD.rFb};s.TK=function(){return this.cb};s.tZa=function(){return this.cb};s.h8=function(){return this.cb.toString()};e.yb(c.Wxa,"PRIM_WEB","JsonNumber",{});c.Xxa=function(a,
b,c){f.w.call(this,a,b);this.cb=c};var f=c.u(c.Xxa,c.T3);f.n$=function(){return a.rD.tFb};f.TK=function(){return this.cb};f.h8=function(){return this.cb};f.tZa=function(){if(isNaN(Number(this.cb)))throw e.lza(this.cb);return new c.Vi(this.cb)};f.jZa=function(){if("TRUE"==this.cb.toUpperCase())return!0;if("FALSE"==this.cb.toUpperCase())return!1;throw e.Ahb(this.cb);};e.yb(c.Xxa,"PRIM_WEB","JsonString",{});c.Uxa=function(a,b,c){d.w.call(this,a,b);this.cb=c};var d=c.u(c.Uxa,c.T3);d.n$=function(){return a.rD.qFb};
d.TK=function(){return this.cb};d.jZa=function(){return this.cb};d.h8=function(){return this.cb?"true":"false"};e.yb(c.Uxa,"PRIM_WEB","JsonBoolean",{});c.Vxa=function(a,b){w.w.call(this,a,b)};var w=c.u(c.Vxa,c.T3);w.n$=function(){return a.rD.u3a};w.TK=function(){return null};e.yb(c.Vxa,"PRIM_WEB","JsonNull",{})},{rp:["PRIM_PCOL"]});
