window.LANSA.addSrc("evef",function(e,c,a,b){e.Bb("PRIM_EVP");e.Bb("PRIM_EDIT");c.ERb=function(b){h.w.call(this,b);this.vl|=a.v3a.Fpb;this.Ye|=268435456;this.$a=new c.DRb(this);this.$a.Ia(this);this.$a.Fa(this,a.K.fh,this.Xy)};var h=c.u(c.ERb,c.H3);h.zb=function(){b.ea(this.$a);this.$a=null;h.j.zb.call(this)};h.G$=function(){return this.$a};h.bn=function(b){this.$a.fl()!=b&&(this.$a.bn(b),this.fa(a.a.g))};h.fl=function(){return this.$a.fl()};h.Ur=function(b){this.$a.np()!=b&&(this.$a.Ur(b),this.fa(a.a.g))};
h.np=function(){return this.$a.np()};h.FU=function(b){this.$a.zF()!=b&&(this.$a.FU(b),this.fa(a.a.g))};h.zF=function(){return this.$a.zF()};h.vF=function(){return this.It()!=this.Jt()};h.Jt=function(){return this.$a.Jt()};h.ny=function(a){this.$a.ny(a)};h.It=function(){return this.$a.It()};h.my=function(a){this.$a.my(a)};h.ic=function(){return this.$a.ic()};h.Et=function(){return this.$a.ga};h.eG=function(a){1==a?this.Ll(268435456):this.Ll(0)};h.RC=function(){var a=0;268435456==this.ai()&&(a=1);return a};
h.Ll=function(b){this.ai()!=b&&(this.Ye=this.Ye&~a.Fh.jia|b,this.Mg(),this.l(a.a.g))};h.ai=function(){return this.Ye&a.Fh.jia};h.tLa=function(){return this.dB()?!0:!1};h.dB=function(){return 0<this.ai()};h.UBa=function(){this.zs()&&this.zs().uc(this.Dqa);this.$a&&this.$a.uc(this.pqa)};h.pwa=function(){this.$a.Hf(this.vb());this.$a.Vv(!0);this.$a.Yt(!0);this.$a.I4(this.XS());this.$a.ck(this.bg());this.$a.XL(this.Mi());this.$a.X4(this.$J);this.$a.Em(this.bm());this.$a.ql(this.hl());this.$a.Yr(this.Bu());
this.$a.nl(this.dj());this.$a.ml(this.Ci());this.$a.Ml(this.Wj());this.vb().sLa()&&this.$a.ly("*")};h.cY=function(a){this.pwa();h.j.cY.call(this,a)};h.Ki=function(){this.pwa();h.j.Ki.call(this)};h.pe=function(a){if(this.$a){var c=this.ye(),e,l,s;this.qd()?(l=this.Zg,s=this.$g,e=c.$()-(this.Zg+this.hj),c=c.ba()-(this.$g+this.gj)):(l=this.mf(),s=this.hf(),e=c.$()-(this.mf()+this.pg()),c=c.ba()-(this.hf()+this.Bg()));this.$a.mb(b.Cd(l,s,e,c))}h.j.pe.call(this,a)};h.Hia=function(){var a;this.$a&&(a=this.$a.Uj());
return a};h.oJ=function(a,b){a&&a.va(this,this.Ij);b&&b.ya(this,this.Ij);this.$a.Hf(b)};h.Gn=function(){this.$a.ze()};h.Xi=function(a){null!=this.$a&&this.$a.XL(this.Mi());h.j.Xi.call(this,a);this.$a&&(this.$a.Aq(null),this.$a.Vv(!0),this.$a.Yt(!0),this.Lx&&this.$a.Aq(this.Lx))};h.vpb=function(){this.$a&&this.$a.r$b()};h.E4=function(a,b){this.$a&&this.$a.E4(a,b)};h.gO=function(){this.$a&&this.$a.gO()};h.$E=function(a){this.$a&&this.$a.$E(a)};h.YF=function(a){this.$a&&this.$a.YF(a)};h.Xy=function(){this.zc()};
h.Ij=function(){};h.JHa=h[a.R.Caa]=function(){this.$a&&this.e5(this.LX())};h.SW=h[a.R.Nw]=function(){this.$a.ze()};h.rO=h[a.R.tL]=function(){this.$a.ze()};e.gd(c.ERb,"PRIM_EVEF",{rB:a.Br.FS,Wa:{ComponentVersion:{f:h.RC,i:function(a){this.eG(e.aa(a))}},AutoTab:{f:h.XS,i:function(a){this.I4(e.Ha(a))}},AutoSelect:{f:h.bm,i:function(a){this.Em(e.Ha(a))}},WordWrap:{f:h.cg,i:function(a){this.vh(e.Ha(a))}},ShowSelection:{f:h.hl,i:function(a){this.ql(e.Ha(a))}},ShowSelectionHilight:{f:h.Bu,i:function(a){this.Yr(e.Ha(a))}},
ShowPrompter:{f:h.a3,i:function(a){this.fna(e.Ha(a))}},PrompterImage:{f:h.XJa,i:h.Y4},PrompterTabStop:{f:h.ava,i:function(a){this.Yjb(e.Ha(a))}},UsePicklist:{f:h.AKa,i:function(a){this.OZ(e.Ha(a))}},EditAlignment:{f:function(){return e.Ja(this.dj(),a.sn.G)},i:function(b){this.nl(e.Ba(b,a.sn.G))}},DisplayAlignment:{f:function(){return e.Ja(this.Ci(),a.Qi.G)},i:function(b){this.ml(e.Ba(b,a.Qi.G))}},Text:{f:h.Gia},SelectionEnd:{f:h.It,i:function(a){this.my(e.aa(a))}},SelectionStart:{f:h.Jt,i:function(a){this.ny(e.aa(a))}},
VisualStyleEdit:{f:h.m7a,i:h.xAa},NumericEditStyle:{f:function(){return e.Ja(this.Wj(),a.km.G)},i:function(b){this.Ml(e.Ba(b,a.km.G))}},HasSelection:{f:h.vF},EditStyle:{f:h.z2,i:h.ica},EditStyles:{f:h.Qia},EditMouseOverStyle:{f:h.pJa,i:h.IPa},EditMouseOverStyles:{f:h.qJa},EditFocusedStyle:{f:h.nJa,i:h.HPa},EditFocusedStyles:{f:h.oJa},LabelStyle:{f:h.I2,i:h.qca},LabelStyles:{f:h.BJa},LabelMouseOverStyle:{f:h.zJa,i:h.ZPa},LabelMouseOverStyles:{f:h.AJa},InputType:{f:function(){return e.Ja(this.fl(),
a.Rd.G)},i:function(b){this.bn(e.Ba(b,a.Rd.G))}},InputTypePattern:{f:h.np,i:function(a){this.Ur(e.ma(a))}},SpellCheck:{f:h.zF,i:function(a){this.FU(e.Ha(a))}},Value:{f:function(){return this.Ka()},i:function(a){this.Va(a)}}},Gc:{SelectText:function(a,b){this.E4(e.aa(a)-1,e.aa(b))}},qg:{vg:"Value"}});c.DRb=function(a){t.w.call(this);this.jcc=a};var t=c.u(c.DRb,c.lI);t.vT=function(){return this.jcc.iq()||this.jcc.aK?!1:t.j.vT.call(this)}},{rp:["PRIM_EVP","PRIM_EDIT"]});
