window.LANSA.addSrc("ppnl",function(e,c,a,b,h){e.Bb("PRIM_PHBN");e.Bb("PRIM_IMAG");e.Bb("PRIM_TBLO");a.lpa=9999;a.Xeb={hya:0,j_b:3};a.sI={Y3:0,xla:1,g_b:2};a.sI.G={NONE:a.sI.Y3,POPUP:a.sI.xla};a.$j={Tgb:129,zOa:1,Pgb:2,ahb:4,Vgb:8,Qgb:16,Sgb:32,Ugb:64,Xgb:128,$gb:256,Rgb:512,Zgb:1024,cBd:2048,Ygb:4096};a.eba={cfb:0,afb:1,dfb:2};a.gAd={F1b:0};a.vK={q0a:0,m0a:268435456,s0a:536870912};a.vK.G={HIDDEN:a.vK.q0a,ALL:a.vK.m0a,NONE:a.vK.s0a};a.Sla={wMc:0,igb:1,p0b:805306368};a.Fg={J5:0,MSa:1,Mob:3,Nob:4,T9b:5,
S9b:6,U9b:7,K9b:8,L9b:9,O9b:10,W9b:11,P9b:12,M9b:13,N9b:14,Q9b:15,R9b:16,V9b:17};a.Fg.G={NONE:a.Fg.J5,FADEINANDSCALE:a.Fg.MSa,SLIDEINLEFT:a.Fg.Mob,SLIDEINRIGHT:a.Fg.Nob,SLIDEINBOTTOM:a.Fg.T9b,NEWSPAPER:a.Fg.S9b,SLIDEINTOP:a.Fg.U9b,"3DFLIPHORIZONTAL":a.Fg.K9b,"3DFLIPVERTICAL":a.Fg.L9b,"3DSIGN":a.Fg.O9b,SUPERSCALED:a.Fg.W9b,"3DSLIT":a.Fg.P9b,"3DROTATEBOTTOM":a.Fg.M9b,"3DROTATEINLEFT":a.Fg.N9b,LETMEIN:a.Fg.Q9b,MAKEWAY:a.Fg.R9b,SLIPFROMTOP:a.Fg.V9b};a.Fg.Txa={NONE:a.Fg.J5,FADEINANDSCALE:a.Fg.MSa};a.Fg.LEb=
{"":a.Fg.J5,"md-effect-1":a.Fg.MSa,"md-effect-21":a.Fg.Mob,"md-effect-2":a.Fg.Nob,"md-effect-3":a.Fg.T9b,"md-effect-4":a.Fg.S9b,"md-effect-7":a.Fg.U9b,"md-effect-8":a.Fg.K9b,"md-effect-9":a.Fg.L9b,"md-effect-10":a.Fg.O9b,"md-effect-11":a.Fg.W9b,"md-effect-13":a.Fg.P9b,"md-effect-14":a.Fg.M9b,"md-effect-15":a.Fg.N9b,"md-effect-17":a.Fg.Q9b,"md-effect-18":a.Fg.R9b,"md-effect-19":a.Fg.V9b};c.GWb=function(a){t.w.call(this,a);this.nd=a};var t=c.u(c.GWb,c.M3);t.zb=function(){t.j.zb.call(this)};t.U=function(){this.ab.jZ();
t.j.U.call(this)};t.Ca=function(){return this.nd.rb()};t.Ma=function(){return null};t.U$=function(){return!0};t.V4=function(){};t.vca=function(){};t.uca=function(){};t.Vv=function(){};t.Yt=function(){};t.lja=function(){return null};t.DF=function(){return!1};t.qd=function(){return!0};t.vP=function(){return!0};t.CF=function(){return!1};t.iL=function(){return!1};t.ae=function(b){b[0]=a.VLa;b[1]=a.TLa};t.Rbd=function(){};t.pS=function(a){t.j.pS.call(this,a)};t.Hfc=function(){return!1};t.Aba=function(){};
t.yf=function(){};t.n4=function(){};t.Tt=function(){};t.r4=function(){};t.zz=function(){};c.Sw=function(){e.Bb("PRIM_IMAG");e.Bb("PRIM_TBLO");e.Bb("PRIM_LABL");p.w.call(this);this.Rc=b.Cd(10,10,280,120);this.xf=a.$j.Tgb;this.Yk=this.qh=this.HQ=this.qm=null;this.Ix=a.Fg.J5;this.t7=a.vj.Ww;this.DEa=this.$V=this.ZV=null;this.vf=new c.wd(0,0);this.LXa=this.J7=this.ur=this.Jy=this.nA=this.Hx=this.qa=this.Wp=this.FN=this.pm=null;this.pFa="";this.KXa=12;this.yga=a.m.cc;b.Q().bEc(this);this.Afc();b.Q().Lqc();
var d=null;this.qa=new c.yz;b.rq(this.qa);b.zp(this.qa);this.Wp=new c.hm;this.Wp.mb(new c.ja(0,0,0,30));this.Wp.cf(!1);this.Wp.yq(!1);this.Wp.ol(this.qa);this.Wp.wca();this.Hx=new c.Ns;this.Hx.cf(!1);this.Hx.OI(a.og.nQ);this.Hx.Ia(this.Wp);this.Hx.SD(a.ie.DD);this.nA=new c.Ns;this.nA.OI(a.og.Xca);this.nA.Ia(this.Wp);this.nA.cf(!1);this.nA.Fa(this,a.K.nc,this.Ulc);this.nA.Fa(this,a.K.OP,this.Vlc);this.nA.Fa(this,a.K.PP,this.Wlc);this.Jy=new c.Kr;this.Jy.Ia(this.Wp);this.Jy.cf(!1);this.Jy.Mn(a.xh.Gq);
this.Jy.vh(!1);this.Jy.xk(a.tn.MEb);b.$c(this.qa,this.Wp,null,null,1,1);d=b.$c(this.qa,this.Hx,this.qa.hd(0),this.qa.od(0),1,1);d.Qb(a.Ea.Zk);d.jc(a.ka.ek);d.Ne(2);d=b.$c(this.qa,this.nA,this.qa.hd(0),this.qa.od(0),1,1);d.Qb(a.Ea.sw);d.jc(a.ka.$d);d.Ie(2);d=b.$c(this.qa,this.Jy,this.qa.hd(0),this.qa.od(0),1,1);d.Qb(a.Ea.gf);d.jc(a.ka.ek);this.cf(!1);this.Bfb(c.HMa)};var p=c.u(c.Sw,c.hm);p.zb=function(){b.ea(this.Uad);this.Uad=null;b.ea(this.Wp);this.Wp=null;b.ea(this.Hx);this.Hx=null;b.ea(this.nA);
this.nA=null;b.ea(this.Jy);this.Jy=null;p.j.zb.call(this)};p.U=function(){p.j.U.call(this);this.aca(null);this.mPa(null);this.oQa(null);this.pQa(null);this.$ba(null);this.vkb(null);b.Q().CPc(this);b.ea(this.Yk);this.Yk=null;b.ea(this.DEa);this.DEa=null};p.Cg=function(){var a=c.V3;this.pY()&&(a=c.YYb);return a};p.hqd=function(){return this.t7};p.ija=function(){if(null==this.DEa){var a=new c.GWb(this);this.DEa=b.Taa(a);this.ya(this,this.boc)}return this.DEa};p.aca=function(b){this.qm!=b&&(this.qm&&
this.qm.va(this),(this.qm=b)&&this.qm.ya(this,this.MAb),this.l(a.a.g))};p.ruc=function(){return this.qm};p.jua=function(){var a=null;this.qm&&this.qm instanceof c.Pt&&(a=this.qm);return a};p.mPa=function(b){this.HQ!=b&&(this.HQ&&this.HQ.va(this),(this.HQ=b)&&this.HQ.ya(this,this.Blc),this.l(a.a.g))};p.Gid=function(){return this.HQ};p.oQa=function(b){this.ZV!=b&&(this.ZV&&this.ZV.va(this),(this.ZV=b)&&this.ZV.ya(this,this.$nc),this.l(a.a.g))};p.fqd=function(){return this.ZV};p.pQa=function(b){this.$V!=
b&&(this.$V&&this.$V.va(this),(this.$V=b)&&this.$V.ya(this,this.aoc),this.l(a.a.g))};p.gqd=function(){return this.$V};p.rb=function(){var a=this.qh;!this.qh||this.qh instanceof c.Sw||(a=this.qh);!a&&this.x$a()&&(a=this);return a};p.Dkd=function(){return this.qh};p.GX=function(){null==this.Yk&&(this.Yk=new c.Uaa,this.Yk.$4b(),this.Yk.uAa(a.eu.HSa));return this.Yk};p.Dyc=function(){return this.Yk};p.trd=function(){return this.vf};p.Cn=function(){this.Dg();return this.Sf};p.H4=function(b){b=this.xf&
~a.$j.Pgb|(b?a.$j.Pgb:0);this.xf!=b&&(this.xf=b,this.l(a.a.g))};p.nPa=function(b){b=this.xf&~a.$j.zOa|(b?a.$j.zOa:0);this.xf!=b&&(this.xf=b,this.l(a.a.g))};p.v4a=function(){return 0!=(this.xf&a.$j.zOa)};p.C3b=function(b){b=this.xf&~a.$j.Qgb|(b?a.$j.Qgb:0);this.xf!=b&&(this.xf=b,this.l(a.a.g))};p.PGb=function(){return 0!=(this.xf&a.$j.Qgb)};p.ukb=function(b){b=this.xf&~a.$j.$gb|(b?a.$j.$gb:0);this.xf!=b&&(this.xf=b,this.BQ(this.ye()),this.l(a.a.g))};p.g7a=function(){return 0!=(this.xf&a.$j.$gb)};p.zzc=
function(){return this.KXa};p.r5b=function(b){b!=this.KXa&&(this.KXa=b,this.kb(),this.fa(a.a.g))};p.urd=function(){return this.yga};p.kkb=function(b){if(this.B$a()||this.yga!=b)this.yga=b,this.l(a.a.g)};p.HYc=function(){!1==this.B$a()&&(this.yga=a.m.cc,this.l(a.a.g))};p.U3b=function(b){b=this.xf&~a.$j.Rgb|(b?a.$j.Rgb:0);this.xf!=b&&(this.xf=b,this.BQ(this.ye()),this.l(a.a.g))};p.WIa=function(){return 0!=(this.xf&a.$j.Rgb)};p.mGd=function(b){b=this.xf&~a.$j.Ygb|(b?a.$j.Ygb:0);this.xf!=b&&(this.xf=
b,this.l(a.a.g))};p.Uyc=function(){return 0!=(this.xf&a.$j.Ygb)};p.wB=function(b){b=this.xf&~a.$j.Vgb|(b?a.$j.Vgb:0);this.xf!=b&&(this.xf=b,this.l(a.a.g))};p.aXc=function(b){b=this.xf&~a.$j.Ugb|(b?a.$j.Ugb:0);this.xf!=b&&(this.xf=b,this.l(a.a.g))};p.dGd=function(b){b=this.xf&~a.$j.Xgb|(b?a.$j.Xgb:0);this.xf!=b&&(this.xf=b,this.l(a.a.g))};p.sZ=function(b){b=this.xf&~a.$j.Sgb|(b?a.$j.Sgb:0);this.xf!=b&&(this.xf=b,this.l(a.a.g))};p.kHb=function(){return 0!=(this.xf&a.$j.Sgb)};p.jHb=function(){return this.pm};
p.$ba=function(b){this.pm!=b&&(null!=this.pm&&(this.pm.va(this,this.I1a),this.pm.Ab()),this.pm=b,null!=this.pm&&(this.pm.ua(),this.pm.ya(this,this.I1a)),this.BQ(this.ye()),this.fa(a.a.g))};p.tAc=function(){return this.FN};p.vkb=function(b){this.FN!=b&&(null!=this.FN&&(this.FN.va(this,this.ACb),this.FN.Ab()),this.FN=b,null!=this.FN&&(this.FN.ua(),this.FN.ya(this,this.ACb)),this.BQ(this.ye()),this.fa(a.a.g))};p.Azc=function(){return this.ija().Xf()};p.s5b=function(b){this.ija().Xf()!=b&&(this.ija().Cb(b),
this.l(a.a.g))};p.Bzc=function(){return this.ija().qj()};p.ib=function(){var a=null;null!=this.Ma()&&(a=this.Ma().ib());return a};p.Lsc=function(){var a=!1;if(this.pY()||!this.x$a())a=!0;return a};p.sAc=function(){return this.pFa};p.BZc=function(b){this.pFa!=b&&(this.pFa=b,this.kb(),this.fa(a.a.g))};p.Qxc=function(){return this.qa};p.m2=function(){return this.qa};p.Di=function(){var a=!1;null!=this.Ma()&&(a=this.Ma().ib(),a=b.Kd[a].GQ);return a};p.y9a=function(){return 0!=(this.xf&a.$j.Pgb)};p.nLa=
function(){return 0!=(this.xf&a.$j.zOa)};p.i$a=function(){return 0!=(this.xf&a.$j.Vgb)};p.Yud=function(){return 0!=(this.xf&a.$j.Ugb)};p.x$a=function(){return 0!=(this.xf&a.$j.Xgb)};p.mka=function(){return 0!=(this.xf&a.$j.ahb)};p.pY=function(){return 0!=(this.xf&a.$j.Zgb)};p.U9a=function(){return!1};p.B$a=function(){return!1==this.OKb()};p.OKb=function(){return this.yga!=a.m.cc};p.YX=function(){var a=!1;this.rb()==this&&this.rb().Z()&&this.rb().Z()!=this.Yk&&(a=!0);return a};p.eU=function(){if(null!=
this.Ma()){var a=this.K$()?this.K$().Jh():"DEFAULT";b.HTa(this.Ma().ib(),a)}};p.kOc=function(a){var c=!1;this.Di()&&this.nLa()&&!this.mka()&&this.jua()&&null!=a&&b.Q().lB(this.jua())==a&&(c=!0);return c};p.lOc=function(a){var c=!1;if(this.Di()&&this.nLa()&&!this.U9a()&&!this.mka())if(null==a)c=!0;else for(var d=b.Q().lB(a),c=!0;null!=a&&null!=d;)d==this?(c=!1,a=null):null!=d&&(d.jua()?(d=d.jua(),a=a!=d?d:null):a=null),d=b.Q().lB(a);return c};p.BQ=function(d,e){e===h&&(e=!1);if(!b.Q().ZX()){var f=
new c.ja(0,0,d.$(),30),g=d.$()-4;this.WIa()&&(g-=f.ba());this.FN&&(g-=f.ba());this.Jy.bc(this.Kb());this.Jy.hc(Math.min(g,this.Jy.tKa(this.Jy.Kb(),this.Jy.bz().length)+10));this.Wp.Ia(this.g7a()?this:null);this.Wp.mb(f);this.Wp.uc(""==this.pFa?a.Dka:this.pFa);this.Hx.Nb(this.WIa());this.Hx.hc(f.ba());this.Hx.Nb(null!=this.FN);this.Hx.bd(this.FN);this.Hx.mb(new c.ja(this.Hx.se(),this.Hx.He(),Math.min(this.Hx.Ic()?this.Hx.Ic().fb():this.Wp.Ua(),this.Wp.Ua()-4),Math.min(this.Hx.Ic()?this.Hx.Ic().Ua():
this.Wp.Ua(),this.Wp.Ua()-4)));this.nA.Nb(this.WIa());this.nA.mb(new c.ja(this.nA.se(),this.nA.He(),30,29));this.nA.Yi(this.pm?this.pm:a.Xb.t$c);e?b.Q().pfc(this.nA):b.Q().LPc(this.nA);this.Wp.Z()&&d.Ta(d.M()+f.ba());this.Ob()&&this.Dg()}};p.pe=function(a){this.BQ(a);p.j.pe.call(this,a)};p.Dg=function(){this.YX()||this.Ia(this.GX());this.gWc(this.pY());this.Lsc()&&p.j.Dg.call(this)};p.Ki=function(){p.j.Ki.call(this);this.BQ(this.ye())};p.Kgb=function(b,c,d){p.j.Kgb(b,c,d);d[0]&&this.kP()!=a.Ru.Loa&&
this.g7a()&&(d[0]=this.Wp==c||this.Jy==c)};p.ae=function(b){""==b[0]&&(b[0]=a.VLa);""==b[1]&&(b[1]=a.TLa);p.j.ae.call(this,b)};p.lma=function(a){return this.t9(this.qm,a)};p.Egb=function(a){return this.Hta(a)};p.kma=function(){null!=this.Yk&&(null!=this.rb()&&this.Lr(this.rb(),a.R.xab),this.aca(null),this.i$a()||null==this.HQ||this.v4a()||b.Zka()!=this.HQ||this.HQ.Cz(this.HQ.TC()),this.mPa(null),this.oQa(null),this.pQa(null));this.y9a()&&this.Zn()};p.Fgb=function(){};p.nza=function(){this.vf.rl(this.se());
this.vf.yk(this.He());this.Di()&&this.fx(this.t7,this.ZV,this.vf,this.qm,this.$V,this.Ix)};p.l5=function(d,e,f,g,l){var p=b.Hl();this.YX()&&(p.rl(this.se()),p.yk(this.He()));d==h&&(d=p.Db());e==h&&(e=p.Eb());f==h&&(f=a.vj.Ww);g==h&&(g=a.Fg.J5);this.fx(f,null,new c.wd(d,e),l,null,g)};p.fx=function(d,e,f,g,l,p){d==h&&(d=a.vj.Ww);e==h&&(e=null);f==h&&(f=b.Hl());g==h&&(g=null);l==h&&(l=null);p==h&&(p=a.Fg.J5);if(this.Di()&&this.x$a()){if(this.ZV==e&&this.$V==l&&this.qm==g&&this.t7==d&&this.Ix==p){d=b.Cd(f.Db(),
f.Eb(),this.rb().fb(),this.rb().Ua());b.HWb(this,d);this.GX().mb(new c.ja(0,0,d.$(),d.ba()));f.rl(d.O());f.yk(d.M());this.rb().mb(d);this.c6b(this.ija().gD());this.vf=f;return}var w=this.y9a();this.H4(!1);this.qn();this.kma();this.H4(w)}this.t7!=a.vj.Ww&&this.Z()!=this.Yk&&this.Ia(null);this.xf|=a.$j.Zgb;this.akb(!1);null!=this.Cn()&&(this.aca(g),this.GX(),this.Uyc()&&this.Lr(this.GX(),a.R.OLa),this.mPa(b.Zka()),this.t7=d,this.Ix=p,this.BQ(this.ye()),this.CMc(f,this.i$a()),this.Z()==this.GX()?this.Lr(this.GX(),
a.R.Eaa):this.Lr(this,a.R.Eaa),this.oQa(e),this.pQa(l),this.PGb()&&this.rb().ze(!0),this.Wrc())};p.qn=function(){if(this.Di()){var c=b.Q().Oj;c&&c.Jr(this)&&this.Lr(c,a.R.Lv);b.Q().Lic(this);null!=this.Ma()&&(c=this.Ma().ib(),b.Kd[c].ssa());this.Hrc();this.kma()}else b.Q().Q0&&(c=b.Q().Q0,c.Ma()&&c.Ma().GQ&&c==this.qm&&b.Q().su(c,!1))};p.Ifc=function(a){for(var b=this.ga.gD(),c=null,d=b.length-1;null!=b&&0<=d&&null!=(c=b[d]);d--)a.splice(0,0,c)};p.CMc=function(a,c){this.Ma()&&(c||(b.Q().lu&&b.Q().lu.ECc(),
b.Q().Qq(this.jua(),!1,this)),this.DMc(a))};p.DMc=function(c){if(this.lma(c)&&this.rb()){this.rb().Dg();this.rb().qz(!0);c=this.Yk;c.uP()||c.cOa();c=this.Ma().ib();a.lpa+=2;b.Kd[c].EEa=a.lpa;b.cqb(c,b.Kd[c].Ag());b.Kd[c].lna();var d=b.Kd[c].la.ur?b.Kd[c].la.ur.Ma():null;d&&d.v.parentElement!=document.body&&(null!=d.v.parentElement&&d.v.parentElement.removeChild(d.v),d.v.style.zIndex=b.Kd[c].EEa-1,document.body.appendChild(d.v))}};b.HWb=function(c,d){switch(c.t7){case a.vj.dOa:var e=b.NF();d.Ar(e);
break;case a.vj.Rla:var e=b.NF(),f=0,g=0,f=(e.$()-d.fb())/2,g=(e.ba()-d.Ua())/2;d.Lb(f,g);c.YX()&&d.Ar(c.Z().Jza(d));break;case a.vj.uMc:e=b.NF();f=(e.$()-d.fb())/2;g=e.pa-d.Ua();d.Lb(f,g);c.YX()&&d.Ar(c.Z().Jza(d));break;case a.vj.vMc:e=b.NF();f=(e.$()-d.fb())/2;d.Lb(f,0);c.YX()&&d.Ar(c.Z().Jza(d));break;case a.vj.o0b:e=b.NF();g=(e.ba()-d.Ua())/2;f=e.na-d.fb();d.Lb(f,g);c.YX()&&d.Ar(c.Z().Jza(d));break;case a.vj.n0b:e=b.NF();g=(e.ba()-d.Ua())/2;d.Lb(0,g);c.YX()&&d.Ar(c.Z().Jza(d));break;default:e=
b.NF(),d.na>e.na&&d.Lb(Math.max(0,e.na-d.$()),d.M()),d.pa>e.pa&&d.Lb(d.O(),Math.max(0,e.pa-d.ba())),d.O()<e.O()&&d.Lb(0,d.M()),d.M()<e.M()&&d.Lb(d.O(),0)}};p.lKc=function(){b.Q();this.ur=new c.hm;this.ur.Fa(this,a.K.aZa,this.roc);this.ur.Fa(this,a.K.nc,this.soc);this.ur.tf(1);this.ur.Qa(0);this.ur.ina(1);this.ur.Ta(0);this.ur.Nb(!1);this.LXa=new c.eg;this.J7=new c.tb;this.J7.sd(this.LXa)};p.c6b=function(a){var d=b.Q().fr;this.ur||this.lKc();if(!this.ur.Ob()){this.LXa.Ad(this.yga);this.LXa.gg(this.KXa);
this.ur.Cb(this.OKb()?this.J7:null);for(var e=0;e<a.length;e++)this.ur.io(a[e]);null==this.ur.Xf()?this.ur.Ia(null):(this.ur.Ia(d),this.ur.Dg(),this.ur.tf(1),this.ur.AO())}this.ur.mb(new c.ja(0,0,d.fb(),d.Ua()))};p.GCc=function(){this.ur.sb()&&this.ur.Eo()};p.Lj=function(c){var d=this.Ma().ib();a.lpa+=2;b.Kd[d].EEa=a.lpa;b.cqb(d,b.Kd[d].Ag());p.j.Lj.call(this,c)};p.t9=function(d,f){var g=!0,h=e.Tb(),l=this.rb().fb(),p=this.rb().Ua();h.Zb("CONTEXT",d);h.rA("LEFT",f.Db());h.rA("TOP",f.Eb());h.rA("WIDTH",
l);h.rA("HEIGHT",p);h.WN("TRANSITION",this.Ix,a.Fg.G);h.af("CONTINUE",!0);this.za(a.K.mB,h);f.rl(h.Yia("LEFT"));f.yk(h.Yia("TOP"));g=h.Nf("CONTINUE");l=l==h.Yia("WIDTH")?this.rb().fb():h.Yia("WIDTH");p=p==h.Yia("HEIGHT")?this.rb().Ua():h.Yia("HEIGHT");l=new c.ja(f.Db(),f.Eb(),l,p);b.HWb(this,l);this.GX().mb(new c.ja(0,0,l.$(),l.ba()));f.rl(l.O());f.yk(l.M());this.rb().mb(l);this.Ix=h.m5a("TRANSITION",a.Fg.G);h.qc();this.vf=f;return g};p.Hta=function(b){var c=!1,c=e.Tb();c.af("IMMEDIATE",b);c.af("CLOSEPOPUP",
!0);this.za(a.K.P1,c);b||this.Ix!=a.Fg.J5?c=!0:(c=c.Nf("CLOSEPOPUP"),c||(this.xf|=a.$j.ahb));return c};p.Hrc=function(){this.za(a.K.u8);this.xf&=~a.$j.ahb;this.xf&=~a.$j.Zgb;this.akb(!0);this.YX()&&this.Z().kb()};p.Wrc=function(){this.za(a.K.Lfb)};p.roc=function(){this.ur.sb()||(this.ur.Ia(null),this.Fgb())};p.soc=function(){this.U9a()&&this.nLa()&&this.qn()};p.Vlc=function(){this.BQ(this.ye(),!0)};p.Wlc=function(){this.BQ(this.ye())};p.Ulc=function(a,c){b.Q().su(this,!1);c.Wo("HANDLED",!0)};p.boc=
function(){};p.MAb=function(b,c){switch(c.Ya){case a.a.ub:this.aca(null)}};p.$nc=function(b,c){switch(c.Ya){case a.a.ub:this.oQa(null)}};p.aoc=function(b,c){switch(c.Ya){case a.a.ub:this.pQa(null)}};p.Blc=function(b,c){switch(c.Ya){case a.a.ub:this.mPa(null)}};p.I1a=function(b,c){switch(c.Ya){case a.a.ub:case a.a.Vb:this.$ba(null)}};p.ACb=function(b,c){switch(c.Ya){case a.a.ub:case a.a.Vb:this.vkb(null)}};p.dta=p[a.R.wka]=function(){this.pY()&&this.nza()};p.FC=p[a.R.Mv]=function(a){p.j.FC.call(this,
a);this.BQ(this.ye())};p.lp=p[a.R.vD]=function(a){p.j.lp.call(this,a);this.BQ(this.ye())};e.gd(c.Sw,"PRIM_PPNL",{Wa:{CloseOnClick:{f:p.kHb,i:function(a){this.sZ(e.Ha(a))}},AutoClose:{f:p.v4a,i:function(a){this.nPa(e.Ha(a))}},AutoFocus:{f:p.PGb,i:function(a){this.C3b(e.Ha(a))}},TitleBar:{f:p.g7a,i:function(a){this.ukb(e.Ha(a))}},ShroudColor:{f:function(){return this.B$a()?e.Qe:b.mh(this.yga)},i:function(a){a===e.Qe?this.HYc():this.kkb(b.lh(e.ma(a)))}},ShroudOpacity:{f:p.zzc,i:function(a){this.r5b(e.aa(a))}},
CloseButton:{f:p.WIa,i:function(a){this.U3b(e.Ha(a))}},CloseImage:{f:p.jHb,i:p.$ba},TitleImage:{f:p.tAc,i:p.vkb},ShroudStyle:{f:p.Azc,i:p.s5b},ShroudStyles:{f:p.Bzc},TitleBarThemeDrawStyle:{f:p.sAc,i:function(a){this.BZc(e.ma(a))}},IsOpen:{f:p.Di}},Gc:{ShowPopup:function(b,c,d,f,g){this.l5(b,c,d?e.Ba(d,a.vj.WJc):d,f?e.Ba(f,a.Fg.G):f,g)},ClosePopup:p.qn}});c.ydb=function(d){r.w.call(this,d);this.Rc=new c.ja(0,0,300,30);this.dra=a.Sla.wMc;this.jEa=new c.yz;this.P_=this.CJ=this.BJ=null;this.QQ=[];this.QWa=
null;b.rq(this.jEa);b.zp(this.jEa);this.ol(this.jEa);this.cf(!1);this.P_=new c.YMa;this.P_.aAa(a.sI.g_b);this.P_.Fa(this,a.K.mB,this.amc);this.BJ=new c.Ns;this.BJ.Ia(this);this.BJ.mb(new c.ja);this.BJ.Fa(this,a.K.nc,this.bmc);this.BJ.W4();this.QWa=new c.DWb(this)};var r=c.u(c.ydb,c.hm);r.zb=function(){r.j.zb.call(this)};r.U=function(){r.j.U.call(this);b.ea(this.QWa);this.QWa=null};r.Ztc=function(){return this.CJ};r.W3b=function(b){this.CJ!=b&&(null!=this.CJ&&(this.CJ.va(this,this.IAb),this.CJ.Ab()),
this.CJ=b,null!=this.CJ&&(this.CJ.ua(),this.CJ.ya(this,this.IAb)),this.kb(),this.l(a.a.g))};r.DYc=function(b){b=this.xf&~a.Sla.igb|(b?a.Sla.igb:0);this.dra!=b&&(this.dra=b,this.l(a.a.g))};r.t6a=function(){return 0!=(this.dra&a.Sla.igb)};r.SVc=function(b){this.XIa()!=b&&(this.dra=this.dra&~a.Sla.p0b|b,this.kb(),this.qz(),this.O0b(this.ye()),this.fa(a.a.g))};r.XIa=function(){return this.dra&a.Sla.p0b};r.V4a=function(){var b=null;switch(this.XIa()){case a.vK.s0a:case a.vK.q0a:b=r.j.V4a.call(this);break;
case a.vK.m0a:e.Bb("PRIM_PCOL"),b=new c.Vcb(this.P_),b=new c.KY(b)}return b};r.ae=function(b){""==b[0]&&(b[0]=a.TPb);""==b[1]&&(b[1]=a.AHc);r.j.ae.call(this,b)};r.Ggb=function(){this.ol(this.jEa)};r.Rv=function(c,d){r.j.Rv.call(this,c,d);this.Ggb();b.EWb(this,this.jEa,a.xa.oj,a.Ea.eF,a.ka.ek,this.H1a)};r.pe=function(a){r.j.pe.call(this,a);this.O0b(a)};r.O0b=function(d){switch(this.XIa()){case a.vK.s0a:for(this.BJ.Nb(!1);0<this.QQ.length;)this.QQ[0].Zn();break;case a.vK.q0a:for(var e=this.QQ.length,
f=0,g=null,h=this.ul,l=h.length-1;0<=l&&null!=(g=h[l]);l--)f=Math.max(f,g.Xc().na),g.Bs()>d.na&&(b.CWb(this,g),e++);h=this.QQ;for(l=0;l<h.length&&null!=(g=h[l]);l++)f+g.Xa.fb()<d.na?(g.Zn(),l--,e--):g.Ca().tf(l+1);if(0<e)this.BJ.Yi(this.CJ?this.CJ:a.Xb.Web),this.BJ.mb(new c.ja(d.na-(d.ba()+2),0,d.ba(),d.ba())),this.BJ.Nb(!0),this.P_.tOa();else for(this.BJ.Nb(!1);0<this.QQ.length;)this.QQ[0].Zn();break;case a.vK.m0a:for(;0<this.ul.length;)b.CWb(this,this.ul[this.ul.length-1]);this.BJ.Yi(this.CJ?this.CJ:
a.Xb.Web);this.BJ.mb(new c.ja(d.na-(d.ba()+2),0,d.ba(),d.ba()));this.BJ.Nb(!0);this.P_.tOa()}this.Ob()&&this.Dg()};b.EWb=function(c,d,e,f,g,h){for(var l=null,p=c.ul,w=1,s=0;s<p.length&&null!=(l=p[s]);s++,w++){var r=d.lf(l);r||(r=b.$c(d,l,d.hd(0),d.od(0),1,1),l.Fa(c,a.K.W3,h));r.ci(e);r.Qb(f);r.jc(g)}};r.IAb=function(b,c){switch(c.Ya){case a.a.ub:case a.a.Vb:this.W3b(null);break;case a.a.g:this.kb()}};r.amc=function(b,c){this.za(a.K.mB,c)};r.bmc=function(b,d){this.P_.fx(a.vj.Ww,this,new c.wd(this.jq()+
this.fb()-this.P_.fb(),this.kq()+this.Ua()),this);d.Wo("HANDLED",!0)};r.H1a=function(a){this.t6a()&&(a=a instanceof c.Xaa?a:null)&&a.NA()&&!a.NA().Di()&&(a.Bq(),this.QWa.rg())};e.yb(c.ydb,"PRIM_PPNL","MenuBar",{Wa:{CollapsedMenuImage:{f:r.Ztc,i:r.W3b},ShowOnHover:{f:r.t6a,i:function(a){this.DYc(e.Ha(a))}},CollapseStyle:{f:function(){return e.Ja(this.XIa(),a.vK.G)},i:function(b){this.SVc(e.Ba(b,a.vK.G))}}}});c.DWb=function(a){g.w.call(this,500);this.IR=a};var g=c.u(c.DWb,c.YT);g.zO=function(){if(this.IR.t6a()){var a=
!1,c=!1,d=b.Q().jgb(b.Hl());d?a=!0:(d=b.UT(b.Hl()))&&(d==this.IR||d.Jr(this.IR))&&(a=!0);!a&&(d=b.Q().lB(b.KP()))&&(c=a=!0);a||(this.IR.Qq(),c=!0);c&&this.zj()}return!1};c.YMa=function(){l.w.call(this);this.Rc=new c.ja(0,0,150,150);this.Sp=new c.yz;this.i7=a.Xeb.hya;b.rq(this.Sp);b.zp(this.Sp);this.ol(this.Sp)};var l=c.u(c.YMa,c.Sw);l.zb=function(){l.j.zb.call(this)};l.U=function(){l.j.U.call(this)};l.aAa=function(b){this.Nua()!=b&&(this.i7=this.i7&~a.Xeb.j_b|b,this.kb(),this.fa(a.a.g))};l.Nua=function(){return this.i7&
a.Xeb.j_b};l.ae=function(b){""==b[0]&&(b[0]=a.VPb);""==b[1]&&(b[1]=a.BHc);l.j.ae.call(this,b)};l.Ggb=function(){this.ol(this.Sp);this.sZ(!0)};l.Rv=function(c,d){l.j.Rv.call(this,c,d);this.Ggb();b.EWb(this,this.Sp,a.xa.nj,a.Ea.nC,a.ka.si,this.H1a)};l.tOa=function(){if(this.Nua()!=a.sI.Y3){for(var b=null,d=this.ul,e=[!0,2,2,0,0],f=0;f<d.length&&null!=(b=d[f]);f++){var g=b instanceof c.Xaa?b:null;switch(this.Nua()){case a.sI.xla:g?g.c1b(e):e[2]+=b.sb()?b.Ua():0;break;case a.sI.g_b:e[1]=Math.max(e[1],
b.fb()),e[2]+=b.sb()?b.Ua():0}}for(f=0;f<d.length&&null!=(b=d[f]);f++)switch(this.Nua()){case a.sI.xla:(g=b instanceof c.Xaa?b:null)&&g.hc(e[1])}this.hc(e[1]);this.Jc(e[2])}};l.lma=function(a){this.tOa();return l.j.lma.call(this,a)};l.pe=function(a){l.j.pe.call(this,a)};l.PAb=l[a.R.hab]=function(a){l.j.PAb.call(this,a);this.tOa()};l.H1a=function(a){(a=a instanceof c.Xaa?a:null)&&a.Bq()};e.yb(c.YMa,"PRIM_PPNL","Menu",{Wa:{MenuSizing:{f:function(){return e.Ja(this.Nua(),a.sI.G)},i:function(b){this.aAa(e.Ba(b,
a.sI.G))}}}});c.FWb=function(){s.w.call(this)};var s=c.u(c.FWb,c.oI);s.hOb=function(){return!0};s.ae=function(){};c.Xaa=function(){f.w.call(this);this.Rc=new c.ja(0,0,100,25);this.c7=a.eba.cfb;this.kr=0;this.xWa=this.mtb=this.vm=this.WM=this.F0=this.xR=this.gK=null;this.G0=new c.yz;this.nu=0;this.cH=a.ie.YY;b.rq(this.G0);b.zp(this.G0);this.ol(this.G0);this.JPa(!0);this.WM=new c.tb;this.WM.Ap(a.m.Jd);this.WM.yj(a.m.Jd);this.WM.$m(1);this.WM.Jn(1);this.WM.lm(1);this.WM.Kl(1);this.F0=new c.Ns;this.F0.Ia(this);
this.F0.mb(new c.ja(0,0,18,18));this.F0.Cb(this.WM);this.vm=new c.FWb;this.vm.Ia(this);this.vm.Ne(2);this.vm.Ie(2);this.mtb=b.$c(this.G0,this.vm,this.G0.hd(0),this.G0.od(0),1,1);this.xWa=b.$c(this.G0,this.F0,this.G0.hd(0),this.G0.od(0),1,1)};var f=c.u(c.Xaa,c.hm);f.zb=function(){f.j.zb.call(this)};f.U=function(){f.j.U.call(this);this.WPa(null)};f.NA=function(){return this.vm.NA()};f.HZ=function(b){this.NA()!=b&&(this.vm.NA()&&this.vm.NA().Bz(this,a.K.mB,this.wBb),this.vm.HZ(b),this.vm.NA()&&this.vm.NA().Fa(this,
a.K.mB,this.wBb),this.l(a.a.g))};f.M2=function(){return this.vm.M2()};f.Kwc=function(){return this.xR};f.WPa=function(b){this.xR!=b&&(null!=this.xR&&(this.xR.va(this,this.vBb),this.xR.Ab()),this.xR=b,null!=this.xR&&(this.xR.ua(),this.xR.ya(this,this.vBb)),this.nv(),this.l(a.a.g))};f.Av=function(){return this.nu};f.Wt=function(b){b!=this.nu&&(this.nu=b,this.nv(),this.fa(a.a.g))};f.zq=function(b){this.cH!=b&&(this.cH=b,this.nv(),this.fa(a.a.g))};f.hf=function(){return this.vm.hf()};f.bf=function(b){this.hf()!=
b&&(this.vm.bf(b),this.l(a.a.g))};f.mf=function(){return this.vm.mf()};f.Ne=function(b){this.mf()!=b&&(this.vm.Ne(b),this.l(a.a.g))};f.pg=function(){return this.vm.pg()};f.Ie=function(b){this.pg()!=b&&(this.vm.Ie(b),this.l(a.a.g))};f.Bg=function(){return this.vm.Bg()};f.If=function(b){this.Bg()!=b&&(this.vm.If(b),this.l(a.a.g))};f.Cl=function(){return this.cH};f.cva=function(){return 0!=(this.c7&a.eba.dfb)?!0:!1};f.Zjb=function(b){b=this.c7&~a.eba.dfb|(b?a.eba.dfb:0);this.c7!=b&&(this.c7=b,this.nv(),
this.fa(a.a.g))};f.uf=function(){return 0!=(this.c7&a.eba.afb)?!0:!1};f.Vg=function(b){var d=this.UC();if(b&&0!=d&&null!=this.Z())for(var e=null,f=this.Z().Ck,g=0;g<f.length&&null!=(e=f[g]);g++)if(e instanceof c.Xaa){var h=e;h!=this&&h.UC()==d&&h.Vg(!1)}b=this.c7&~a.eba.afb|(b?a.eba.afb:0);this.c7!=b&&(this.c7=b,this.nv(),this.fa(a.a.g))};f.UC=function(){return this.kr};f.xZ=function(b){this.kr!=b&&(this.kr=b,this.nv(),this.fa(a.a.g))};f.C6a=function(){return this.gK};f.EQa=function(a){this.gK!=a&&
(this.gK=a)};f.ae=function(b){""==b[0]&&(b[0]=a.SPb);f.j.ae.call(this,b)};f.Bq=function(){var a=b.Q().lB(this);(null==a||a.Di())&&this.NA()&&!this.NA().Di()&&this.vm.z8b(!0)};f.cwa=function(){};f.c1b=function(b){var d=null,e=this.$b&&this.$b instanceof c.ydb?this.$b:null,f=this.nu;this.uf()?(d=this.cva()?a.Xb.c_b:a.Xb.b_b,this.WM.Ap(a.m.OU),this.WM.yj(a.m.r5)):(this.WM.Ap(a.m.Jd),this.WM.yj(a.m.Jd));this.xR&&(d=this.xR);d&&0==f&&(f=Math.min(this.Ua(),d.Ua()));this.vm.uc(a.ZHc);this.vm.VL(!1);this.vm.zq(this.Cl());
this.vm.eQa(e?a.BD.dya:a.BD.eya);this.vm.Ejb(e?a.Ym.Y3:a.Ym.yla);this.vm.bG(a.Ts.rK);this.vm.ana(!1);this.vm.bc(this.Kb());this.vm.Mn(a.xh.Gq);this.F0.Yi(d);this.F0.mb(new c.ja(this.F0.se(),this.F0.He(),f,f));this.mtb.jc(a.ka.Kf);this.mtb.Ne(e?0:f+2);this.xWa.jc(a.ka.$d);this.xWa.Qb(a.Ea.Zk);this.xWa.Ne(e?0:2);this.vm.Tk(!1,!0);var g=this.vm.q2(),h=this.vm.cua();e?(g+=f+4,d&&(g+=f+4)):(g+=60,h+=10);!0==b[0]&&(this.Jc(h),b[1]=Math.max(b[1],g),b[2]+=this.sb()?h:0,b[3]+=g,b[4]+=h)};f.Rv=function(a,b){f.j.Rv.call(this,
a,b);this.c1b([!1,0,0])};f.Gh=function(a){var d=!1;this.UC()&&this.Vg(!0);d=f.j.Gh.call(this,a);if(!d){a=b.Q().gA;for(var e=null,g=0;g<a.length&&null!=(e=a[g]);g++)e instanceof c.YMa&&b.Q().su(e,!1)}return d};f.wBb=function(a,b){b.kYc(this)};f.vBb=function(b,c){switch(c.Ya){case a.a.ub:case a.a.Vb:this.WPa(null);break;case a.a.g:this.nv()}};e.yb(c.Xaa,"PRIM_PPNL","MenuItem",{Wa:{Checked:{f:f.uf,i:function(a){this.Vg(e.Ha(a))}},MenuPopup:{f:f.NA,i:f.HZ},RadioItem:{f:f.cva,i:function(a){this.Zjb(e.Ha(a))}},
GroupIndex:{f:f.UC,i:function(a){this.xZ(e.aa(a))}},Image:{f:f.Kwc,i:f.WPa},ImageHeight:{f:f.Av,i:function(a){this.Wt(e.aa(a))}},MarginLeft:{f:f.mf,i:function(a){this.Ne(e.aa(a))}},MarginTop:{f:f.hf,i:function(a){this.bf(e.aa(a))}},MarginBottom:{f:f.Bg,i:function(a){this.If(e.aa(a))}},MarginRight:{f:f.pg,i:function(a){this.Ie(e.aa(a))}},Alignment:{f:function(){return e.Ja(this.Cl(),a.ie.sK)},i:function(b){this.zq(e.Ba(b,a.ie.sK))}}},Gc:{ShowMenu:f.Bq,HideMenu:f.cwa}});c.BWb=function(a,b,c){d.w.call(this);
this.IR=a;this.Xa=b;this.iad=b.Xc();-1==c&&(c=this.IR.QQ.length);this.IR.QQ.splice(c,0,this);this.Xa.ya(this,this.$n);this.Xa.Ia(a.P_)};var d=c.u(c.BWb,c.pd);d.U=function(){var a=this.IR.ul.length+1;this.Xa.va(this,this.$n);this.IR.QQ.splice(this.IR.QQ.indexOf(this),1);this.Xa.Wc(this.IR);this.Xa.tf(a);this.Xa.mb(this.iad);d.j.U.call(this)};d.Ca=function(){return this.Xa};b.CWb=function(a,b){-1==a.QQ.indexOf(b)&&new c.BWb(a,b,0)};d.$l=function(b,c){switch(c.Ya){case a.a.ub:this.Zn()}};c.YYb=function(a){w.w.call(this,
a);this.GQ=!1;this.jW=null;this.Zu="";this.EEa=null};var w=c.u(c.YYb,c.V3);w.JKb=function(){var b=!1,c=e.Ja(this.la.Ix,a.Fg.LEb);if("md-effect-17"==c||"md-effect-18"==c||"md-effect-19"==c)b=!0;return b};w.Ve=function(a){this.v=document.createElement("div");this.v.setAttribute("id",a+this.fc);this.v.setAttribute("LANSAHandle",this.fc);this.jW=document.createElement("div");this.jW.setAttribute("LANSAHandle",this.fc);return this.v};w.QSa=function(){this.ssa()};w.cpb=function(b){this.Zu=e.Ja(this.la.Ix,
a.Fg.LEb);null!=this.EEa&&(b=this.EEa);9999<b&&(""==this.Zu?w.j.cpb.call(this,b):this.jW.style.zIndex=b)};w.bs=function(a,c,d,e){a=b.Cd(a,c,d,e);this.la.YX()&&a.Ar(this.la.Z().Oxb(a));w.j.bs.call(this,a.O(),a.M(),a.$(),a.ba())};w.lna=function(){var a=this.GQ;this.la.c6b(this.la.ija().gD());if(""==this.Zu)this.GQ=!0,a||document.body.appendChild(this.v);else if(!this.GQ){b.Q().fr.Ma().v.classList.add("container");this.jW.setAttribute("class","md-modal "+this.Zu);a=b.Kd[this.la.rb().Ma().ib()];a.v.style.opacity=
"";a.v.setAttribute("class","md-content");this.jW.appendChild(this.v);document.body.insertBefore(this.jW,b.Q().fr.Ma().v);var c=this;this.JKb()&&setTimeout(function(){document.documentElement.classList.add("md-perspective")},25);setTimeout(function(){c.jW.classList.add("md-show")},100);this.GQ=!0}};w.ssa=function(){this.GQ&&(this.jW.classList.contains("md-show")?this.Y1b():(this.GQ=!1,this.JKb()&&document.documentElement.classList.remove("md-perspective"),""==this.Zu?document.body.removeChild(this.v):
(document.body.removeChild(this.jW),b.Q().fr.Ma().v.classList.remove("container"))),this.la.GCc())};w.Y1b=function(){var a=this;this.jW.classList.remove("md-show");setTimeout(function(){a.la.qn()},500)};w.CBd=function(){this.Y1b()}},{rp:["PRIM_PHBN","PRIM_IMAG","PRIM_TBLO"]});
