window.LANSA.addSrc("imag",function(e,c,a,b){c.Ns=function(){h.w.call(this);this.ir="";this.Yb=this.Za=this.gu=this.CUa=this.ZQ=this.qe=this.Oe=null;this.GV=a.og.Xca;this.Rz=this.hA=this.dA=this.oA=0;this.Lc|=a.Sb.tka;this.PDa=new c.hm;this.PDa.cf(!1);this.PDa.Ia(this);this.qe=new c.LP;this.Oe=new c.tb;this.Oe.sd(this.qe);this.PDa.dna(this.Oe);this.cf(!1)};var h=c.u(c.Ns,c.hm);h.zb=function(){b.ea(this.qe);this.qe=null;b.ea(this.Oe);this.Oe=null;h.j.zb.call(this)};h.U=function(){h.j.U.call(this);
this.Xma(null);this.CUa=null;this.Yi(null);this.Vk(null)};h.hh=function(){return this.ir};h.Ou=function(c){b.hI(this.ir,c)||(this.ir=c,this.Xma(b.hla(this.ir)),this.l(a.a.g))};h.pld=function(){return this.ZQ};h.Xma=function(b){this.ZQ!=b&&(this.Yi(null),null!=this.ZQ&&this.ZQ.va(this,this.WAb),this.ZQ=b,null!=this.ZQ&&this.ZQ.ya(this,this.WAb),this.zQ(),this.kb(),this.l(a.a.g))};h.D4a=function(){return this.gu};h.Yi=function(b){this.gu!=b&&(this.Xma(null),null!=this.gu&&(this.gu.va(this,this.$l),
this.gu.Ab()),this.gu=b,null!=this.gu&&(this.gu.ua(),this.gu.ya(this,this.$l)),this.zQ(),this.kb(),this.Gd(),this.l(a.a.g))};h.G2=function(){return this.qe.Xj()};h.DZ=function(b){this.qe.Xj()!=b&&(this.qe.gg(b),this.l(a.a.g))};h.wX=function(){return this.qe.se()};h.CZ=function(b){this.qe.se()!=b&&(this.qe.Qa(b),this.l(a.a.g))};h.yX=function(){return this.qe.He()};h.EZ=function(b){this.qe.He()!=b&&(this.qe.Ta(b),this.l(a.a.g))};h.hT=function(){return this.qe.fb()};h.hM=function(b){this.qe.fb()!=b&&
(this.qe.hc(b),this.l(a.a.g))};h.Av=function(){return this.qe.Ua()};h.Wt=function(b){this.qe.Ua()!=b&&(this.qe.Jc(b),this.l(a.a.g))};h.RK=function(){return this.GV};h.OI=function(b){this.GV!=b&&(this.GV=b,this.qe.jc(b),this.kb(),this.Gd(),this.l(a.a.g))};h.xX=function(){return this.qe.sT()};h.eQ=function(b){this.qe.sT()!=b&&(this.qe.i5(b),this.l(a.a.g))};h.zX=function(){return this.qe.rj()};h.FZ=function(b){this.qe.rj()!=b&&(this.qe.Nl(b),this.l(a.a.g))};h.wF=function(){return this.qe.Tg()};h.SD=
function(b){this.qe.Tg()!=b&&(this.qe.Qb(b),this.l(a.a.g))};h.Hf=function(b){this.Za!=b&&(this.Vk(b),this.l(a.a.g))};h.vb=function(){var a=null;return a=this.Za};h.ic=function(){return this.Yb};h.hf=function(){return this.oA};h.bf=function(c){this.oA!=c&&(this.oA=c,this.kb(),this.Gd(),b.Ra().oc(this,!1),this.fa(a.a.g))};h.mf=function(){return this.dA};h.Ne=function(c){this.dA!=c&&(this.dA=c,this.kb(),this.Gd(),b.Ra().oc(this,!1),this.fa(a.a.g))};h.pg=function(){return this.hA};h.Ie=function(c){this.hA!=
c&&(this.hA=c,this.kb(),this.Gd(),b.Ra().oc(this,!1),this.fa(a.a.g))};h.Bg=function(){return this.Rz};h.If=function(c){this.Rz!=c&&(this.Rz=c,this.kb(),this.Gd(),b.Ra().oc(this,!1),this.fa(a.a.g))};h.xl=function(a,b,c,e,l){return l};h.qS=function(){var a=this.Yb.sj();""!=a?this.ZQ&&this.ZQ.hh()==a||this.Xma(b.hla(a)):this.Xma(this.Yb.Cja());this.Za.HS(this.ic())};h.Vk=function(a){var c=null;a&&(c=a.xt(),this.Za==a?c.Rm(this.Yb):a.ov(c));this.Za&&(this.Za.va(this),this.Yb.va(this),b.ea(this.Yb),this.Yb=
null);if(this.Za=a)this.Za.ya(this,this.Ij),this.Yb=c,this.Yb.ya(this,this.qv);this.Mg()};h.zQ=function(){null==this.gu?this.qe.bd(this.ZQ):this.CUa&&0<this.CUa.hh().length?this.qe.bd(this.CUa):this.qe.bd(this.gu)};h.pe=function(b){var e=new c.ja(0,0,b.$(),b.ba());h.j.pe.call(this,b);e.Ta(e.M()+this.oA);e.Qa(e.O()+this.dA);e.Oa(e.na-this.hA);e.Aa(e.pa-this.Rz);this.PDa.Wc(this);this.PDa.mb(e);this.RK()==a.og.Xca&&this.qe.Ic()&&(this.qe.Ic().Ua()>e.ba()||this.qe.Ic().fb()>e.$()?this.qe.jc(a.og.nQ):
this.qe.jc(a.og.$d))};h.zI=function(b){var e=this.Wm(),h=this.nq();if(0!=this.yX()||0!=this.wX()||100!=this.hT()||100!=this.Av()||this.xX()!=a.rs.kda||this.zX()!=a.Nx.jea||this.qe.Ug()==a.og.dRa)h=e=!1;if(e||h){var g=new c.ja;if(this.qe.Ic())switch(g.Oa(this.qe.Ic().fb()),g.Aa(this.qe.Ic().Ua()),this.qe.Ug()){case a.og.nQ:if(h&&!e&&0<b.$()&&0<g.$()){var l=b.$()/g.$();g.Aa(g.M()+g.ba()*l)}}e&&b.Oa(b.O()+this.ga.pk()+this.dA+g.$()+this.hA+this.ga.Al());h&&b.Aa(b.M()+this.ga.dl()+this.oA+g.ba()+this.Rz+
this.ga.Am())}};h.Gh=function(a){b.Xcb();return h.j.Gh.call(this,a)};h.$l=function(b,c){switch(c.Ya){case a.a.ub:case a.a.Vb:this.Yi(null);break;case a.a.g:this.kb(),this.Gd()}};h.WAb=function(b,c){switch(c.Ya){case a.a.ub:case a.a.Vb:this.Xma(null);break;case a.a.g:this.kb()}};h.Ij=function(b,c){c.Ya==a.a.g?c.gp==a.he.Ot?this.Za.ov(this.ic()):this.Vk(this.Za):c.Ya==a.a.ub&&this.Hf(null)};h.qv=function(b,c){c.Ya==a.a.g&&c.gp==a.he.Ot&&this.qS()};e.gd(c.Ns,"PRIM_IMAG",{Wa:{FileName:{f:h.hh,i:function(a){this.Ou(e.ma(a))}},
Image:{f:h.D4a,i:function(a){this.Yi(a)}},ImageTile:{f:function(){return e.Ja(this.xX(),a.rs.G)},i:function(b){this.eQ(e.Ba(b,a.rs.G))}},ImageUnits:{f:function(){return e.Ja(this.zX(),a.Nx.G)},i:function(b){this.FZ(e.Ba(b,a.Nx.G))}},ImageSizing:{f:function(){return e.Ja(this.RK(),a.og.G)},i:function(b){this.OI(e.Ba(b,a.og.G))}},ImageOpacity:{f:h.G2,i:function(a){this.DZ(e.aa(a))}},ImageLeft:{f:h.wX,i:function(a){this.CZ(e.aa(a))}},ImageTop:{f:h.yX,i:function(a){this.EZ(e.aa(a))}},ImageWidth:{f:h.hT,
i:function(a){this.hM(e.aa(a))}},ImageHeight:{f:h.Av,i:function(a){this.Wt(e.aa(a))}},ImageAlignment:{f:function(){return e.Ja(this.wF(),a.ie.G)},i:function(b){this.SD(e.Ba(b,a.ie.G))}},DataClass:{f:h.vb,i:h.Hf},MarginLeft:{f:h.mf,i:function(a){this.Ne(e.aa(a))}},MarginTop:{f:h.hf,i:function(a){this.bf(e.aa(a))}},MarginBottom:{f:h.Bg,i:function(a){this.If(e.aa(a))}},MarginRight:{f:h.pg,i:function(a){this.Ie(e.aa(a))}}}})});
