window.LANSA.addSrc("gpbx",function(e,c,a,b){a.Bqc={ZKd:0,YKd:9,H$c:6,$Kd:5,aLd:10};a.ZAc={Bsc:0};c.vVb=function(){h.w.call(this);this.tsb=a.Bqc.H$c;this.OG=a.ZAc.Bsc;this.dH=new c.ja;this.Lc=this.Lc|a.Sb.Aaa|a.Sb.Kwa|a.Sb.cab|a.Sb.sD|a.Sb.CP|a.Sb.gB;this.yh=this.yh|a.ji.BP|a.ji.uY;this.cf(!1)};var h=c.u(c.vVb,c.JP);h.Cg=function(){return c.OYb};h.FFd=function(b){this.tsb!=b&&(this.tsb=b,this.l(a.a.g),this.Cu())};h.gnd=function(){return this.tsb};h.Vo=function(a){h.j.Vo.call(this,a);this.YLc()};h.Yob=
function(){if(this.Ob()){var a=this.Pd(),a=Math.abs(a.Ua()),c=this.ye();this.qd();this.qd();c.Qa(c.O()+a);""==this.Kb()?(c.Oa(c.O()),c.Aa(a)):(this.Kb(),c.Oa(c.O()+this.q2()),c.Aa(this.cua()),c.Oa(c.na+a));b.Po(this.dH,c)||(this.dH=c,this.kb());this.Vo(!0)}};h.pe=function(a){a.Ta(a.M()+this.dH.ba());a.Qa(a.O()+4);a.Oa(a.na-4);a.Aa(a.pa-4);h.j.pe.call(this,a)};h.OOc=function(a,b,c){a.Ta(a.M()+this.dH.ba());a.Qa(a.O()+4);a.Oa(a.na-4);a.Aa(a.pa-4);h.j.OOc.call(this,a,b,c)};h.Ki=function(){h.j.Ki.call(this);
this.yd(a.R.Mv)};h.ad=function(){var b=this.mL()||this.vk()&&(this.qY()||this.AP());this.gH(a.Sb.sL,b);h.j.ad.call(this)};h.FD=function(a){var b=!1,b=a.De().DOa(this,this.ga.di,this.qY(),this.AP(),a);!1==b&&h.j.FD.call(this,a)};h.gU=function(a){var b=!1;null!=a.De()&&a.Ca().vk()&&(b=a.De().EOa(this,this.ga.di,a,this.qY(),this.AP()));!1==b&&h.j.gU.call(this,a)};h.ae=function(b){""==b[1]&&(b[1]=a.qPb);h.j.ae.call(this,b)};h.YLc=function(){var a=this.ye(),a=this.zA(a,null),c=this.ye();c.Ta(c.M()+this.dH.ba()/
2+1);c.Qa(c.O()+2);c.Oa(c.na-2);c.Aa(c.pa-2);var e=this.Ma().ib(),l=this.Kb();b.Kd[e].hg(l,c,this.dH);b.ea(a)};h.lp=h[a.R.vD]=function(a){this.Yob();h.j.lp.call(this,a)};h.Cr=h[a.R.uD]=function(){h.j.Cr.call(this);this.Yob()};h.FC=h[a.R.Mv]=function(){this.Yob();this.Cu()};h.toc=h[a.R.Gab]=function(){this.Mg()};e.gd(c.vVb,"PRIM_GPBX",{Wa:{Caption:{f:h.Kb,i:function(a){this.bc(e.ma(a))}},ThemeStyle:{f:function(){return e.Ja(this.eL(),a.eu.G)},i:function(b){this.uAa(e.Ba(b,a.eu.G))}}}});c.OYb=function(a){t.w.call(this,
a);this.pb=this.ZTa=this.ACa=this.Xd=this.Mc=null};var t=c.u(c.OYb,c.V3);t.Ve=function(a,b){var c=null;t.j.Ve.call(this,a,b);this.ZTa=4;this.Mc=document.createElement("div");this.Xd=document.createElement("div");this.ACa=document.createElement("div");this.pb=document.createElement("span");this.v.appendChild(this.Mc);this.v.appendChild(this.Xd);this.v.appendChild(this.ACa);this.v.appendChild(this.pb);this.W8a(this.Mc,this.ZTa);this.W8a(this.Xd,0);this.W8a(this.ACa,0);c=this.Mc.style;c.borderTopWidth=
"0px";c=this.Xd.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.ACa.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.pb.style;c.position="absolute";c.whiteSpace="nowrap";c.cursor="inherit";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";return this.v};t.W8a=function(a,b){var c=a.style;c.position="absolute";c.overflowX="hidden";c.overflowY=
"hidden";c.whiteSpace="nowrap";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.outline="none";c.background="rgba(0,0,0,0)";c.borderTopWidth="1px";c.borderBottomWidth="1px";c.borderLeftWidth="1px";c.borderRightWidth="1px";c.borderTopLeftRadius=b+"px";c.webkitBorderTopLeftRadius=b+"px";c.borderTopRightRadius=b+"px";c.webkitBorderTopRightRadius=b+"px";c.borderBottomLeftRadius=b+"px";c.webkitBorderBottomLeftRadius=b+"px";c.borderBottomRightRadius=
b+"px";c.webkitBorderBottomRightRadius=b+"px"};t.hg=function(a,b,c){var e=this.Mc.style;e.left=b.O()+"px";e.top=b.M()+"px";e.width=b.$()+"px";e.height=b.ba()+"px";e.borderColor=this.Ok();e=this.Xd.style;e.left=b.O()+this.ZTa-1+"px";e.top=b.M()+"px";e.width=c.O()-b.O()+"px";e.height="1px";e.borderColor=this.Ok();e=this.ACa.style;e.left=c.na+2+"px";e.top=b.M()+"px";e.width=b.na-this.ZTa-c.na+"px";e.height="1px";e.borderColor=this.Ok();e=this.pb.style;e.left=c.O()+7+"px";e.top=c.M()+2+"px";e.height=
c.ba()+"px";e.width=c.$()+"px";this.pb.textContent=a}});
