window.LANSA.addSrc("fld",function(e,c,a,b,h){function t(b,c){var e=a.Ga.Lk;null!=b&&(b.mthLOAD!=h&&b.mthLOAD(c),e=a.Ga.Fb);return e}a.WY={o_b:0,n_b:1,p_b:2};a.WY.G={DEFAULTITEM:a.WY.o_b,BLANKS:a.WY.n_b,SHOWVALUE:a.WY.p_b};a.egb={Tgb:0,E1b:15};a.Gya={ggb:1,Xzd:15,j0b:16,Wzd:240};c.Oka=function(a){p.w.call(this);this.gw=new c.tMa(a);new c.MRb(this)};var p=c.u(c.Oka,c.zL);p.ez=function(){return this.gw};p.th=function(){return this.gw.th()};p.qk=function(){return this.gw.qk()};p.iz=function(){var b=
this.th(),c=this.qk();switch(this.PK()){case a.Zd.V9:case a.Zd.W9:return b-c;case a.Zd.l2:switch(b){case 1:return a.NIc;case 2:return a.KIc;case 4:return a.LIc;case 8:return a.MIc}break;case a.Zd.CIa:switch(b){case 4:return 6;case 8:return 15}}return 0};p.PK=function(){return this.gw.PK()};p.uua=function(){return this.gw.uua()};p.zs=function(){return this.gw.zs()};p.sX=function(){return this.gw.sX()};p.tX=function(){return this.gw.tX()};p.uX=function(){return this.gw.uX()};p.aT=function(){return this.gw.aT()};
p.FA=function(){return this.gw.FA()};p.m$=function(){return this.gw.m$()};p.$4a=function(){return this.gw.$4a()};p.lyc=function(){switch(this.PK()){case a.Zd.l2:case a.Zd.V9:case a.Zd.W9:return 0;case a.Zd.Nta:case a.Zd.Qta:case a.Zd.Tta:case a.Zd.Rta:case a.Zd.Mta:return"";case a.Zd.Ota:case a.Zd.Sta:case a.Zd.Pta:return b.uj();case a.Zd.qia:return!1}};p.Ka=function(){if(this.eo().Qk())return e.Qe;switch(this.PK()){case a.Zd.qia:return 0!==this.eo().Ka()}return this.eo().Ka()};p.Va=function(c){if(c==
e.Qe)this.eo().pK();else{switch(this.PK()){case a.Zd.l2:c=e.aa(c);break;case a.Zd.V9:case a.Zd.W9:0==this.qk()&&(c=e.aa(c));break;case a.Zd.Nta:case a.Zd.Qta:case a.Zd.Tta:case a.Zd.Rta:case a.Zd.Mta:c=e.ma(c);break;case a.Zd.Ota:"string"===typeof c&&(c=b.T_a(c));break;case a.Zd.Sta:"string"===typeof c&&(c=b.j0a(c));break;case a.Zd.Pta:"string"===typeof c&&(c=b.V_a(c));break;case a.Zd.qia:c=e.Ha(c),this.eo().Va(c?1:0)}this.eo().Va(c)}};p.kha=function(){return this};p.dZa=function(){this.Va(this.FA())};
p.Cha=function(){return new c.Oka(this.gw.fs)};e.gd(c.Oka,"PRIM_FLD",{rB:a.Br.FS,Wa:{Text:{f:function(){return this.Gia()}},Length:{f:p.th},Decimals:{f:p.qk},Value:{f:p.Ka,i:p.Va}},qg:{vg:"Value"}});var r=p;r.aD=r.applyDefault=r.dZa;c.MRb=function(b){g.w.call(this,b);this.Pp=a.Zm.ANa;b=b.ez();switch(b.Pwc()){case a.Mw.oOb:this.Pp|=a.uK.p0a;break;case a.Mw.nOb:this.Pp|=a.uK.o0a;break;case a.Mw.rOb:this.Pp|=a.uK.t0a;break;case a.Mw.qOb:this.Pp|=a.uK.pkc;break;case a.Mw.pOb:this.Pp|=a.Zm.OKc}this.Pp=
b.lEc()?this.Pp|a.tt.gfb:this.Pp|a.tt.Epb;b.rMb()&&(this.Pp|=a.Zm.fya);b.sLa()&&(this.Pp|=a.Zm.h_b);b.M$a()&&(this.Pp|=a.Zm.i_b);b.HEc()&&(this.Pp|=a.Zm.wla)};var g=c.u(c.MRb,c.HP);g.th=function(){return this.vb().th()};g.qk=function(){return this.vb().qk()};g.iz=function(){return this.vb().iz()};g.PK=function(){return this.vb().PK()};g.zs=function(){return this.vb().zs()};g.sX=function(){return this.vb().sX()};g.tX=function(){return this.vb().tX()};g.uX=function(){return this.vb().uX()};g.aT=function(){return this.vb().aT()};
g.FA=function(){return this.vb().FA()};g.m$=function(){return this.vb().m$()};g.Vm=function(){switch(this.PK()){case a.Zd.l2:return 8==this.th()?a.bb.vG:a.bb.DB;case a.Zd.V9:case a.Zd.W9:if(0==this.qk()&&this.th()<=a.OIc)return a.bb.Kz;if(this.th()<=a.JIc&&this.qk()<=a.IIc)return a.bb.uG;break;case a.Zd.CIa:return a.bb.rJ;case a.Zd.l4a:return a.bb.oCa;case a.Zd.m4a:return a.bb.pCa}return g.j.Vm.call(this)};g.aMb=function(){var a=this.vb().$4a();a&&(a=new a,a.CT(),this.Za.mWc(a))};g.VIa=function(){switch(this.vb().PK()){case a.Zd.l2:case a.Zd.V9:case a.Zd.W9:if(0<
this.m$().length)return a.Nd.Y0a;switch(this.vb().uua()){case a.Bi.c3a:case a.Bi.d3a:return a.Nd.X0a}return a.Nd.NGa;case a.Zd.Nta:case a.Zd.Tta:return a.Nd.QGa;case a.Zd.Qta:case a.Zd.Rta:return a.Nd.PGa;case a.Zd.Mta:return a.Nd.D8;case a.Zd.qia:return a.Nd.MGa;case a.Zd.Pta:return a.Nd.ES;case a.Zd.Ota:return a.Nd.iF;case a.Zd.Sta:return a.Nd.jF}};g.K2b=function(c,e){var f="";switch(c){case a.Kk.Dsa:f=this.vb().zs();break;case a.Kk.U1:f=this.vb().aT();break;case a.Kk.Csa:var g=this.sX(),k=this.tX(),
h=this.uX(),l=b.xz(g),p=b.xz(k),s=b.xz(h);switch(e){case a.iaa.m8a:f=g+"\n"+k+"\n"+h;break;case a.iaa.DLb:""==l&&(""==p?""==!s&&(g=h,h=""):(g=k,k=h,h=""));f=g;if(0<k.length||0<h.length)f=f+"\n"+k,0<h.length&&(f=f+"\n"+h);break;case a.iaa.FLb:f="",0<g.length&&(f=g),0<k.length&&(f=f+(0<f.length?" ":"")+k),0<h.length&&(f=f+(0<f.length?" ":"")+h)}}return f};g.R_a=function(c){var f=null;this.vb().p$()||null!=this.vb().Qv()&&(f=b.Wbb(c));if(null==f)switch(this.Bl()){case a.Nd.D8:case a.Nd.QGa:f=b.NSb(c);
break;case a.Nd.OGa:case a.Nd.PGa:f=b.YSb(c);break;case a.Nd.Ryb:throw 0;case a.Nd.iF:case a.Nd.jF:case a.Nd.ES:b.qMa==h&&e.Bb("PRIM_DTIM");f=a.ac.Z2a;f=b.qMa(c,this.Vm(),f,void 0,void 0);break;case a.Nd.Y0a:b.ORb==h&&e.Bb("PRIM_FMTN");f=b.ORb(c,this);break;case a.Nd.Pyb:case a.Nd.NGa:f=this.vb().PK()!=a.Zd.l2?!0:!1;switch(this.vb().uua()){case a.Bi.pEb:f=f?b.Fu(c,a.Hc.iya):b.Qw(c,a.Hc.iya);break;case a.Bi.qEb:f=f?b.Fu(c,a.Hc.jya):b.Qw(c,a.Hc.jya);break;case a.Bi.rEb:f=f?b.Fu(c,a.Hc.Dla):b.Qw(c,a.Hc.Dla);
break;case a.Bi.sEb:f=f?b.Fu(c,a.Hc.kya):b.Qw(c,a.Hc.kya);break;case a.Bi.tEb:f=f?b.Fu(c,a.Hc.lya):b.Qw(c,a.Hc.lya);break;case a.Bi.uEb:f=f?b.Fu(c,a.Hc.mya):b.Qw(c,a.Hc.mya);break;case a.Bi.vEb:f=f?b.Fu(c,a.Hc.nya):b.Qw(c,a.Hc.nya);break;case a.Bi.wEb:f=f?b.Fu(c,a.Hc.oya):b.Qw(c,a.Hc.oya);break;case a.Bi.xEb:f=f?b.Fu(c,a.Hc.pya):b.Qw(c,a.Hc.pya);break;case a.Bi.BEb:f=f?b.Fu(c,a.Hc.tya):b.Qw(c,a.Hc.tya);break;case a.Bi.yEb:f=f?b.Fu(c,a.Hc.qya):b.Qw(c,a.Hc.qya);break;case a.Bi.EEb:f=f?b.Fu(c,a.Hc.uya):
b.Qw(c,a.Hc.uya);break;case a.Bi.zEb:f=f?b.Fu(c,a.Hc.rya):b.Qw(c,a.Hc.rya);break;case a.Bi.FEb:f=f?b.Fu(c,a.Hc.vya):b.Qw(c,a.Hc.vya);break;case a.Bi.AEb:f=f?b.Fu(c,a.Hc.sya):b.Qw(c,a.Hc.sya);break;case a.Bi.IEb:f=f?b.Fu(c,a.Hc.wya):b.Qw(c,a.Hc.wya);break;case a.Bi.KEb:for(var g="",l=0;l<this.iz();l++)g+="#";f=f?b.tJc(c,g):b.sJc(c,g);break;case a.Bi.hIa:case a.Bi.DEb:if(!f){f=b.Qw(c,a.Hc.Rha);break}f=f?b.Fu(c,a.Hc.Ela):b.Qw(c,a.Hc.Ela);break;default:f=f?b.Fu(c,a.Hc.Ela):b.Qw(c,a.Hc.Ela)}break;case a.Nd.X0a:switch(this.vb().uua()){case a.Bi.c3a:f=
b.rMa(c,a.GS.g1a);break;case a.Bi.d3a:f=b.rMa(c,a.GS.h1a);break;default:f=b.rMa(c,a.GS.lzb)}break;case a.Nd.MGa:f=b.rJc(c)}return f};g.S_a=function(){var c=this.Vm();return c==a.bb.Kz?(b.VRb==h&&e.Bb("PRIM_FMTN"),b.VRb(this.Za)):c==a.bb.DB?(b.RRb==h&&e.Bb("PRIM_FMTN"),b.RRb(this.Za)):c==a.bb.vG?(b.TRb==h&&e.Bb("PRIM_FMTN"),b.TRb(this.Za)):g.j.S_a.call(this)};g.Ffb=function(c){var e=c[1],e=b.wJc(c[0]);c[1]=e;c[2]=0;return a.Ga.Fb};c.XRb=function(b){l.w.call(this);this.cub=a.egb.Tgb;this.Ecc=b;this.Pfa=
null;this.zo=[]};var l=c.u(c.XRb,c.pd);l.zb=function(){this.Pfa&&this.Pfa.Ab()};l.U=function(){this.Nxb();l.j.U.call(this)};l.bqd=function(){return this.zo};l.SXc=function(b){this.QJa()!=b&&(this.cub=this.cub&~a.egb.E1b|b,this.l(a.a.g))};l.QJa=function(){return this.cub&a.egb.E1b};l.m3=function(){this.Ecc&&(this.Pfa=e.re(this.Ecc),this.Pfa.ua(),t(this.Pfa,this))};l.jMb=function(a,b){a.$b=this;a.ya(this,this.Znc);b&&a.WXc();this.h$b(a);this.zo.push(a)};l.BPc=function(a){a.$b=null;a.va(this);this.zo.splice(this.zo.indexOf(a),
1)};l.uH=function(b,c,e){var f=a.Ga.Lk,g=this.S$a(b);null==g&&(g=this.s1a());if(g){for(g=this.zo.indexOf(g);0<c;c--)if(0>--g)if(e)g=this.zo.length-1;else{f=a.Ga.FK;break}0<=g&&(g=this.zo[g],f=g.oK(b))}return f};l.WH=function(b,c,e){var f=a.Ga.Lk,g=this.S$a(b);null==g&&(g=this.s1a());if(g){for(g=this.zo.indexOf(g);0<c;c--)if(++g>=this.zo.length)if(e)g=0;else{f=a.Ga.FK;break}g<this.zo.length&&(g=this.zo[g],f=g.oK(b))}return f};l.s1a=function(){for(var a=null,b=this.zo,c,e=0;e<b.length&&null!=(c=b[e]);e++)if(c.v2()){a=
c;break}null==a&&0<this.zo.length&&(a=this.zo[0]);return a};l.un=function(){return this.zo.length()};l.wp=function(a){return this.zo[a]};l.S$a=function(b){var e=new c.ccb;b.D1(e);b=null;for(var f=this.zo,g,h=0;h<f.length&&null!=(g=f[h]);h++)if(g.IJ.zGa(e)==a.dd.Tj){b=g;break}null==b&&this.QJa()==a.WY.o_b&&(b=this.s1a());return b};l.z3=function(a){for(var c=null,e=this.zo,f,g=0;g<e.length&&null!=(f=e[g]);g++)if(b.hI(f.bz(),a)){c=f;break}return c};l.SFc=function(a,c){var e=null,f=null,g=this.zo,h=0;
if(null!=c)for(h=0;h<g.length&&null!=(f=g[h])&&f!=c;h++);for(;h<g.length&&null!=(f=g[h]);h++){var l=f.bz();if(b.hUb(l,a)){e=f;break}}if(null==e&&null!=c)for(h=0;h<g.length&&null!=(f=g[h])&&f!=c;h++)if(l=f.bz(),b.hUb(l,a)){e=f;break}return e};l.h$b=function(a){a.v2()||(a=null);for(var b,c=this.zo,e=0;e<c.length&&null!=(b=c[e]);e++)b.v2()&&b!=a&&(null!=a?b.DPa(!1):a=b)};l.rhb=function(){var b=a.Ga.Fb;this.Pfa&&(b=t(this.Pfa,this));return b};l.rlc=function(){this.Nxb()};l.qlc=function(b,c,f,g){f=f!==
h?f:!1;g=g!==h?g:null;var k=e.re("PRIM_PKIT");k.ua(this);k.Qs(c);k.TZc(b);k.DPa(f);g&&k.bd(g);this.jMb(k,!0);return a.Ga.Fb};l.Nxb=function(){for(var a;null!=(a=this.zo.shift());)a.Ia(null),a.kNb()&&(a.sP()?a.Ab(this,!0):a.Zn());this.zo=[]};l.Znc=function(){this.l(a.a.g,a.he.TIc)};e.gd(c.XRb,"PRIM_PKLT",{Wa:{NoMatchAction:{f:function(){return e.Ja(this.QJa(),a.WY.G)},i:function(b){this.SXc(e.Ba(b,a.WY.G))}},DefaultPicklist:{f:function(){return!0},i:function(){}}},Gc:{Add:l.qlc,RemoveAll:l.rlc}});
c.YRb=function(){s.w.call(this);this.$b=null;this.cb=this.pb="";this.SV=0;this.IJ=new c.ccb;this.IJ.Owb()};var s=c.u(c.YRb,c.pd);s.U=function(){this.bd(null);this.Ia(null);s.j.U.call(this)};s.Ic=function(){return this.ta};s.bd=function(b){this.ta!=b&&(null!=this.ta&&(this.ta.va(this,this.$l),this.ta.Ab()),this.ta=b,null!=this.ta&&(this.ta.ua(),this.ta.ya(this,this.$l)),this.l(a.a.g))};s.Z=function(){return this.$b};s.Ia=function(b){this.$b!=b&&(this.$b&&this.$b.BPc(this),b&&b.jMb(this,!1),this.l(a.a.g))};
s.bz=function(){return this.pb};s.Qs=function(b){this.pb!=b&&(this.pb=b,this.l(a.a.g,a.he.WLa))};s.Ka=function(){return this.IJ.cb};s.Va=function(b){this.IJ.cb!=b&&(this.IJ.mgc(b),this.l(a.a.g))};s.Zld=function(){return this.IJ};s.eKb=function(){return e.ma(this.Ka())};s.TZc=function(b){this.eKb()!=b&&(this.IJ.Xpb(b),this.l(a.a.g))};s.v2=function(){return 0!=(this.SV&a.Gya.ggb)};s.DPa=function(b){this.v2()!=b&&(this.SV=b?this.SV|=a.Gya.ggb:this.SV&=~a.Gya.ggb,this.$b&&this.$b.h$b(this),this.l(a.a.g))};
s.WXc=function(){!0!=this.kNb()&&(this.SV=this.SV|=a.Gya.j0b,this.l(a.a.g))};s.oK=function(a){return a.uS(this.IJ)};s.po=function(a){return a.o$b(this.IJ)};s.kNb=function(){return 0!=(this.SV&a.Gya.j0b)};e.gd(c.YRb,"PRIM_PKIT",{Wa:{Value:{f:s.Ka,i:s.Va},Caption:{f:s.bz,i:function(a){this.Qs(e.ma(a))}},Image:{f:s.Ic,i:s.bd},Default:{f:s.v2,i:function(){}},Parent:{f:s.Z,i:s.Ia}}});c.GSb=function(a){f.w.call(this,a)};var f=c.u(c.GSb,c.Kaa);f.iZ=function(){return a.Ga.Fb};f.rP=function(b){var c=b[0],
e=b[1],f=b[2],g=b[3],h=b[4],l=a.Ga.Tf,p=this.vb().m6,s=null,r,s=p.z3(c);0<e&&(r=c.substr(0,e));if(s=p.SFc(r+f,s))l=a.Ga.Fb,g=1,c=s.bz(),this.ic().eE(s.eKb());b[0]=c;b[1]=e;b[2]=f;b[3]=g;b[4]=h;return l};f.Dya=function(b){var c=a.Ga.Lk,e=this.vb().m6;e&&(c=(b=e.z3(b))?b.po(this.ic()):a.Ga.Tf);return c};f.xw=function(b){var c="",e=a.Ga.Lk,f=this.vb().m6;if(f)if(e=f.S$a(this.ic()))c=e.bz(),0==c.length&&this.ic().w4(c),e=a.Ga.Fb;else switch(f.QJa()){case a.WY.n_b:c="";e=a.Ga.Fb;break;case a.WY.p_b:c=
this.ic().sj();e=a.Ga.Fb;break;default:e=a.Ga.Tf}b[0]=c;return e}});
