window.LANSA.addSrc("wdgt",function(e,c,a,b,h){var t={};c.pZb=function(a){p.w.call(this);this.IDa=a;this.vUa=function(){};this.HV=this.Itb=!1;this.bub=[];this.aub=[];this.Ytb=[];this.Xtb=[];this.Ztb=[]};var p=c.u(c.pZb,c.te);p.xP=function(){return this.Itb};p.Jh=function(){return this.IDa.nm};p.mzc=function(){return this.IDa.js||[]};p.Tzc=function(){return this.IDa.st||[]};p.cvc=function(){return this.IDa.fn};p.Tvc=function(){return this.IDa.fe};p.iX=function(){return this.vUa};p.hPc=function(){function a(){if(p<
u.length){var c=u[p],e=document.createElement("script");e.type="text/javascript";e.onload=function(){e.onload=null;e.onerror=null;p++;a()};e.onerror=function(){e.onload=null;e.onerror=null;throw"Error defining Widget "+d+", failed to load script: "+c;};document.body.appendChild(e);e.src=c}else b()}function b(){function a(){if(!c.Itb){for(c.Itb=!0;0<c.Xtb.length;){var b=c.Xtb.shift();c.o9a(b)}for(;0<c.aub.length;)b=c.aub.shift(),c.q9a(b.mqb,b.ibd,b.value);for(;0<c.Ztb.length;)b=c.Ztb.shift(),c.nMb(b.mqb,
b.parent);for(;0<c.bub.length;)b=c.bub.shift(),c.r9a(b);for(;0<c.Ytb.length;)b=c.Ytb.shift(),c.p9a(b)}}var d=c.cvc(),f=c.vUa.prototype;e&&e(f);var g={Loading:{},Completed:{},Finalize:function(){a()}};d(f,g)!==g.Loading&&a()}var c=this,d=c.Jh(),e=c.Tvc();t[d]=c;for(var f=c.Tzc(),g=0;g<f.length;g++){var h=f[g],l=document.createElement("link");l.type="text/css";l.rel="stylesheet";l.href=h;document.body.appendChild(l)}var p=0,u=c.mzc();a()};p.q9a=function(a,b,c){if(this.xP()){var d=a["set"+b];if(!d)throw e.ZPc("set"+
b);d&&d.call(a,c)}else this.aub.push({mqb:a,ibd:b,value:c})};p.p9a=function(a){this.xP()?a.wIa():this.Ytb.push(a)};p.o9a=function(a){if(this.xP()){var b=a.onCreateInstance;b&&b.call(a)}else this.Xtb.push(a)};p.nMb=function(a,b){if(this.xP()){var c=a.onRealizeControl;if(!c)throw e.YPc();c.call(a,b)}else this.Ztb.push({mqb:a,parent:b})};p.r9a=function(a){if(this.xP()){var b=a.onSizeChanged;b&&b.call(a)}else this.bub.push(a)};c.Pdb=function(){r.w.call(this)};var r=c.u(c.Pdb,c.hm);r.ww=function(){return this.Ma()&&
this.Ma().gCc()?this:null};r[a.R.Nw]=function(b){var c=!1;this.Ma()&&(c=b.Nc!==h?b.Nc:a.W.FI,c=c==a.W.FI||c==a.W.Iu||c==a.W.ky?this.Ma().pGb(null):this.Ma().qGb(null));c||r.j.SW.call(this,b)};r[a.R.Uwa]=function(b){var c=!1;this.Ma()&&(c=(b.Nc!==h?b.Nc:a.W.FI)==a.W.FI?this.Ma().pGb(document.activeElement):this.Ma().qGb(document.activeElement));c||r.j.a2a.call(this,b)};c.lYb=function(){g.w.call(this)};var g=c.u(c.lYb,c.pd);e.gd(c.lYb,"PRIM_WDGT",{});c.nYb=function(){l.w.call(this);var a=this.$Ia(),
a=this.kS=t[a],b=this.RG=new (a.iX());b.LANSA_Component=this;b.LANSA_Class=a;a.o9a(b)};var l=c.u(c.nYb,c.pd);l.n9a=function(a,b){if(this.kS.xP()){var c=this.RG[a];if(!c)throw e.f2b(a);return c.apply(this.RG,b)}throw e.SOa();};l.bva=function(a){if(this.kS.xP()){var b=this.RG["get"+a];if(!b)throw e.e2b("get"+a);return b.call(this.RG)}throw e.SOa();};l.iAa=function(a,b){this.kS.q9a(this.RG,a,b)};l.m3=function(){f.j.m3.call();var a=this;setTimeout(function(){a.kS.p9a(a)},5)};l.wIa=function(){this.za(a.K.bY)};
e.yb(c.nYb,"PRIM_WDGT","Object",{});var s=l;s.get=s.bva;s.set=s.iAa;s.invoke=s.n9a;c.mYb=function(){f.w.call(this);var b=this.$Ia(),b=this.kS=t[b],c=this.RG=new (b.iX());c.LANSA_Component=this;c.LANSA_Class=b;b.o9a(c);this.yh&=~a.ji.BP;this.yh&=~a.ji.uY};var f=c.u(c.mYb,c.Pdb);f.Cg=function(){return c.oZb};f.zd=function(a,c,d){f.j.zd.call(this,a,c,d);a=this.Ma().ib();b.Kd[a].cJc(this.RG)};f.n9a=function(a,b){if(this.kS.xP()){var c=this.RG[a];if(!c)throw e.f2b(a);return c.apply(this.RG,b)}throw e.SOa();
};f.bva=function(a){if(this.kS.xP()){var b=this.RG["get"+a];if(!b)throw e.e2b("get"+a);return b.call(this.RG)}throw e.SOa();};f.iAa=function(a,b){this.kS.q9a(this.RG,a,b)};f.Uzd=function(){this.wIa()};f[a.R.Cka]=function(){this.kS.p9a(this)};f[a.R.uD]=function(){this.Ob()&&this.kS.r9a(this.RG)};f.Iba=function(){f.j.Iba.call(this);this.Ob()&&this.kS.r9a(this.RG)};e.yb(c.mYb,"PRIM_WDGT","Control",{});s=f;s.get=s.bva;s.set=s.iAa;s.invoke=s.n9a;c.gYb=function(){d.w.call(this);this.Rc=b.Cd(0,0,100,100);
this.lDa=this.NDa=""};var d=c.u(c.gYb,c.Pdb);d.Cg=function(){return c.PYb};d.Ewc=function(){return this.NDa};d.dXc=function(b){this.NDa!=b&&(this.NDa=b,this.fa(a.a.g),this.Gd())};d.aT=function(){return this.lDa};d.Pib=function(a){this.lDa=a};d.zI=function(a){var d=this.Wm(),e=this.nq();if(d||e){var f=new c.ja,g=[];g[0]=d;g[1]=e;g[2]=a;g[3]=0;g[4]=0;var h=this.ib();g[3]=0;g[4]=0;null!=h&&b.Kd[h].L8c(g);f.Oa(g[3]);f.Aa(g[4]);d&&a.Oa(a.O()+this.ga.pk()+f.$()+this.ga.Al());e&&a.Aa(a.M()+this.ga.dl()+
f.ba()+this.ga.Am())}};e.yb(c.gYb,"PRIM_WEB","HtmlContainer",{Wa:{Html:{f:d.Ewc,i:function(a){this.dXc(e.ma(a))}},Description:{f:d.aT,i:function(a){this.Pib(e.ma(a))}}},qg:{vg:"Html"}});c.deb=function(a){w.w.call(this,a)};var w=c.u(c.deb,c.kl);w.OKa=function(){return!1};w.QKa=function(){return this.la.iq()||this.la.aK?!1:!0};w.gCc=function(){return 0<this.i0a().length};w.LL=function(a){w.j.LL.call(this,a);return!1};w.pGb=function(a){var b=this.i0a();for(a=a?b.indexOf(a)+1:0;0<=a&&a<b.length;){var c=
b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a++}return!1};w.qGb=function(a){var b=this.i0a();for(a=a?b.indexOf(a)-1:b.length-1;0<=a;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a--}return!1};w.i0a=function(){var a=[],b=[];this.u0b(this.v,b);for(var c=1;c<b.length;c++)a=a.concat(b[c]||[]);return a=a.concat(b[0]||[])};w.u0b=function(a,b){var c=a.tabIndex;0<=c&&(b[c]===h&&(b[c]=[]),b[c].push(a));for(var c=a.childNodes,d=0;d<c.length;d++)a=c[d],this.u0b(a,b)};w.TW=w[a.Da.uJ]=
function(b){b.Be=a.Da.H8|a.Da.Isa};c.oZb=function(a){u.w.call(this,a);this.Xa=null};var u=c.u(c.oZb,c.deb);u.Ve=function(a,b){this.v=document.createElement("div");this.v.setAttribute("id",a+this.fc);this.v.setAttribute("LANSAHandle",this.fc);return u.j.Ve.call(this,a,b)};u.cJc=function(a){null==this.Xa&&(this.Xa=document.createElement("div"),this.Xa.style.left="0px",this.Xa.style.top="0px",this.Xa.style.width="100%",this.Xa.style.height="100%",a.LANSA_Class.nMb(a,this.Xa),this.v.appendChild(this.Xa))};
c.PYb=function(a){G.w.call(this,a);this.Xa=null};var G=c.u(c.PYb,c.deb);G.Mx=function(){G.j.Mx.call(this);this.v.style.whiteSpace="normal"};G.Ve=function(a,b){this.v=document.createElement("div");this.v.setAttribute("id",a+this.fc);this.v.setAttribute("LANSAHandle",this.fc);this.Xa=document.createElement("div");this.Xa.style.left="0px";this.Xa.style.top="0px";this.Xa.style.width="100%";this.Xa.style.height="100%";this.Xa.innerHTML=this.la.NDa;this.v.appendChild(this.Xa);return G.j.Ve.call(this,a,
b)};G.A8c=function(){var a=this.la.Wm(),b=this.la.nq();this.Xa.style.width=a?"":"100%";this.Xa.style.height=b?"":"100%";this.Xa.innerHTML=this.la.NDa};G.zd=function(){G.j.zd.call(this);this.A8c()};G.L8c=function(a){var b=a[0],c=a[2],d=this.Xa.style.width;a[1]&&!b&&(this.Xa.style.width=c.$()+"px");a[3]=this.Xa.clientWidth;a[4]=this.Xa.clientHeight;this.Xa.style.width=d}});
