window.LANSA.addSrc("web",function(e,c,a,b,h){e.Bb("PRIM_LABL");var t=null,p=null;a.DI={dib:0,T2b:1,U2b:2,S2b:3};a.DI.G={INLINE:a.DI.dib,LEFT:a.DI.T2b,RIGHT:a.DI.U2b,CENTER:a.DI.S2b};a.wD={hIa:0,CEb:1,GEb:2,HEb:3,JEb:4,b3a:5};a.wD.G={NONE:a.wD.hIa,NOTLOADED:a.wD.CEb,PERMISSIONDENIED:a.wD.GEb,POSITIONUNAVAILABLE:a.wD.HEb,TIMEOUT:a.wD.JEb,UNKNOWNERROR:a.wD.b3a};a.CS={Fxb:0,Dxb:1,Gxb:2,Exb:4};a.CS.G={NONE:a.CS.Fxb,ERROR:a.CS.Dxb,WARNING:a.CS.Gxb,INFORMATION:a.CS.Exb};c.Ydb=function(){r.w.call(this);
this.eb=[]};var r=c.u(c.Ydb,c.pd);r.U=function(){r.j.U.call(this)};r.Dc=function(){return this.eb.length};r.Ce=function(a){return this.eb[a-1]};r.HH=function(a){for(var c=null,d=0;d<this.eb.length;d++){var e=this.eb[d];if(b.hI(e.Tl,a)){c=e;break}}return c};e.yb(c.Ydb,"PRIM_WEB","URLParameters",{Wa:{Item:{f:function(a){return this.HH(e.ma(a))},Px:"na"},ItemCount:{f:r.Dc}},qg:{vg:"Item"},oq:{wp:function(a){return this.Ce(e.aa(a))},Lw:r.Dc}});c.Xdb=function(){g.w.call(this);this.cb=this.Tl=""};var g=
c.u(c.Xdb,c.pd);g.Jh=function(){return this.Tl.toUpperCase()};g.Ka=function(){return this.cb};e.yb(c.Xdb,"PRIM_WEB","URLParameter",{Wa:{Name:{f:g.Jh},Value:{f:g.Ka}}});c.Vdb=function(){l.w.call(this);try{var a,b=(new Date).toString();localStorage.setItem(b,b);a=localStorage.getItem(b)==b;localStorage.removeItem(b);a&&(t=localStorage)}catch(c){}this.mr=null};var l=c.u(c.Vdb,c.pd);l.U=function(){l.j.U.call(this)};l.x4a=function(){return null!=t};l.Dc=function(){return this.XO().length};l.Ce=function(a){return this.XO()[a-
1]};l.HH=function(a){for(var b=null,c=this.XO(),d=0;d<c.length;d++){var e=c[d];if(e.Tl==a){b=e;break}}return b};l.XO=function(){if(null==this.mr&&(this.mr=[],t))for(var a=0;a<t.length;a++){var b=t.key(a);""!=b&&t[b]!=h&&this.mr.push(new c.hNa(b))}return this.mr};l.mza=function(){this.mr=null};l.dh=function(a,b){var d=this.XO(),e=this.HH(a);null==e&&(e=new c.hNa(a),d.push(e));e.Va(b)||d.splice(d.indexOf(e),1)};l.Mr=function(c){var d=this.XO(),e=this.HH(c);null!=e&&(t.removeItem(c),d.splice(d.indexOf(e),
1),b.sq().u9(a.XD.ona))};l.Co=function(){t&&(t.clear(),this.mza(),b.sq().u9(a.XD.ona))};e.yb(c.Vdb,"PRIM_WEB","LocalStorage",{Wa:{Available:{f:l.x4a},Item:{f:function(a){return this.HH(e.ma(a))},Px:"na"},ItemCount:{f:l.Dc}},Gc:{Add:l.dh,Remove:l.Mr,Clear:l.Co},qg:{vg:"Item"},oq:{wp:function(a){return this.Ce(e.aa(a))},Lw:l.Dc}});c.hNa=function(a){s.w.call(this);this.Tl=a};var s=c.u(c.hNa,c.pd);s.Jh=function(){return this.Tl};s.Ka=function(){var a="";t&&(a=t[this.Tl],a===h&&(a=""));return a};s.Va=
function(c){var d=!0;try{t[this.Tl]=c,b.sq().u9(a.XD.ona)}catch(e){b.sq().mGb(a.XD.ona),d=!1}return d};e.yb(c.hNa,"PRIM_WEB","LocalStorageItem",{Wa:{Name:{f:s.Jh},Value:{f:s.Ka,i:function(a){this.Va(e.ma(a))}}},qg:{vg:"Value"}});c.Wdb=function(){f.w.call(this);try{var a,b=(new Date).toString();sessionStorage.setItem(b,b);a=sessionStorage.getItem(b)==b;sessionStorage.removeItem(b);a&&(p=sessionStorage)}catch(c){}this.mr=null};var f=c.u(c.Wdb,c.pd);f.U=function(){f.j.U.call(this)};f.x4a=function(){return null!=
p};f.Dc=function(){return this.XO().length};f.Ce=function(a){return this.XO()[a-1]};f.HH=function(a){for(var b=null,c=this.XO(),d=0;d<c.length;d++){var e=c[d];if(e.Tl==a){b=e;break}}return b};f.XO=function(){if(null==this.mr&&(this.mr=[],p))for(var a=0;a<p.length;a++){var b=p.key(a);""!=b&&p[b]!=h&&this.mr.push(new c.iNa(b))}return this.mr};f.mza=function(){this.mr=null};f.dh=function(a,b){var d=this.XO(),e=this.HH(a);null==e&&(e=new c.iNa(a),d.push(e));e.Va(b)||d.splice(d.indexOf(e),1)};f.Mr=function(c){var d=
this.XO(),e=this.HH(c);null!=e&&(p.removeItem(c),d.splice(d.indexOf(e),1),b.sq().u9(a.XD.pna))};f.Co=function(){p&&(p.clear(),this.mza(),b.sq().u9(a.XD.pna))};e.yb(c.Wdb,"PRIM_WEB","SessionStorage",{Wa:{Available:{f:f.x4a},Item:{f:function(a){return this.HH(e.ma(a))},Px:"na"},ItemCount:{f:f.Dc}},Gc:{Add:f.dh,Remove:f.Mr,Clear:f.Co},qg:{vg:"Item"},oq:{wp:function(a){return this.Ce(e.aa(a))},Lw:f.Dc}});c.iNa=function(a){d.w.call(this);this.Tl=a};var d=c.u(c.iNa,c.pd);d.Jh=function(){return this.Tl};
d.Ka=function(){var a="";p&&(a=p[this.Tl],a===h&&(a=""));return a};d.Va=function(c){var d=!0;try{p[this.Tl]=c,b.sq().u9(a.XD.pna)}catch(e){b.sq().mGb(a.XD.pna),d=!1}return d};e.yb(c.iNa,"PRIM_WEB","SessionStorageItem",{Wa:{Name:{f:d.Jh},Value:{f:d.Ka,i:function(a){this.Va(e.ma(a))}}},qg:{vg:"Value"}});c.Udb=function(){w.w.call(this)};var w=c.u(c.Udb,c.pd);w.U=function(){w.j.U.call(this)};w.XAc=function(a){0<a&&window.history.go(0-a)};w.YAc=function(a){0<a&&window.history.go(a)};w.dh=function(a){var c=
window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(c+="?"+a);window.history.pushState(null,"",c);b.sq().yIa()};w.PPc=function(a){var c=window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(c+="?"+a);window.history.replaceState(null,"",c);b.sq().yIa()};e.yb(c.Udb,"PRIM_WEB","History",{Gc:{Add:function(a){this.dh(e.ma(a))},Replace:function(a){this.PPc(e.ma(a))},GoBack:function(a){this.XAc(a===h?1:e.aa(a))},GoForward:function(a){this.YAc(a===
h?1:e.aa(a))}}});c.ZXb=function(){u.w.call(this);this.Rc=b.Cd(0,0,400,400);this.lDa=this.Zh="";this.yh&=~a.ji.BP;this.yh&=~a.ji.uY};var u=c.u(c.ZXb,c.hm);u.Cg=function(){return c.pYb};u.ho=function(){return this.Zh};u.xq=function(b){this.Zh!=b&&(this.Zh=b,this.fa(a.a.g))};u.aT=function(){return this.lDa};u.Pib=function(a){this.lDa=a};u.zd=function(a,c,d){u.j.zd.call(this,a,c,d);a=this.Ma().ib();b.Kd[a].xq(this.ho())};u.Qrc=function(){this.za(a.K.iQb)};e.yb(c.ZXb,"PRIM_WEB","Page",{Wa:{Source:{f:u.ho,
i:function(a){this.xq(e.ma(a))}},Description:{f:u.aT,i:function(a){this.Pib(e.ma(a))}}}});c.nla=function(){G.w.call(this)};var G=c.u(c.nla,c.hm);G.l6a=function(){for(var a=null,b=this;b;){if(b instanceof c.Zdb){a=b;break}b=b.$b}return a};G.Eba=function(){G.j.Eba.call(this);var a=this.l6a();a&&a.bX(this)};G.fZ=function(){G.j.fZ.call(this);var a=this.l6a();a&&a.cX(this)};G.Gh=function(a){G.j.Gh.call(this,a);var b=this.l6a();b==this&&b.az(a,!1)};e.yb(c.nla,"PRIM_WEB","RichTextItem",{});c.ceb=function(){k.w.call(this)};
var k=c.u(c.ceb,c.nla);k.Cg=function(){return c.cZb};e.yb(c.ceb,"PRIM_WEB","RichTextLine",{});c.$db=function(){n.w.call(this)};var n=c.u(c.$db,c.nla);n.Cg=function(){return c.aZb};e.yb(c.$db,"PRIM_WEB","RichTextBreak",{});c.aeb=function(){A.w.call(this);this.bW=null;this.PEa=a.DI.dib;this.yXa=this.zXa=0};var A=c.u(c.aeb,c.nla);A.U=function(){A.j.U.call(this);this.vQa(null)};A.Cg=function(){return c.bZb};A.ezc=function(){return this.bW};A.vQa=function(b){this.bW!=b&&(null!=this.bW&&(this.bW.va(this,
this.aCb),this.bW.Ab()),this.bW=b,null!=this.bW&&(this.bW.ua(),this.bW.ya(this,this.aCb)),this.fa(a.a.g))};A.Kqd=function(){return this.PEa};A.f5b=function(b){this.PEa!=b&&(this.PEa=b,this.fa(a.a.g))};A.fzc=function(){return this.zXa};A.h5b=function(b){this.zXa!=b&&(this.zXa=b,this.fa(a.a.g))};A.dzc=function(){return this.yXa};A.g5b=function(b){this.yXa!=b&&(this.yXa=b,this.fa(a.a.g))};A.zd=function(a,c,d){A.j.zd.call(this,a,c,d);a=this.Ma().ib();b.Kd[a].hg(this.PEa,this.zXa,this.yXa)};A.yhb=function(){var a=
this.bW,c=this.Ma().ib(),a=a?a.hh():"";b.Kd[c].bd(a)};A.aCb=function(b,c){switch(c.Ya){case a.a.ub:case a.a.Vb:this.vQa(null);break;case a.a.g:this.fa(a.a.g)}};e.yb(c.aeb,"PRIM_WEB","RichTextImage",{Wa:{Image:{f:A.ezc,i:function(a){this.vQa(a)}},Width:{f:A.fzc,i:function(a){this.h5b(e.aa(a))}},Height:{f:A.dzc,i:function(a){this.g5b(e.aa(a))}},Alignment:{f:function(){return e.Ja(this.PEa,a.DI.G)},i:function(b){this.f5b(e.Ba(b,a.DI.G))}}}});c.jNa=function(){S.w.call(this);this.yR=null};var S=c.u(c.jNa,
c.nla);S.Cg=function(){return c.dZb};S.iT=function(){null==this.yR&&(this.yR=new c.beb(this));return this.yR};e.yb(c.jNa,"PRIM_WEB","RichTextParagraph",{Wa:{Items:{f:S.iT}}});c.Zdb=function(){M.w.call(this);this.Rc=b.Cd(0,0,100,100)};var M=c.u(c.Zdb,c.jNa);M.Cg=function(){return c.$Yb};M.bX=function(b){if(!this.Yc()){var c=e.Tb();c.Zb("ITEM",b);this.za(a.K.rY,c);c.qc()}};M.cX=function(b){if(!this.Yc()){var c=e.Tb();c.Zb("ITEM",b);this.za(a.K.tY,c);c.qc()}};M.k2=function(b){if(!this.Yc()){var c=e.Tb();
c.Zb("ITEM",b);this.za(a.K.sY,c);c.qc()}};M.az=function(b,c){if(!c&&!this.Yc()){var d=e.Tb();d.Zb("ITEM",b);d.af("CONTINUE",!0);this.za(a.K.bI,d);c=!d.Nf("CONTINUE");d.qc()}return c};e.yb(c.Zdb,"PRIM_WEB","RichText",{});c.beb=function(a){v.w.call(this);this.eb=[];this.Ly=a};var v=c.u(c.beb,c.pd);v.U=function(){v.j.U.call(this)};v.Dc=function(){return this.eb.length};v.Ce=function(a){return this.eb[a-1]};v.dh=function(b,d,e,f){var g=new c.ceb;g.ua();g.bc(b);d!=h&&g.Cb(d);e!=h&&g.mm(e);f!=h&&g.Ln(f);
g.Ia(this.Ly);this.eb[this.eb.length]=g;this.Ly.fa(a.a.g);this.Ly.Ob()&&this.Ly.Dg();return g};v.Tec=function(){var b=new c.$db;b.ua();b.Ia(this.Ly);this.eb[this.eb.length]=b;this.Ly.fa(a.a.g);this.Ly.Ob()&&this.Ly.Dg();return b};v.bfc=function(b,d,e,f,g,k,n){var l=new c.aeb;l.ua();l.vQa(b);d!=h&&l.f5b(d);e!=h&&l.h5b(e);f!=h&&l.g5b(f);g!=h&&l.Cb(g);k!=h&&l.mm(k);n!=h&&l.Ln(n);l.Ia(this.Ly);this.eb[this.eb.length]=l;this.Ly.fa(a.a.g);this.Ly.Ob()&&this.Ly.Dg();return l};v.gfc=function(b,d,e,f){var g=
new c.jNa;g.ua();b!=h&&g.bc(b);d!=h&&g.Cb(d);e!=h&&g.mm(e);f!=h&&g.Ln(f);g.Ia(this.Ly);this.eb[this.eb.length]=g;this.Ly.fa(a.a.g);this.Ly.Ob()&&this.Ly.Dg();return g};v.Mr=function(b){this.eb.splice(this.eb.indexOf(b),1);b.Ia(null);b.Ab();this.Ly.fa(a.a.g)};v.ak=function(){for(;0<this.eb.length;)this.Mr(this.eb[0]);this.Ly.fa(a.a.g)};e.yb(c.beb,"PRIM_WEB","RichTextItems",{Wa:{Item:{f:function(a){return this.Ce(e.aa(a))},Px:"na"},ItemCount:{f:v.Dc}},Gc:{Add:v.dh,AddBreak:v.Tec,AddImage:function(b,
c,d,f,g,h,k){return this.bfc(b,e.Ba(c,a.DI.G),d,f,g,h,k)},AddParagraph:v.gfc,Remove:v.Mr,RemoveAll:v.ak},qg:{vg:"Item"},oq:{wp:function(a){return this.Ce(e.aa(a))},Lw:v.Dc}});c.aYb=function(){C.w.call(this);this.Rc=b.Cd(0,0,100,100)};var C=c.u(c.aYb,c.hm);C.Cg=function(){return c.HYb};C.zd=function(a,b,c){C.j.zd.call(this,a,b,c)};C.Xi=function(a){this.WF();a&&this.Mya();b.Ra().Ry(this)};C.iy=function(){this.ga.rS()};e.yb(c.aYb,"PRIM_WEB","Camera",{});c.kYb=function(){J.w.call(this);this.Rc=b.Cd(0,
0,100,100);this.jE=null;this.FGa("")};var J=c.u(c.kYb,c.hm);J.U=function(){this.jE=null;J.j.U.call(this)};J.Cg=function(){return c.eZb};J.$ta=function(){this.Ma()&&this.FGa(this.Ma().jtc());return this.jE};J.FGa=function(a){this.jE=new c.LF({data:a,mimetype:"image/png",filename:"signature.png"})};J.Co=function(){if(this.Ma()){var a=this.Ma().ib();b.Kd[a].Co();this.zc()}};J.zd=function(a,b,c){J.j.zd.call(this,a,b,c)};J.Xi=function(a){this.WF();a&&this.Mya();b.Ra().Ry(this)};J.iy=function(){this.ga.rS()};
J.zc=function(){this.za(a.K.fh)};e.yb(c.kYb,"PRIM_WEB","Signature",{Wa:{Blob:{f:J.$ta}},Gc:{Clear:J.Co}});c.fYb=function(){y.w.call(this);this.Gub=this.Ysb=this.vqb=this.uqb=this.qqb=this.DWa=this.Jtb=0;this.T6=a.wD.CEb};var y=c.u(c.fYb,c.pd);y.Ixc=function(){return this.Jtb};y.Wwc=function(){return this.DWa};y.Csc=function(){return this.qqb};y.Psc=function(){return this.uqb};y.Qsc=function(){return this.vqb};y.twc=function(){return this.Ysb};y.Ezc=function(){return this.Gub};y.pnd=function(){return this.T6};
y.XOc=function(){var b=this;navigator.geolocation&&navigator.geolocation.getCurrentPosition(function(d){b.Jtb=d.coords.longitude;b.DWa=d.coords.latitude;b.qqb=d.coords.accuracy;b.uqb=d.coords.altitude?d.coords.altitude:0;b.vqb=d.coords.altitudeAccuracy?d.coords.altitudeAccuracy:0;b.Ysb=d.coords.heading?d.coords.heading:0;b.Gub=d.coords.speed?d.coords.speed:0;b.T6=a.wD.hIa;d=new c.Tka;b.za(a.K.N1b,d)},function(d){b.Jtb=0;b.DWa=0;b.qqb=0;b.uqb=0;b.vqb=0;b.Ysb=0;b.Gub=0;b.T6=a.wD.b3a;switch(d.code){case d.PERMISSION_DENIED:b.T6=
a.wD.GEb;break;case d.POSITION_UNAVAILABLE:b.T6=a.wD.HEb;break;case d.TIMEOUT:b.T6=a.wD.JEb;break;case d.UNKNOWN_ERROR:b.T6=a.wD.b3a}d=new c.Tka;b.za(a.K.N1b,d)});return this.DWa};e.yb(c.fYb,"PRIM_WEB","Geolocation",{Wa:{Longitude:{f:y.Ixc},Latitude:{f:y.Wwc},Accuracy:{f:y.Csc},Altitude:{f:y.Psc},AltitudeAccuracy:{f:y.Qsc},Heading:{f:y.twc},Speed:{f:y.Ezc},ErrorCode:{f:function(){return e.Ja(this.T6,a.wD.G)}}},Gc:{Refresh:y.XOc}});c.cYb=function(){z.w.call(this)};var z=c.u(c.cYb,c.pd);z.kJc=function(b,
c){if("undefined"!==typeof console)switch(c){case a.CS.Dxb:console.error(b);break;case a.CS.Gxb:console.warn(b);break;case a.CS.Exb:console.info(b);break;default:console.log(b)}};e.yb(c.cYb,"PRIM_WEB","Console",{Wa:{},Gc:{Log:function(b,c){return this.kJc(e.ma(b),c?e.Ba(c,a.CS.G):a.CS.Fxb)}}});c.eYb=function(){O.w.call(this);this.Yb=this.Za=null;this.zy=this.ir="";this.Ptb=!1};var O=c.u(c.eYb,c.Kr);O.U=function(){O.j.U.call(this);this.Vk(null)};O.Cg=function(){return c.NYb};O.hh=function(){return this.ir};
O.q5a=function(){return this.zy};O.Hf=function(b){this.Za!=b&&(this.Vk(b),this.l(a.a.g))};O.vb=function(){var a=null;return a=this.Za};O.ic=function(){return this.Yb};O.T5a=function(){return this.Ptb};O.R4b=function(b){this.Ptb!=b&&(this.Ptb=b,this.fa(a.a.g))};O.zc=function(){this.za(a.K.fh)};O.V3a=function(b){var c=e.Tb();c.Zb("FILE",b);this.za(a.K.RFb,c);c.qc()};O.qS=function(){this.ZQ=b.hla(this.Yb.sj());this.Za.HS(this.ic())};O.Vk=function(a){var c=null;a&&(c=a.xt(),this.Za==a?c.Rm(this.Yb):a.ov(c));
this.Za&&(this.Za.va(this),this.Yb.va(this),b.ea(this.Yb),this.Yb=null);if(this.Za=a)this.Za.ya(this,this.Ij),this.Yb=c,this.Yb.ya(this,this.qv);this.Mg()};O.rJd=function(){};O.Ij=function(b,c){c.Ya==a.a.g?c.gp==a.he.Ot?this.Za.ov(this.ic()):this.Vk(this.Za):c.Ya==a.a.ub&&this.Hf(null)};O.qv=function(b,c){c.Ya==a.a.g&&c.gp==a.he.Ot&&this.qS()};e.yb(c.eYb,"PRIM_WEB","FilePicker",{Wa:{MultiSelect:{f:O.T5a,i:function(a){this.R4b(e.Ha(a))}}}});c.Tdb=function(a){E.w.call(this);this.yWa=a;this.VV=this.jE=
null};var E=c.u(c.Tdb,c.pd);E.U=function(){null!=this.jE&&(this.jE=null);null!=this.VV&&(b.pzb(this.VV),this.VV=null);E.j.U.call(this)};E.Jh=function(){return this.yWa.name};E.$ta=function(){null==this.jE&&(this.jE=new c.NTb(this.yWa));return this.jE};E.v6a=function(){return this.yWa.size};E.Yxc=function(){return this.yWa.type};e.yb(c.Tdb,"PRIM_WEB","File",{Wa:{Name:{f:E.Jh},Blob:{f:E.$ta},FileSize:{f:E.v6a},MimeType:{f:E.Yxc}}});c.bYb=function(){fa.w.call(this)};var fa=c.u(c.bYb,c.pd);fa.nhb=function(a){var d=
this;if(window.FileReader&&a instanceof c.LF){if(a=a.$ia()){var e=b.mQ(),f=new FileReader;f.onload=function(a){d.aX(a.target.result);b.gx(e)};f.readAsText(a)}}else d.aX("")};fa.aX=function(b){var c=e.Tb();c.bF("DATA",b);this.za(a.K.Q1,c)};e.yb(c.bYb,"PRIM_WEB","ClobReader",{Gc:{Read:fa.nhb}});c.$Xb=function(){ea.w.call(this)};var ea=c.u(c.$Xb,c.pd);ea.nhb=function(a){var d=this;if(window.FileReader&&a instanceof c.LF){if(a=a.$ia()){var e=b.mQ(),f=new FileReader;f.onload=function(a){d.aX(b.AFb(a.target.result));
b.gx(e)};f.readAsDataURL(a)}}else d.aX("","")};ea.aX=function(b){var c=e.Tb();c.bF("DATA",b);this.za(a.K.Q1,c)};e.yb(c.$Xb,"PRIM_WEB","BlobReader",{Gc:{Read:ea.nhb}});c.$Yb=function(a){ia.w.call(this,a)};var ia=c.u(c.$Yb,c.kl);ia.bc=function(a){this.v.textContent=a};ia.Mx=function(){ia.j.Mx.call(this);this.v.style.whiteSpace="normal";this.v.style.overflowX="auto";this.v.style.overflowY="auto"};ia.Ve=function(a,b){this.v=document.createElement("div");this.v.setAttribute("id",a+this.fc);this.v.setAttribute("LANSAHandle",
this.fc);return ia.j.Ve.call(this,a,b)};c.dZb=function(a){V.w.call(this,a)};var V=c.u(c.dZb,c.kl);V.bc=function(a){this.v.textContent=a};V.Tva=function(){return!1};V.iea=function(){};V.Mx=function(){};V.Ve=function(a,b){this.v=document.createElement("p");this.v.setAttribute("id",a+this.fc);this.v.setAttribute("LANSAHandle",this.fc);return V.j.Ve.call(this,a,b)};c.aZb=function(a){T.w.call(this,a)};var T=c.u(c.aZb,c.kl);T.Tva=function(){return!1};T.iea=function(){};T.Mx=function(){};T.Ve=function(a,
b){this.v=document.createElement("br");this.v.setAttribute("id",a+this.fc);this.v.setAttribute("LANSAHandle",this.fc);return T.j.Ve.call(this,a,b)};c.bZb=function(a){I.w.call(this,a)};var I=c.u(c.bZb,c.kl);I.bd=function(a){this.v.src=a};I.Tva=function(){return!1};I.hg=function(b,c,d){this.v.style.width=0==c?"auto":c+"px";this.v.style.height=0==d?"auto":d+"px";switch(b){case a.DI.dib:this.v.style.marginLeft="initial";this.v.style.marginRight="initial";this.v.style.display="inline";this.v.style.cssFloat=
"none";break;case a.DI.T2b:this.v.style.marginLeft="initial";this.v.style.marginRight="initial";this.v.style.display="inline";this.v.style.cssFloat="left";break;case a.DI.U2b:this.v.style.marginLeft="initial";this.v.style.marginRight="initial";this.v.style.display="inline";this.v.style.cssFloat="right";break;case a.DI.S2b:this.v.style.marginLeft="auto",this.v.style.marginRight="auto",this.v.style.display="block",this.v.style.cssFloat="none"}};I.iea=function(){};I.Mx=function(){this.v.style.borderStyle=
"solid"};I.Ve=function(a,b){this.v=document.createElement("img");this.v.setAttribute("id",a+this.fc);this.v.setAttribute("LANSAHandle",this.fc);return I.j.Ve.call(this,a,b)};c.cZb=function(a){F.w.call(this,a)};var F=c.u(c.cZb,c.kl);F.bc=function(a){this.v.textContent=a};F.Tva=function(){return!1};F.iea=function(){};F.Mx=function(){};F.Ve=function(a,b){this.v=document.createElement("span");this.v.setAttribute("id",a+this.fc);this.v.setAttribute("LANSAHandle",this.fc);return F.j.Ve.call(this,a,b)};
c.HYb=function(a){aa.w.call(this,a)};var aa=c.u(c.HYb,c.kl);aa.Ve=function(a,b){this.v=document.createElement("div");this.v.setAttribute("id",a+this.fc);this.v.setAttribute("LANSAHandle",this.fc);return aa.j.Ve.call(this,a,b)};c.eZb=function(a){Z.w.call(this,a);this.HG=this.qm=null;this.Xbc=this.Jvb=!1;this.itb=null};var Z=c.u(c.eZb,c.kl);Z.Ve=function(a,b){this.v=document.createElement("div");this.v.setAttribute("id",a+this.fc);this.v.setAttribute("LANSAHandle",this.fc);this.v.style.msTouchAction=
"none";this.HG=document.createElement("canvas");this.HG.style.kLd="none";this.v.appendChild(this.HG);this.qm=this.HG.getContext("2d");this.mzb();return Z.j.Ve.call(this,a,b)};Z.Jl=function(a,b,c,d){Z.j.Jl.call(this,a,b,c,d);a=this.qm.getImageData(0,0,this.HG.width-1,this.HG.height-1);this.HG.width=this.Ec;this.HG.height=this.Pc;this.qm.putImageData(a,0,0)};Z.LL=function(a){this.h6b(a);return!0};Z.hfb=function(a){this.g6b(a);return!0};Z.wNa=function(a){this.f6b(a);return!0};Z.Noa=function(a){this.h6b(a);
return!0};Z.Ru=function(a){this.g6b(a);return!0};Z.cea=function(a){this.f6b(a);return!0};Z.mMb=function(a){this.v.onpointerdown===h&&a.touches!==h?(a.iqb=a.touches[0].pageX-this.la.jq(),a.jqb=a.touches[0].pageY-this.la.kq()):(a.iqb=a.clientX-this.la.jq(),a.jqb=a.clientY-this.la.kq());this.la.zc()};Z.mzb=function(){this.z_a(!0);this.itb=new Image;this.itb.onload=function(){throw 0;};this.itb.src=null};Z.z_a=function(a){(this.Xbc||a)&&this.qm.clearRect(0,0,this.qm.canvas.width,this.qm.canvas.height);
this.Xbc=!1};Z.jtc=function(){var a=this.HG.toDataURL("image/png");return b.AFb(a)};Z.Co=function(){this.mzb()};Z.h6b=function(a){a.preventDefault();this.z_a(!1);this.qm.beginPath();this.mMb(a);this.qm.moveTo(a.iqb,a.jqb);this.Jvb=!0};Z.f6b=function(a){a.preventDefault();this.Jvb=!1};Z.qHd=function(a){this.Ru(a)};Z.g6b=function(a){this.Jvb&&(a.preventDefault(),this.z_a(!1),this.qm.strokeStyle="rgb(0,0,0)",this.qm.lineWidth=1,this.mMb(a),this.qm.lineTo(a.iqb,a.jqb),this.qm.stroke())};c.pYb=function(a){ca.w.call(this,
a);this.Wra=this.Xa=null};var ca=c.u(c.pYb,c.kl);ca.xq=function(a){this.Wra.src=a};ca.Ve=function(a,b){this.v=document.createElement("div");this.v.setAttribute("id",a+this.fc);this.v.setAttribute("LANSAHandle",this.fc);this.Wra=document.createElement("iframe");this.WFa(this.Wra);this.Wra.style.width="100%";this.Wra.style.height="100%";this.v.appendChild(this.Wra);return ca.j.Ve.call(this,a,b)};ca.xW=function(){var a=this;ca.j.xW.call(this);a.v.addEventListener("load",function(){a.la.Qrc()},!1)};ca.WFa=
function(a){ca.j.WFa.call(this,a);this.v.style.overflowX="auto";this.v.style.overflowY="auto"};c.NYb=function(a){Q.w.call(this,a);this.iR=null};var Q=c.u(c.NYb,c.leb);Q.Ve=function(a,b){var c=Q.j.Ve.call(this,a,b);this.iR=document.createElement("input");this.iR.type="File";var d=this.iR.style;this.pb.style.zIndex=1;d.opacity=0;d.position="absolute";d.zIndex=99998;d.background="rgb( 255, 0, 0 )";c.appendChild(this.iR);return c};Q.zd=function(){Q.j.zd.call(this);this.y8c()};Q.Jl=function(a,b,c,d){Q.j.Jl.call(this,
a,b,c,d);this.iR.style.left="0px";this.iR.style.top="0px";this.iR.style.width=c+"px";this.iR.style.height=d+"px"};Q.xW=function(){var a=this;this.E1();a.iR.addEventListener("change",function(b){a.Aic(b);a.iR.value=""},!1)};Q.y8c=function(){this.iR.multiple=this.la.T5a()};Q.Aic=function(a){a=a.target.files||a.dataTransfer.files;for(var b=0,d;d=a[b];b++)d=new c.Tdb(d),this.la.V3a(d)}},{rp:["PRIM_LABL"]});
