window.LANSA.addSrc("msg",function(e,c,a,b,h){e.Bb("PRIM_PPNL");a.zla={Y3:0,PKc:1,RKc:2,MKc:4,NKc:8};a.zla.G={NONE:a.zla.Y3,TEXT:a.zla.PKc,WARNING:a.zla.RKc,ERROR:a.zla.MKc,FATAL:a.zla.NKc};a.SY={SZb:1,UZb:2,TZb:4};a.SY.G={ERROR:a.SY.SZb,QUESTION:a.SY.UZb,INFORMATION:a.SY.TZb};a.Xn={vcd:16,QZa:1,hGa:16,eGa:32,jGa:64,gGa:128,iGa:256,fGa:512};a.Xn.G={NONE:a.Xn.QZa,OK:a.Xn.hGa,CANCEL:a.Xn.eGa,YES:a.Xn.jGa,NO:a.Xn.gGa,RETRY:a.Xn.iGa,IGNORE:a.Xn.fGa};a.QF={Peb:16,WZb:48,XZb:192,YZb:224,VZb:768};a.QF.G=
{OK:a.QF.Peb,OKCANCEL:a.QF.WZb,YESNO:a.QF.XZb,YESNOCANCEL:a.QF.YZb,IGNORERETRY:a.QF.VZb};c.WTb=function(){t.w.call(this)};var t=c.u(c.WTb,c.pd);e.gd(c.WTb,"PRIM_MSG",{});c.Mbb=function(){p.w.call(this);this.YB=[]};var p=c.u(c.Mbb,c.pd);p.Wxc=function(){e.Bb("PRIM_PCOL");var a=new c.WRb(this);return new c.KY(a)};p.dh=function(a,b){var e=new c.Nbb(this,a);this.YB.push(e);e.qi(b);this.Rrc(e);return e};p.Co=function(a){if(a)for(var b=0;b<this.YB.length;b++){var c=this.YB[b];c.Ca()==a&&(this.iGb(c),this.YB.splice(b--,
1),c.Xzb())}};p.Gic=function(){for(;0<this.YB.length;){var a=this.YB.shift();this.iGb(a);a.Xzb()}};p.Rrc=function(b){var c=e.Tb();c.Zb("MESSAGE",b);this.za(a.K.wKc,c);c.qc()};p.iGb=function(b){var c=e.Tb();c.Zb("MESSAGE",b);this.za(a.K.xKc,c);c.qc()};e.gd(c.Mbb,"PRIM_MSGQ",{Wa:{Messages:{f:p.Wxc}},Gc:{Add:function(a,b){return this.dh(e.ma(a),b===h?null:b)},Clear:function(a){return this.Co(a===h?null:a)},ClearAll:function(){return this.Gic()}}});c.WRb=function(a){r.w.call(this);this.nEa=a};var r=c.u(c.WRb,
c.Raa);r.Dc=function(){return this.nEa.YB.length};r.Fw=function(a){return this.nEa.YB[a]};c.Nbb=function(a,b){g.w.call(this);this.nEa=a;this.zg=b;this.Xa=null};var g=c.u(c.Nbb,c.pd);g.Jo=function(){return this.zg};g.Ca=function(){return this.Xa};g.qi=function(a){this.Yf()&&this.Xa!=a&&(null!=this.Xa&&(this.Xa.YF(this),this.Xa.va(this,this.$n)),this.Xa=a)&&(a.$E(this),a.ya(this,this.$n))};g.Yf=function(){return null!==this.nEa};g.Xzb=function(){this.qi(null);this.zg="";this.nEa=null};g.$n=function(b,
c){switch(c.Ya){case a.a.ub:this.qi(null)}};e.yb(c.Nbb,"PRIM_MSGQ","Message",{Wa:{Text:{f:g.Jo},Control:{f:g.Ca,i:g.qi}}});c.jYb=function(){l.w.call(this);this.Gpa=[]};var l=c.u(c.jYb,c.pd);l.U=function(){this.ak();l.j.U.call(this)};l.Ce=function(a){return this.Gpa[a]};l.Dc=function(){return this.Gpa.length};l.dh=function(b){this.Gpa.push(b);this.l(a.a.g)};l.ak=function(){this.Gpa=[];this.l(a.a.g)};l.Hxc=function(){for(var a="",b=0;b<this.Gpa.length;b++){var c=this.Gpa[b];c.length>a.length&&(a=c)}return a};
e.yb(c.jYb,"PRIM_WEB","MessageBoxCaptions",{Gc:{Add:l.dh,RemoveAll:l.ak}});c.iYb=function(){s.w.call(this);e.Bb("PRIM_PHBN");e.Bb("PRIM_LABL");this.$Ea=this.J7=this.Yga=null;this.mEa=a.SY.TZb;this.Sz=a.QF.Peb;this.Be=a.Xn.QZa;this.eUa=[];this.YQ=null;this.wYa=new c.Kr;this.vYa=new c.MP;this.gC=new c.hm;this.IG=e.re("PRIM_WEB","MessageBoxCaptions");this.IG.ua();this.IG.ya(this,this.HAb);this.xi=new c.idb;this.EM=new c.MP;this.UG=new c.MP;this.kK=new c.MP;this.eN=new c.MP;this.pN=new c.MP;this.RJ=new c.MP;
this.UG.Fa(this,a.K.nc,this.Hnc);this.EM.Fa(this,a.K.nc,this.Plc);this.kK.Fa(this,a.K.nc,this.rpc);this.eN.Fa(this,a.K.nc,this.Fnc);this.pN.Fa(this,a.K.nc,this.koc);this.RJ.Fa(this,a.K.nc,this.hnc);this.gC.Ia(this);this.xi.Ia(this);this.EM.Ia(this);this.UG.Ia(this);this.kK.Ia(this);this.eN.Ia(this);this.pN.Ia(this);this.RJ.Ia(this);this.J7=new c.tb;this.$Ea=new c.eg;this.J7.sd(this.$Ea);this.$Ea.Ad(a.m.tQ);this.$Ea.gg(9);this.s5b(this.J7);this.J7.ua();this.$Ea.ua();this.gC.Qa(90);this.gC.cf(!1);this.gC.Ta(57);
this.gC.Nb(!0);this.gC.IU(!0);this.gC.BZ(!0);this.xi.tf(6);this.xi.SD(a.xh.Gq);this.xi.Qa(20);this.xi.Ta(57);this.xi.Wt(64);this.xi.hM(64);this.xi.Jc(64);this.xi.hc(64);this.xi.cf(!1);this.UG.bc(b.Um().ok||"OK");this.eN.bc(b.Um().no||"No");this.kK.bc(b.Um().yes||"Yes");this.pN.bc(b.Um().retry||"Retry");this.EM.bc(b.Um().cancel||"Cancel");this.RJ.bc(b.Um().ignore||"Ignore");this.O3b(this.Sz);this.nPa(!1);this.ukb(!0)};var s=c.u(c.iYb,c.Sw);s.U=function(){this.IG.va(this,this.HAb);this.IG.Ab();this.IG=
null;this.qzb();s.j.U.call(this)};s.rVc=function(a){this.wYa.Cb(a)};s.ztc=function(){return this.wYa.Xf()};s.Atc=function(){return this.wYa.qj()};s.zia=function(){return this.vYa.Xf()};s.bG=function(a){this.vYa.Cb(a)};s.ttc=function(){return this.vYa.qj()};s.vAa=function(b){b!=this.tT()&&(this.bc(b),this.fTa(),this.l(a.a.g))};s.tT=function(){return this.Kb()};s.GXc=function(b){this.IG.ak();b!=this.yIb()&&(this.IG.dh(b),this.l(a.a.g))};s.Ctc=function(){return this.IG};s.yIb=function(){return 0<this.IG.Dc()?
this.IG.Ce(0):""};s.d4b=function(b){this.YQ!==b&&(null!=this.YQ&&(this.YQ.va(this,this.VAb),this.YQ.Ab()),this.YQ=b,null!==this.YQ&&(this.YQ.ua(),this.YQ.ya(this,this.VAb)),this.fTa(),this.l(a.a.g))};s.xuc=function(){return this.YQ};s.HXc=function(b){this.mEa!=b&&(this.mEa=b,this.fTa(),this.l(a.a.g))};s.apd=function(){return this.mEa};s.O3b=function(b){this.Sz=b;this.UG.Nb(0!=(this.Sz&a.Xn.hGa));this.EM.Nb(0!=(this.Sz&a.Xn.eGa));this.kK.Nb(0!=(this.Sz&a.Xn.jGa));this.eN.Nb(0!=(this.Sz&a.Xn.gGa));
this.RJ.Nb(0!=(this.Sz&a.Xn.fGa));this.pN.Nb(0!=(this.Sz&a.Xn.iGa))};s.Ljd=function(){return this.Sz};s.oGd=function(a){this.Be=a};s.Jqd=function(){return this.Be};s.Zjc=function(b,e,f){var g=new c.Kr;g.Ia(this.gC);g.Qa(0);g.cf(!1);g.Ta(e);g.Mn(a.xh.Gq);g.hc(f.fb());g.Jc(f.Ua());g.vh(!1);g.bc(b);return g};s.k6b=function(a,e){var f=b.Nv(0,0),g=new c.ja(0,0,0,0);b.ey(a,g,0,e);f.hc(g.$()+2);f.Jc(g.ba()+2);return f};s.Wyc=function(){if(null!=this.YQ)return this.YQ;var d="";switch(this.mEa){case a.SY.SZb:d=
"lansa_error.png";break;case a.SY.UZb:d="lansa_question.png";break;default:d="lansa_information.png"}var e=new c.xL;e.Ou(b.vc(d));return e};s.Kfc=function(){var a=this.vYa.qj().ab.gD(),b=null;this.UG.qj().ak();this.EM.qj().ak();this.kK.qj().ak();this.eN.qj().ak();this.pN.qj().ak();this.RJ.qj().ak();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.UG.qj().dh(b),this.EM.qj().dh(b),this.kK.qj().dh(b),this.eN.qj().dh(b),this.pN.qj().dh(b),this.RJ.qj().dh(b);this.UG.Tk(!1,!0);this.EM.Tk(!1,!0);
this.kK.Tk(!1,!0);this.eN.Tk(!1,!0);this.pN.Tk(!1,!0);this.RJ.Tk(!1,!0)};s.Qfc=function(){var a=this.wYa.qj().ab.gD(),b=null;this.gC.qj().ak();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.gC.qj().dh(b);this.gC.Tk(!1,!0)};s.lna=function(){this.Yga=b.mQ();this.Be=a.Xn.QZa;this.vyb();var c=b.Hl();this.fx(a.vj.Rla,null,c,null);this.oWc()};s.fTa=function(){this.pY()&&(this.vyb(),this.Dg())};s.vyb=function(){var a;this.qzb();this.xi.bd(this.Wyc());this.Kfc();this.Qfc();a=this.qwb();this.BMc(a)};
s.nza=function(){this.qwb();s.j.nza.call(this)};s.qwb=function(){var a=this.Qy(),b=this.gic(),c=this.mic(),c=this.lic(c),e=this.iic(a),f=this.hic(b),g=this.oic(c,e,f);this.RQc(g,b,e);this.qfc(b,c,f,g);return a};s.RQc=function(a,b,c){this.hc(a.fb());this.Jc(a.Ua());a=b.fb();b=b.Ua();this.EM.hc(a);this.UG.hc(a);this.kK.hc(a);this.eN.hc(a);this.pN.hc(a);this.RJ.hc(a);this.EM.Jc(b);this.UG.Jc(b);this.kK.Jc(b);this.eN.Jc(b);this.pN.Jc(b);this.RJ.Jc(b);this.gC.hc(c.fb());this.gC.Jc(c.Ua())};s.qfc=function(a,
b,c,e){this.pVc(a);a=e.Ua()-c.Ua();this.EM.Ta(a);this.UG.Ta(a);this.kK.Ta(a);this.eN.Ta(a);this.pN.Ta(a);this.RJ.Ta(a);this.xi.Qa(20);this.xi.Ta(this.Wp.Ua()+20);this.gC.Qa(40+b.fb());this.gC.Ta(this.Wp.Ua()+20)};s.oic=function(a,c,e){var f=b.NF(),g=b.Nv(0,0);a=this.kic(a,c);c=this.Jy.tKa(this.Jy.Kb(),this.Jy.bz().length)+10;g.hc(Math.max(a.fb(),c,e.fb())+60);g.Jc(this.Wp.Ua()+a.Ua()+e.Ua()+40);g.hc(Math.min(f.$()-40,g.fb()));g.Jc(Math.min(f.ba()-40,g.Ua()));return g};s.dja=function(a,b){var c=a;
b.length>a.length&&(c=b);return c};s.Gxc=function(){var a="",a=this.dja(this.UG.Kb(),a),a=this.dja(this.EM.Kb(),a),a=this.dja(this.kK.Kb(),a),a=this.dja(this.eN.Kb(),a),a=this.dja(this.pN.Kb(),a),a=this.dja(this.RJ.Kb(),a);return" "+a+" "};s.gic=function(){var a=this.Gxc(),c=b.Nv(0,0),c=this.UG.Pd();return c=this.k6b(a,c)};s.Qy=function(){var a=this.IG.Hxc(),c=b.Nv(0,0),c=this.gC.Pd();return c=this.k6b(a,c)};s.mic=function(){var a=b.Nv(0,0);a.hc(this.xi.fb());a.Jc(this.xi.Ua());return a};s.iic=function(a){var c=
b.Nv(0,0),e=a.fb()+4;a=this.IG.Dc()*(a.Ua()+4);e+=20;a+=20;e=170>e?170:e;a=70>a?70:a;a=630<a?630:a;c.hc(630<e?630:e);c.Jc(a);return c};s.lic=function(a){var c=b.Nv(0,0);c.Jc(a.Ua()+16);c.hc(a.fb()+8);return c};s.kic=function(a,c){var e=b.Nv(0,0);e.Jc(Math.max(a.Ua(),c.Ua()));e.hc(2+a.fb()+2+c.fb()+2);return e};s.hic=function(a){var c=b.Nv(0,0),e=25>a.Ua()?25:a.Ua();a.hc(66>a.fb()?66:a.fb());a.Jc(e);c.Jc(a.Ua()+24);c.hc(3*a.fb()+8);return c};s.pVc=function(b){b=b.fb()+20;var c=1;this.Sz&a.Xn.iGa&&
(this.pN.Qa(this.fb()-c*b),++c);this.Sz&a.Xn.fGa&&(this.RJ.Qa(this.fb()-c*b),++c);this.Sz&a.Xn.eGa&&(this.EM.Qa(this.fb()-c*b),++c);this.Sz&a.Xn.hGa&&(this.UG.Qa(this.fb()-c*b),++c);this.Sz&a.Xn.gGa&&(this.eN.Qa(this.fb()-c*b),++c);this.Sz&a.Xn.jGa&&this.kK.Qa(this.fb()-c*b)};s.BMc=function(a){for(var b=0,c=a.Ua(),e=0;e<this.IG.Dc();e++)this.eUa.push(this.Zjc(this.IG.Ce(e),b,a)),b+=c};s.oWc=function(){switch(this.Sz){case a.QF.Peb:case a.QF.WZb:this.UG.ze(!0,!0);break;case a.QF.XZb:case a.QF.YZb:this.kK.ze(!0,
!0);break;case a.QF.VZb:this.RJ.ze(!0,!0)}};s.Eja=function(a){this.Be=a;this.qn();b.gx(this.Yga);this.Yga=null};s.qzb=function(){for(var a=0;a<this.eUa.length;++a)this.eUa[a].Ia(null);this.eUa=[]};s.HAb=function(){this.fTa()};s.Hnc=function(){this.Eja(a.Xn.hGa)};s.Plc=function(){this.Eja(a.Xn.eGa)};s.rpc=function(){this.Eja(a.Xn.jGa)};s.Fnc=function(){this.Eja(a.Xn.gGa)};s.koc=function(){this.Eja(a.Xn.iGa)};s.hnc=function(){this.Eja(a.Xn.fGa)};s.VAb=function(b,c){switch(c.Ya){case a.a.ub:case a.a.Vb:this.d4b(null);
break;case a.a.g:this.l(a.a.g)}};e.yb(c.iYb,"PRIM_WEB","MessageBox",{Wa:{Title:{f:s.tT,i:function(a){this.vAa(e.ma(a))}},Caption:{f:s.yIb,i:function(a){this.GXc(e.ma(a))}},Text:{f:s.Jo,i:function(a){this.oM(e.ma(a))}},Captions:{f:s.Ctc},Image:{f:function(){return e.Ja(this.mEa,a.SY.G)},i:function(b){this.HXc(e.Ba(b,a.SY.G))}},CustomImage:{f:s.xuc,i:function(a){this.d4b(a)}},Result:{f:function(){return e.Ja(this.Be,a.Xn.G)}},Buttons:{f:function(){return e.Ja(this.Sz,a.QF.G)},i:function(b){this.O3b(e.Ba(b,
a.QF.G))}},CaptionStyle:{f:s.ztc,i:function(a){this.rVc(a)}},CaptionStyles:{f:s.Atc},ButtonStyle:{f:s.zia,i:function(a){this.bG(a)}},ButtonStyles:{f:s.ttc}},Gc:{Show:s.lna}});c.NMa=function(b){f.w.call(this);this.CWa=[];this.YB=[];this.Xa=b;this.nd=new c.Sw;this.nd.Fa(this,a.K.mB,this.fta);this.nd.Fa(this,a.K.u8,this.eta);this.iga=new c.hm;this.iga.mb(new c.ja(0,0,100,25));this.iga.Ia(this.nd);this.iga.cf(!1);this.iga.uc(a.FPb)};var f=c.u(c.NMa,c.Wi);f.iq=function(){return this.nd};f.dg=function(){return 0==
this.YB.length};f.$E=function(a){this.YB.push(a)};f.YF=function(a){this.YB.splice(this.YB.indexOf(a),1);this.dg()&&this.nd.qn()};f.fta=function(){e.Bb("PRIM_LABL");for(var b=0,f=6,g=100;b<this.YB.length;b++){var h=this.CWa[b],k=this.YB[b];h||(h=new c.Kr,h.Qa(5),h.cf(!1),h.Ta(f),h.Mn(a.xh.Gq),h.hc(320),h.Jc(20),h.vh(!1),this.CWa.push(h));h.Ia(this.iga);h.bc(k.Jo());h.Bic();g<h.fb()+15&&(g=h.fb()+15);f+=25}for(;b<this.CWa.length;b++)h=this.CWa[b],h.Ia(null);this.iga.Jc(f+6);this.iga.hc(g);this.nd.Jc(f+
6);this.nd.hc(g)};f.eta=function(){this.Xa.Tk(!0)}},{rp:["PRIM_PPNL"]});
