window.LANSA.addSrc("atlm",function(e,c,a){e.Bb("PRIM_CPST");a.k8={$fc:0,Mwb:1,Zfc:2,Lwb:4,agc:8,acd:15};a.TP={Lgb:0,C1b:1,B1b:2,yOc:3};a.TP.G={VERTICAL:a.TP.Lgb,HORIZONTAL:a.TP.C1b,DISPLAYPOSITION:a.TP.B1b,EO:a.TP.yOc};a.cxa={Q$c:0,pqb:1,O$c:2,S$c:3,P$c:4,R$c:5,eLd:6};a.Mxd={qNa:0,rNa:1};a.H_a={pab:32};c.wUb=function(c,e,h){b.w.call(this);this.lc=[];this.lc=e;this.Oh=this.hi=h;this.uqa=this.Nra=0;this.JQ=a.k8.$fc};var b=c.u(c.wUb,c.te);b.U=function(){b.j.U.call(this)};c.Xka=function(){h.w.call(this);
this.JEa=a.TP.Lgb};e.Bb("PRIM_TBLO");var h=c.u(c.Xka,c.Jxa);h.U=function(){h.j.U.call(this)};h.uqd=function(){return this.JEa};h.fYc=function(b){this.JEa!=b&&(this.JEa=b,this.l(a.a.g))};h.G4=function(a,b){var c=this.Fla(a);c.G4(b);return c};h.PO=function(a){return this.lf(a).PO()};h.Yid=function(a){return this.lf(a)};h.M5a=function(){return a.cxa.pqb};h.Wm=function(b,c){var e=h.j.Wm.call(this,b,c);if(e){var g=this.lf(b);!g||g.PO()!=a.eh.l8&&g.PO()!=a.eh.i8||(e=!1)}return e};h.nq=function(b,c){var e=
h.j.nq.call(this,b,c);if(e){var g=this.lf(b);!g||g.PO()!=a.eh.G1&&g.PO()!=a.eh.j8||(e=!1)}return e};h.n2=function(a){return this.lf(a)};h.Eha=function(a,b){var c=new e.re("PRIM_ATLI");c.qi(b);c.Ia(this);return c};h.yKc=function(a,b){return b=this.pe(a,void 0)};h.$jc=function(a){var b=new c.IMa;b.qi(a);return b};h.pe=function(b,e){for(var h=this.vA(b,!0);;){var g=new c.wUb(0,h,e);g.Oh.Ta(g.Oh.He()+this.$g);g.Oh.Qa(g.Oh.se()+this.Zg);g.Oh.Oa(g.Oh.Bs()-this.hj);g.Oh.Aa(g.Oh.AH()-this.gj);switch(this.JEa){case a.TP.Lgb:this.oO(g,
a.eh.l8);this.oO(g,a.eh.i8);this.oO(g,a.eh.G1);this.oO(g,a.eh.j8);this.oO(g,a.eh.tA);break;case a.TP.C1b:this.oO(g,a.eh.G1);this.oO(g,a.eh.j8);this.oO(g,a.eh.l8);this.oO(g,a.eh.i8);this.oO(g,a.eh.tA);break;case a.TP.B1b:for(var l=null,s=h,f=0;f<s.length&&null!=(l=s[f]);f++){var d=l;d.W5!=a.eh.tA&&0==(l.Ca().hb&a.H_a.pab)&&this.LZa(g,d)}this.oO(g,a.eh.tA)}if(0==g.Nra&&0==g.uqa)break;e.RZ(g.Nra,g.uqa)}return new c.gI(e.$(),e.ba())};h.oO=function(b,c){var e=null,g=b.lc;switch(c){case a.eh.l8:case a.eh.G1:case a.eh.tA:for(var h=
0;h<g.length&&null!=(e=g[h]);h++){var s=e;if(s.W5==c){var f=e.Ca();0==(f.hb&a.H_a.pab)&&this.LZa(b,s)}}break;case a.eh.i8:case a.eh.j8:for(h=g.length-1;0<=h&&null!=(e=g[h]);h--)s=e,s.W5==c&&(f=e.Ca(),0==(f.hb&a.H_a.pab)&&this.LZa(b,s))}};h.LZa=function(b,c){var e=c.wHb(),g,h;switch(c.W5){case a.eh.l8:h=0;b.JQ|=a.k8.Mwb;0!=c.QR&&e.ph(e.$(),b.hi.ba()*c.QR/100);e.Lb(b.Oh.O()+c.mf(),b.Oh.M()+c.hf());b.Oh.jPa(b.Oh.O(),b.Oh.M()+e.ba()+c.hf()+c.Bg());g=b.Oh.$()-(c.mf()+c.pg());e.ph(Math.max(g,0),e.ba());
this.nha(c,e);0<h&&(h>b.Oh.ba()&&(e=h-b.Oh.ba(),e>b.uqa&&(b.uqa=e)),b.Oh.p3b(0,h));break;case a.eh.i8:h=0;b.JQ|=a.k8.Zfc;0!=c.QR&&e.ph(e.$(),b.hi.ba()*c.QR/100);g=b.Oh.ba()-(e.ba()+c.hf()+c.Bg());0!=(b.JQ&a.k8.Mwb)&&(g=Math.max(g,0));b.Oh.ph(b.Oh.$(),g);e.Lb(b.Oh.O()+c.mf(),b.Oh.pa+c.hf());g=b.Oh.$()-(c.mf()+c.pg());e.ph(Math.max(g,0),e.ba());this.nha(c,e);0<h&&(h>b.Oh.ba()&&(e=h-b.Oh.ba(),e>b.uqa&&(b.uqa=e)),b.Oh.RZ(0,-h));break;case a.eh.G1:h=0;b.JQ|=a.k8.Lwb;0!=c.QR&&e.ph(b.hi.$()*c.QR/100,e.ba());
e.Lb(b.Oh.O()+c.mf(),b.Oh.M()+c.hf());g=b.Oh.O()+e.$()+c.mf()+c.pg();b.Oh.jPa(Math.max(g,b.hi.O()),b.Oh.M());g=b.Oh.ba()-(c.hf()+c.Bg());e.ph(e.$(),Math.max(g,0));this.nha(c,e);0<h&&(h>b.Oh.$()&&(e=h-b.Oh.$(),e>b.Nra&&(b.Nra=e)),b.Oh.p3b(h,0));break;case a.eh.j8:h=0;b.JQ|=a.k8.agc;0!=c.QR&&e.ph(b.hi.$()*c.QR/100,e.ba());g=b.Oh.$()-(e.$()+c.mf()+c.pg());0!=(b.JQ&a.k8.Lwb)&&(g=Math.max(g,0));b.Oh.ph(g,b.Oh.ba());e.Lb(b.Oh.na+c.mf(),b.Oh.M()+c.hf());g=b.Oh.ba()-(c.hf()+c.Bg());e.ph(e.$(),Math.max(g,
0));this.nha(c,e);0<h&&(h>b.Oh.$()&&(e=h-b.Oh.$(),e>b.Nra&&(b.Nra=e)),b.Oh.RZ(-h,0));break;case a.eh.tA:e.Lb(b.Oh.O()+c.mf(),b.Oh.M()+c.hf()),g=b.Oh.$()-(c.mf()+c.pg()),h=b.Oh.ba()-(c.hf()+c.Bg()),e.ph(Math.max(g,0),Math.max(h,0)),this.nha(c,e)}};h.dhb=function(b,c){var e=this.n2(b);if(e){if(e.PO()==a.eh.l8||e.PO()==a.eh.i8)c[0]=!0;if(e.PO()==a.eh.G1||e.PO()==a.eh.j8)c[1]=!0}};e.gd(c.Xka,"PRIM_ATLM",{Wa:{MarginTop:{f:h.hf,i:function(a){this.bf(e.aa(a))}},MarginBottom:{f:h.Bg,i:function(a){this.If(e.aa(a))}},
MarginLeft:{f:h.mf,i:function(a){this.Ne(e.aa(a))}},MarginRight:{f:h.pg,i:function(a){this.Ie(e.aa(a))}},MaxHeight:{f:h.HJa,i:function(a){this.$za(e.aa(a))}},MaxWidth:{f:h.JJa,i:function(a){this.rca(e.aa(a))}},MinHeight:{f:h.KJa,i:function(a){this.bAa(e.aa(a))}},MinWidth:{f:h.LJa,i:function(a){this.tca(e.aa(a))}},ProcessingOrder:{f:function(){return e.Ja(this.JEa,a.TP.G)},i:function(b){this.fYc(e.Ba(b,a.TP.G))}}}})});window.LANSA.addSrc("atli",function(e,c,a,b){a.eh={Vwb:0,l8:1,i8:2,G1:3,j8:4,tA:5,Hhc:6};a.eh.G={NONE:a.eh.Vwb,TOP:a.eh.l8,BOTTOM:a.eh.i8,LEFT:a.eh.G1,RIGHT:a.eh.j8,CENTER:a.eh.tA,EO:a.eh.Hhc};a.Jhc={mha:0};c.IMa=function(){h.w.call(this);this.QR=0;this.W5=a.eh.Vwb;this.JQ=a.Jhc.mha};var h=c.u(c.IMa,c.Kxa);b.Wka=function(a,b,e){var g=new c.IMa;g.Ia(a);g.qi(b);g.G4(e);return g};h.U=function(){h.j.U.call(this)};h.M5a=function(){return a.cxa.pqb};h.PO=function(){return this.W5};h.G4=function(b){this.W5!=
b&&(this.W5=b,this.l(a.a.g))};h.$pd=function(){return this.QR};h.gGd=function(b){0>b?b=0:100<b&&(b=100);this.QR!=b&&(this.QR=b,this.l(a.a.g))};h.t9a=function(b){var c=!1;if(null!=this.Xa&&this.Xa.Z()===b)if(this.Xa.qd()){if(this.Xa.up()||this.W5==a.eh.tA)c=!0}else this.Xa.up()&&(c=!0);return c};h.dMb=function(a,b,c){this.Ia(a);this.qi(b);this.G4(c)};e.gd(c.IMa,"PRIM_ATLI",{Wa:{MarginTop:{f:h.hf,i:function(a){this.bf(e.aa(a))}},MarginBottom:{f:h.Bg,i:function(a){this.If(e.aa(a))}},MarginLeft:{f:h.mf,
i:function(a){this.Ne(e.aa(a))}},MarginRight:{f:h.pg,i:function(a){this.Ie(e.aa(a))}},MaxHeight:{f:h.HJa,i:function(a){this.$za(e.aa(a))}},MaxWidth:{f:h.JJa,i:function(a){this.rca(e.aa(a))}},MinHeight:{f:h.KJa,i:function(a){this.bAa(e.aa(a))}},MinWidth:{f:h.LJa,i:function(a){this.tca(e.aa(a))}},Manage:{f:h.Ca,i:h.qi},Parent:{f:h.Z,i:h.Ia},Attachment:{f:function(){return e.Ja(this.PO(),a.eh.G)},i:function(b){this.G4(e.Ba(b,a.eh.G))}}}})});
