window.LANSA.addSrc("coll",function(e,c,a,b,h){a.zLa={Ric:0,E3a:1};var t=0;c.Mka=function(){p.w.call(this)};var p=c.u(c.Mka,c.pd);p.twb=function(){return!1};p.iNb=function(){return!1};p.Dc=function(){return 0};p.dg=function(){return 0==this.Dc()};p.wW=function(a){a&&(a.ua(),a.Yec(this))};p.OW=function(a){a&&(a.Ab(),a.wPc(this))};p.dZ=function(a,b){this.kOa(b);null!=this.GR&&this.GR.dZ(a,b)};p.q4=function(a,b){this.lOa(b);null!=this.GR&&this.GR.q4(a,b)};e.gd(c.Mka,"PRIM_COLL",{Wa:{AllowsDuplicates:{f:function(){return this.twb()}},
IsEmpty:{f:function(){return this.dg()}},IsOrdered:{f:function(){return this.iNb()}},ItemCount:{f:function(){return this.Dc()}}}});c.wMa=function(){r.w.call(this);this.eb=[];this.GR=null};var r=c.u(c.wMa,c.Mka);r.U=function(){this.ak();r.j.U.call(this)};r.twb=function(){return!0};r.iNb=function(){return!0};r.Dc=function(){return this.eb.length};r.Ce=function(a){if(0>a||a>=this.eb.length)throw e.GD(a,this.eb.length);return this.eb[a]};r.Rs=function(a,b){if(0>a||a>this.eb.length)throw e.GD(a,this.eb.length);
a==this.eb.length?this.Is(b):this.zhb(b,a)};r.y5a=function(a,b){return b===h?this.eb.indexOf(a):this.eb.indexOf(a,b)};r.lIb=function(a){return this.eb.lastIndexOf(a)+1};r.r5a=function(){return 0<this.eb.length?this.eb[0]:null};r.K5a=function(){return 0<this.eb.length?this.eb[this.eb.length-1]:null};r.mkd=function(){return this.Fea};r.tZ=function(a){this.Fea=a};r.YFa=function(a){this.tZ(a.G1b())};r.Ud=function(a){return-1!=this.eb.indexOf(a)};r.Is=r.gMb=function(a){this.wW(a);this.eb.push(a);this.dZ(a,
this.Dc()-1)};r.fMb=function(a){this.wW(a);this.eb.unshift(a);this.dZ(a,0)};r.eMb=function(a,b){if(0>b||b>=this.eb.length)throw e.GD(b,this.eb.length);this.wW(a);this.eb.splice(b+1,0,a);this.dZ(a,b+1)};r.c9a=function(a,b){if(0>b||b>=this.eb.length)throw e.GD(b,this.eb.length);this.wW(a);this.eb.splice(b,0,a);this.dZ(a,b)};r.Mr=function(a){a=this.eb.indexOf(a);if(-1==a)throw e.XPc();return this.Nr(a)};r.Nr=function(a){if(0>a||a>=this.eb.length)throw e.GD(a,this.eb.length);var b=this.eb[a];this.eb.splice(a,
1);e.pha(b);this.OW(b);this.q4(b,a);return b};r.uhb=function(){return this.Nr(0)};r.whb=function(){return this.Nr(this.eb.length-1)};r.ak=function(){for(var a=0;a<this.eb.length;a++)this.OW(this.eb[a]);this.eb=[];this.Bba()};r.Gfb=function(a){for(var b=0,c=0;c<this.eb.length;c++)this.eb[c]===a&&b++;return b};r.zhb=function(a,b){if(0>b||b>=this.eb.length)throw e.GD(b,this.eb.length);var c=this.eb[b];e.pha(c);this.OW(c);this.eb[b]=a;this.wW(a);return c};r.ng=function(){var a=e.q1a(this.Fea);if(a=e.re(a.YNa,
a.Uob))this.sla(a),this.Is(a)};r.mj=function(){this.ak()};r.Th=function(a){if(0<=a&&a<this.Dc()){var b=this.Ce(a);b&&this.dba(b);this.Dk=a;return"OK"}this.Dk=-1;return"NR"};r.vn=function(){return this.Dc()};r.Zl=function(a){a===h&&(a=this.Dk);0<=a&&a<this.Dc()&&this.Nr(a)};r.zk=function(){var a=this.Dk;0<=a&&a<this.Dc()&&(a=this.Ce(a))&&this.sla(a)};r.Gl=function(a,b,c){for(var d=0;d<this.Dc();d++){var e=this.Ce(d);if(e&&(e=e.SX())){var f={},g;for(g in e)f[g]=e[g].get();if(a(f))return null!=b&&b.set(d+
1),c&&this.Th(d),this.Dk=d,"OK"}}return"NR"};r.sp=function(a){this.ak();for(var b=0;b<a;b++)this.ng()};r.Zq=function(){return new c.Ecb(this)};r.Rhb=function(){null==this.GR&&(this.GR=new c.ZTb);return this.GR};c.ZTb=function(){g.w.call(this)};var g=c.u(c.ZTb,c.Fcb);c.UTb=function(){l.w.call(this);this.Dk=-1};var l=c.u(c.UTb,c.wMa);l.ZS=function(){return"PRIM_LCOL<"+this.Fea+">"};l.Efc=function(a){for(var b=0;b<a.Dc();b++)this.Is(a.Ce(b))};l.djc=function(a){for(var b=e.re("PRIM_LCOL"),c=0;c<this.Dc();c++)b.Is(this.Ce(c));
for(c=0;c<a.Dc();c++)b.Is(a.Ce(c));e.pha(b);return b};e.gd(c.UTb,"PRIM_LCOL",{rB:a.Br.D_a,Wa:{First:{f:function(){return this.r5a()}},Last:{f:function(){return this.K5a()}},Item:{f:function(a){return this.Ce(e.aa(a)-1)},i:function(a,b){this.Rs(e.aa(a)-1,b)}},IndexOf:{f:function(a,b){return this.y5a(a,b===h?h:e.aa(b)-1)+1}},LastIndexOf:{f:l.lIb},Collects:{i:l.tZ}},Gc:{Append:l.Efc,Concatenate:l.djc,Contains:l.Ud,Insert:l.Is,InsertFirst:l.fMb,InsertLast:l.gMb,InsertAfter:function(a,b){return this.eMb(a,
e.aa(b)-1)},InsertBefore:function(a,b){return this.c9a(a,e.aa(b)-1)},Remove:l.Mr,RemoveAt:function(a){return this.Nr(e.aa(a)-1)},RemoveFirst:l.uhb,RemoveLast:l.whb,RemoveAll:l.ak,OccurrencesOf:l.Gfb,ReplaceAt:function(a,b){return this.zhb(a,e.aa(b)-1)}},qg:{vg:"Item"},oq:{zaa:function(a){var b=e.re("PRIM_NMBR");b.set(a);return b},wp:function(a){return this.Ce(e.aa(a)-1)},Lw:function(){return this.Dc()}},Pw:{ng:l.ng,Th:function(a){return this.Th(e.aa(a)-1)},sp:l.sp,mj:l.mj,vn:l.vn,Zl:function(a){return this.Zl(a?
e.aa(a)-1:h)},zk:l.zk,Gl:l.Gl,Zq:l.Zq}});c.mQb=function(){s.w.call(this)};var s=c.u(c.mQb,c.wMa);s.ZS=function(){return"PRIM_ACOL<"+this.Fea+">"};e.gd(c.mQb,"PRIM_ACOL",{rB:a.Br.D_a,Wa:{First:{f:function(){return this.r5a()}},Last:{f:function(){return this.K5a()}},Item:{f:function(a){return this.Ce(e.aa(a)-1)},i:function(a,b){this.Rs(e.aa(a)-1,b)}},IndexOf:{f:function(a,b){return this.y5a(a,b===h?h:e.aa(b)-1)+1}},LastIndexOf:{f:s.lIb},Collects:{i:s.tZ}},Gc:{Contains:s.Ud,Insert:s.Is,InsertFirst:s.fMb,
InsertLast:s.gMb,InsertAfter:function(a,b){return this.eMb(a,e.aa(b)-1)},InsertBefore:function(a,b){return this.c9a(a,e.aa(b)-1)},Remove:s.Mr,RemoveAt:function(a){return this.Nr(e.aa(a)-1)},RemoveFirst:s.uhb,RemoveLast:s.whb,RemoveAll:s.ak,OccurrencesOf:s.Gfb,ReplaceAt:function(a,b){return this.zhb(a,e.aa(b)-1)}},qg:{vg:"Item"},oq:{zaa:function(a){var b=e.re("PRIM_NMBR");b.set(a);return b},wp:function(a){return this.Ce(e.aa(a)-1)},Lw:function(){return this.Dc()}},Pw:{ng:s.ng,Th:function(a){return this.Th(e.aa(a)-
1)},sp:s.sp,mj:s.mj,vn:s.vn,Zl:function(a){return this.Zl(a?e.aa(a)-1:h)},zk:s.zk,Gl:s.Gl,Zq:s.Zq}});c.fUb=function(){f.w.call(this)};var f=c.u(c.fUb,c.wMa);f.Is=function(b){this.wW(b);for(var c=0,d=this.eb.length-1;c<=d;){var e=Math.floor((c+d)/2);this.Irc(b,this.eb[e])==a.dd.zl?d=e-1:c=e+1}this.eb.splice(c,0,b)};f.Irc=function(b,c){var d=a.dd.Tj,f=e.Tb();f.Zb("SUBJECT",b);f.Zb("OBJECT",c);f.WN("RESULT",d,a.dd.G);this.za(a.K.zGa,f);d=f.m5a("RESULT",a.dd.G);f.qc();return d};e.gd(c.fUb,"PRIM_SACO",
{Wa:{First:{f:function(){return this.r5a()}},Last:{f:function(){return this.K5a()}},Item:{f:function(a){return this.Ce(e.aa(a)-1)},i:function(a,b){this.Rs(e.aa(a)-1,b)}},IndexOf:{f:function(a,b){return this.y5a(a,b===h?h:e.aa(b)-1)+1}},Collects:{i:f.tZ}},Gc:{Remove:f.Mr,RemoveAt:function(a){return this.Nr(e.aa(a)-1)},RemoveAll:f.ak,RemoveLast:f.whb,RemoveFirst:f.uhb,Contains:f.Ud,OccurrencesOf:f.Gfb,Insert:f.Is},qg:{vg:"Item"},oq:{zaa:function(a){var b=e.re("PRIM_NMBR");b.set(a);return b},wp:function(a){return this.Ce(e.aa(a)-
1)},Lw:function(){return this.Dc()}}});c.KY=function(a){d.w.call(this);this.Scc=a};var d=c.u(c.KY,c.Mka);d.Ce=function(a){if(0>a||a>=this.Dc())throw e.GD(a,this.Dc());return this.Fw(a)};d.Dc=function(){return this.Scc.Dc()};d.Fw=function(a){return this.Scc.Fw(a)};e.gd(c.KY,"PRIM_PCOL",{Wa:{Item:{f:function(a){return this.Ce(e.aa(a)-1)},i:function(a,b){this.Rs(e.aa(a)-1,b)}}},qg:{vg:"Item"},oq:{wp:function(a){return this.Fw(e.aa(a)-1)},Lw:function(){return this.Dc()}}});c.TTb=function(){w.w.call(this);
this.eb={};this.AR=null;this.Oe=a.zLa.E3a};var w=c.u(c.TTb,c.Mka);w.U=function(){this.ak();w.j.U.call(this)};w.ZS=function(){return"PRIM_KCOL<"+this.nUa+" "+this.Rwc()+">"};w.Xf=function(){return this.Oe};w.Cb=function(a){this.Oe=a};w.Dc=function(){return this.lba().length};w.Ce=function(b){b=this.$_a(b);if(this.eb[b]===h&&this.Oe==a.zLa.E3a){var c=null;this.Brb?c=new this.Brb:this.nUa&&(c=e.q1a(this.nUa),c=e.re(c.YNa,c.Uob));c&&(this.eb[b]=c,this.wW(c),this.ZF())}return this.eb[b]};w.Rs=function(a,
b){a=this.$_a(a);var c=a.toString();this.eb[c]===h?this.ZF():this.OW(this.eb[c]);this.wW(b);this.eb[c]=b};w.Fw=function(a){a=this.lba()[a];return this.eb[a]};w.F5a=function(a){a=this.lba()[a];this.AR.set(a);return this.AR};w.G5a=function(a){for(var b in this.eb)if(this.eb[b]===a)return this.c0a(b);return this.AR.lyc()};w.tZ=function(a,b){"string"!==typeof a?this.Brb=a:(this.nUa=a,this.Brb=b)};w.YPa=function(a){this.AR=new a;this.AR.ua()};w.nkd=function(){return this.nUa};w.Rwc=function(){var a="";
this.AR&&(a=this.AR.iua());return a};w.YFa=function(a){this.tZ(a.G1b(),a.cyb(0));this.YPa(a.cyb(1))};w.$_a=function(a){this.AR.set(a);a=this.AR.get();return a.toString()};w.c0a=function(a){this.AR.set(a);return this.AR.get()};w.Mr=function(a){a=this.$_a(a);var b=null;this.eb[a]!==h&&(b=this.eb[a],e.pha(b),this.OW(b),delete this.eb[a],this.ZF(),this.q4(b,0));return b};w.ak=function(){for(var a in this.eb)this.OW(this.eb[a]);this.eb={};this.ZF();this.Bba()};w.ZF=function(){delete this.AE};w.lba=function(){var a=
this;if(this.AE===h){this.AE=[];for(var b in this.eb)this.AE.push(b);this.AE.sort(function(b,c){b=a.c0a(b);c=a.c0a(c);return e.cmp(b,c)})}return this.AE};var u={COLLECTION:a.zLa.Ric,FACTORY:a.zLa.E3a};e.gd(c.TTb,"PRIM_KCOL",{Wa:{Style:{f:function(){return e.Ja(this.Xf(),u)},i:function(a){this.Cb(e.Ba(a,u))}},Item:{f:function(a){return this.Ce(a)},i:function(a,b){this.Rs(a,b)},Px:"na"},Collects:{i:w.tZ},KeyedBy:{i:w.YPa},KeyOf:{f:function(a){return this.G5a(a)},Px:"na"}},Gc:{Remove:w.Mr,RemoveAll:w.ak},
qg:{vg:"Item"},oq:{zaa:function(a){return this.F5a(e.aa(a)-1)},wp:function(a){return this.Fw(e.aa(a)-1)},Lw:function(){return this.Dc()}}});c.jTb=function(){G.w.call(this);this.uR=(t++).toString();this.SG=[];this.Fea=this.Acc=""};var G=c.u(c.jTb,c.Mka);G.ZS=function(){return"PRIM_DCOL<"+this.Fea+" "+this.Acc+">"};G.Dc=function(){return this.SG.length};G.Fw=function(a){return this.SG[a].AG[this.uR]};G.Ce=function(a){return a.AG===h||a.AG[this.uR]===h?null:a.AG[this.uR]};G.Rs=function(a,b){a.AG===h&&
(a.AG={});var c=a.AG[this.uR];c===h?(this.SG.push(a),a.ua()):this.OW(c);a.AG[this.uR]=b;this.wW(b)};G.F5a=function(a){return this.SG[a]};G.tZ=function(a){this.Fea=a};G.YPa=function(a){this.Acc=a};G.G5a=function(a,b){for(var c=b;c<this.SG.length;c++){var d=this.SG[c];if(d.AG[this.uR]===a)return d}return null};G.rrc=function(a){return this.Ce(a)};G.Ud=function(a){return-1!=this.SG.indexOf(a)};G.ijc=function(a){for(var b=0;b<this.SG.length;b++)if(this.SG[b].AG[this.uR]===a)return!0;return!1};G.Is=function(a,
b){var c=this.Ce(b);this.Rs(b,a);return c};G.Mr=function(a){if(a.AG!==h){var b=a.AG[this.uR];if(b!==h)return delete a.AG[this.uR],this.SG.splice(this.SG.indexOf(a),1),e.pha(b),this.OW(b),a.Ab(),this.q4(b,0),b}return null};G.ak=function(){for(var a=0;a<this.SG.length;a++){var b=this.SG[a],c=b.AG[this.uR];c!==h&&(delete b.AG[this.uR],this.OW(c))}this.SG=[];this.Bba()};e.gd(c.jTb,"PRIM_DCOL",{Wa:{Item:{f:function(a){return this.Ce(a)},i:function(a,b){this.Rs(a,b)},Px:"na"},Collects:{i:G.tZ,Px:"na"},
KeyedBy:{i:G.YPa,Px:"na"},KeyOf:{f:function(a,b){return this.G5a(a,b!==h?e.aa(b)-1:0)},Px:"na"}},Gc:{Contains:G.Ud,ContainsItem:G.ijc,Insert:G.Is,Remove:G.Mr,RemoveAll:G.ak,Find:G.rrc},qg:{vg:"Item"},oq:{zaa:function(a){return this.F5a(e.aa(a)-1)},wp:function(a){return this.Fw(e.aa(a)-1)},Lw:function(){return this.Dc()}}})});
