window.LANSA.addSrc("labl",function(e,c,a,b){a.Vpb={SKd:0,Zpb:16};a.AY={YIc:1,gbb:1,fbb:2,dQb:240};a.cbb={qNa:0,zZb:1};c.Kr=function(){h.w.call(this);this.$u=a.tn.f9;this.BR=a.AY.YIc;this.Lfa=a.cbb.qNa;this.Rz=this.hA=this.dA=this.oA=0;this.Pj=null;this.TM=a.Mj.iU;this.ta=null;this.nu=0;this.GV=a.og.nQ;this.B0=new c.ja;this.dH=new c.ja;this.Lc=this.Lc|a.Sb.Aaa|a.Sb.Kwa|a.Sb.cab|a.Sb.sD|a.Sb.CP|a.Sb.dab|a.Sb.gB;this.yh=this.yh|a.ji.ska|a.ji.BP|a.ji.uY;this.cf(!1);this.ana(!1)};var h=c.u(c.Kr,c.Pt);
h.U=function(){this.Pj&&(this.Pj.va(this,this.T1a),this.Pj=null);h.j.U.call(this);this.bd(null)};h.Cg=function(){return c.leb};h.Cz=function(c){this.Pj!=c&&(this.Pj&&this.Pj.va(this,this.T1a),this.Pj=c,null==this.Pj?this.ana(!1):(this.ana(!0),this.Pj.ya(this,this.T1a)),this.l(a.a.g),b.Ra().oc(this,!1))};h.TC=function(){return this.Pj};h.cg=function(){return 0!=(this.BR&a.AY.gbb)?!0:!1};h.Yx=function(){return!this.Wm()&&this.cg()};h.vh=function(c){c=this.BR&~a.AY.gbb|(c?a.AY.gbb:0);this.BR!=c&&(this.BR=
c,this.Gd(),b.Ra().oc(this,!1),this.fa(a.a.g))};h.gKa=function(){return 0!=(this.BR&a.AY.fbb)?!0:!1};h.o5b=function(b){b=this.BR&~a.AY.fbb|(b?a.AY.fbb:0);this.BR!=b&&(this.BR=b,this.Mg(),this.fa(a.a.g))};h.lHd=function(c){this.DKa()!=c&&(this.BR=this.BR&~a.AY.dQb|c,this.Gd(),b.Ra().oc(this,!1),this.fa(a.a.g))};h.DKa=function(){return this.BR&a.AY.dQb};h.xk=function(c){this.$u!=c&&(this.$u=c,b.Ra().oc(this,!1),this.fa(a.a.g))};h.Vj=function(){return this.$u};h.hf=function(){return this.oA};h.bf=function(c){this.oA!=
c&&(this.oA=c,this.Gd(),b.Ra().oc(this,!1),this.fa(a.a.g))};h.mf=function(){return this.dA};h.Ne=function(c){this.dA!=c&&(this.dA=c,this.Gd(),b.Ra().oc(this,!1),this.fa(a.a.g))};h.pg=function(){return this.hA};h.Ie=function(c){this.hA!=c&&(this.hA=c,this.Gd(),b.Ra().oc(this,!1),this.fa(a.a.g))};h.Bg=function(){return this.Rz};h.If=function(c){this.Rz!=c&&(this.Rz=c,this.Gd(),b.Ra().oc(this,!1),this.fa(a.a.g))};h.Tr=function(c){this.TM!=c&&(this.TM=c,b.Ra().oc(this),this.l(a.a.g))};h.Ic=function(){return this.ta};
h.bd=function(c){this.ta!=c&&(null!=this.ta&&(this.ta.va(this,this.$l),this.ta.Ab()),this.ta=c,null!=this.ta&&(this.ta.ua(),this.ta.ya(this,this.$l)),this.Gd(),b.Ra().oc(this),this.l(a.a.g))};h.Ft=function(){return this.TM};h.Av=function(){return this.nu};h.Wt=function(c){c!=this.nu&&(this.nu=c,this.Gd(),this.fa(a.a.g),b.Ra().oc(this))};h.RK=function(){return this.GV};h.OI=function(b){this.GV!=b&&(this.GV=b,this.Gd(),this.l(a.a.g))};h.Cl=function(){var b=a.ie.DD;switch(this.Tg()){case a.Ig.sA:switch(this.UX()){case a.xh.Gq:b=
a.ie.DD;break;case a.xh.DQ:b=a.ie.$Na;break;default:b=a.ie.bOa}break;case a.Ig.nK:switch(this.UX()){case a.xh.Gq:b=a.ie.aOa;break;case a.xh.DQ:b=a.ie.e0b;break;default:b=a.ie.g0b}break;default:switch(this.UX()){case a.xh.Gq:b=a.ie.YY;break;case a.xh.DQ:b=a.ie.d0b;break;default:b=a.ie.ZY}}return b};h.eB=function(){return 0!=(this.Lfa&a.cbb.zZb)};h.Hvd=function(a){this.Lfa|=a};h.gGc=function(a){this.Lfa&=~a};h.Ivd=function(a,b){this.Lfa=this.Lfa&~a|(b?a:0)};h.zd=function(a,b,c){h.j.zd.call(this,a,b,
c);this.Vo(!1)};h.jU=function(a){h.j.jU.call(this,a);this.Vo(a)};h.Vo=function(a){h.j.Vo.call(this,a);a=this.ye();this.ZCb(a,!1)};h.Ki=function(){h.j.Ki.call(this);this.yd(a.R.Mv);this.yd(a.R.zka)};h.ad=function(){this.gH(a.Sb.sL,this.mL());h.j.ad.call(this)};h.Gn=function(a){null!=this.Pj?this.Pj.ze():h.j.Gn.call(this,a)};h.Xi=function(){this.bZ();b.Ra().Ry(this)};h.iy=function(){this.bO()};h.FD=function(a){var b=!1,b=a.De().GOa(this,this.ga.di,this.I$a(),this.K$a(),this.J$a(),a);!1==b&&h.j.FD.call(this,
a)};h.ae=function(b){""==b[1]&&(b[1]=a.sPb);h.j.ae.call(this,b)};h.ZCb=function(a,e){var g=b.sc(a),l=b.sc(g),h=null,f=0<this.nu?this.nu:-1;this.ta&&(h=this.ta.tyb(g.ba()-4,g.ba()-4));g.Ta(g.M()+this.oA);g.Qa(g.O()+this.dA);g.Oa(g.na-this.hA);g.Aa(g.pa-this.Rz);var d=this.Kb(),w=new c.ja,u=new c.ja,G=[],k="";G[0]=w;G[1]=l;G[2]=u;G[3]=f;G[4]=f;G[5]=0;this.rza(null,h,d,this.Pd(),g,G);w=G[0];l=G[1];g=G[5];this.ta&&this.ta instanceof c.xL&&(k=this.ta.hh());this.B0=w;this.dH=l;e||(h=this.Ma().ib(),f=this.Yx(),
b.Kd[h].hg(h,l,k,w,f,this.gKa(),g))};h.rza=function(e,h,g,l,s,f){e=f[0];var d=f[1],w=f[2],u=f[3],G=f[4],k=f[5],d=b.sc(s);if(null!=h&&this.qd()){var n=a.zf.NAa;this.TC()||(n|=a.zf.zRa);k=n;if(this.Yx())switch(this.DKa()){case a.Vpb.Zpb:n|=a.zf.$D;break;default:n|=a.zf.$D,k|=a.zf.$D}else k|=this.$u;switch(this.Tg()){case a.Ig.sA:k|=a.zf.bda;break;case a.Ig.nK:k|=a.zf.PAa;break;default:k|=a.zf.Tmb}b.nxa(h,g,l,s,0,this.Cl(),this.Cl(),this.Ft(),e,d,w,0,this.qd()?0:2,u,G,n)}else if(k=this.yxb(d),0<g.length){d.$()>
s.$()&&(this.Yx()?this.DKa()==a.Vpb.Zpb&&(d=new c.ja(0,0,s.$(),d.ba())):d=new c.ja(0,0,s.$(),d.ba()));switch(this.Tg()){case a.Ig.sA:d=new c.ja(s.O()+(s.$()-d.$())/2,1,d.$(),d.ba());k|=a.zf.bda;break;case a.Ig.nK:d=new c.ja(s.na-d.$(),1,d.$(),d.ba());k|=a.zf.PAa;break;default:d=new c.ja(s.O(),1,d.$()+1,d.ba()),k|=a.zf.Tmb}switch(this.UX()){case a.xh.Gq:d=new c.ja(d.O(),s.M()+(s.ba()-d.ba())/2,d.$(),d.ba());break;case a.xh.DQ:d=new c.ja(d.O(),s.pa-1-d.ba(),d.$(),d.ba())}}f[0]=e;f[1]=d;f[2]=w;f[3]=
u;f[4]=G;f[5]=k};h.yxb=function(c){var e=this.Pd(),g=a.zf.NAa,l=this.Kb();if(0<l.length)if(this.TC()||(g|=a.zf.zRa),this.ds=b.AD(l,e,this.Yx(),c.$(),c.ba()),this.Yx())switch(this.DKa()){case a.Vpb.Zpb:b.ey(l,c,g|a.zf.$D,e);break;default:b.ey(l,c,g|a.zf.$D,e),g|=a.zf.$D}else b.ey(l,c,g,e),g|=this.$u;return g};h.Bic=function(){var a=b.IP();this.Tk(!1,!0);this.yxb(a);this.hc(a.$())};h.oB=function(c){if(this.gKa())switch(b.Qo(c)){case a.W.Cma:case a.W.a3b:case a.W.j3b:case a.W.Tba:case a.W.k3b:case a.W.QRc:case a.W.uTc:case a.W.e3b:case a.W.BTc:case a.W.gib:c.bk(!0);
return}h.j.oB.call(this)};h.zI=function(a){var b=this.Wm(),c=this.nq();(b||c)&&this.d1b(a,b,c)};h.d1b=function(a,e,g){var l=new c.ja,h=new c.ja(0,0,1E4,1E4);this.Yx()&&h.Oa(h.O()+a.$()-(this.ga.pk()+this.ga.Al()));this.ZCb(h,!0);""==this.Kb()&&this.B0.dg()||(""==this.Kb()?l=this.B0:(l=b.sc(this.dH),l.Aa(l.pa+(0<this.dH.ba()?1:0)),l=l.t_(this.B0)));e&&a.Oa(a.O()+this.ga.pk()+this.dA+l.$()+this.hA+this.ga.Al());g&&a.Aa(a.M()+this.ga.dl()+this.oA+l.ba()+this.Rz+this.ga.Am())};h.Lya=function(a,b){h.j.Lya(a,
b);b[0]&&this.gKa()&&(b[0]=!1)};h.Gh=function(a){b.Xcb();return h.j.Gh.call(this,a)};h.$l=function(c,e){switch(e.Ya){case a.a.ub:case a.a.Vb:e.Ph==this.ta&&this.bd(null);break;case a.a.g:e.Ph==this.ta&&(b.Ra().oc(this),this.Gd())}};h.T1a=function(b,c){c.Ya==a.a.Vb&&this.Cz(null)};h.Cr=h[a.R.uD]=function(a){h.j.Cr.call(this,a);b.Ra().oc(this,!1)};h.Kfd=h[a.R.zka]=function(){b.Ra().oc(this,!1)};h.FC=h[a.R.Mv]=function(){b.Ra().oc(this,!1)};h.bia=h[a.R.$wa]=function(a){this.lz()?this.cf(!1):h.j.bia.call(this,
a)};h.rO=h[a.R.tL]=function(){this.Pj&&this.Pj.ze()};h.zt=h[a.R.Lv]=function(b){this.eB()&&(this.Hn(),this.gGc(a.cbb.zZb));h.j.zt.call(this,b)};e.gd(c.Kr,"PRIM_LABL",{Wa:{Ellipses:{f:function(){return e.Ja(this.Vj(),a.tn.G)},i:function(b){this.xk(e.Ba(b,a.tn.G))}},Caption:{f:h.Kb,i:function(a){this.bc(e.ma(a))}},Alignment:{f:function(){return e.Ja(this.Tg(),a.Ig.G)},i:function(b){this.Qb(e.Ba(b,a.Ig.G))}},VerticalAlignment:{f:function(){return e.Ja(this.UX(),a.xh.G)},i:function(b){this.Mn(e.Ba(b,
a.xh.G))}},FocusControl:{f:h.TC,i:h.Cz},WordWrap:{f:h.cg,i:function(a){this.vh(e.Ha(a))}},Selectable:{f:h.gKa,i:function(a){this.o5b(e.Ha(a))}},MarginLeft:{f:h.mf,i:function(a){this.Ne(e.aa(a))}},MarginTop:{f:h.hf,i:function(a){this.bf(e.aa(a))}},MarginBottom:{f:h.Bg,i:function(a){this.If(e.aa(a))}},MarginRight:{f:h.pg,i:function(a){this.Ie(e.aa(a))}},Image:{f:h.Ic,i:h.bd},ImagePosition:{f:function(){return e.Ja(this.Ft(),a.Mj.G)},i:function(b){this.Tr(e.Ba(b,a.Mj.G))}},ImageHeight:{f:h.Av,i:function(a){this.Wt(e.aa(a))}},
ImageSizing:{f:function(){return e.Ja(this.RK(),a.og.G)},i:function(b){this.OI(e.Ba(b,a.og.G))}}},qg:{vg:"Caption"}});c.leb=function(a){t.w.call(this,a);this.wUa=this.nu=this.QDa=this.htb=this.gtb=this.ta=this.RE=this.Jga=this.fC=this.pvb=this.ovb=this.nvb=this.pb=null};var t=c.u(c.leb,c.kl);t.Kb=function(){return this.pb.textContent};t.bc=function(a){this.pb.textContent=a};t.r$=function(){return this.pb};t.dT=function(){return this.pb};t.hg=function(b,c,g,l,h,f,d){null==this.ta.parentElement&&this.v.appendChild(this.ta);
if(null==this.wUa||this.wUa!=f)this.wUa=f,this.pb.spellcheck=!1,this.pb.setAttribute("contenteditable",f);this.ta.style.backgroundImage=e.lv(g);switch(this.la.RK()){case a.og.nQ:this.ta.style.backgroundSize="contain";break;case a.og.dRa:this.ta.style.backgroundSize="cover";break;case a.og.Kf:this.ta.style.backgroundSize="100% 100%";break;case a.og.$d:this.ta.style.backgroundSize="auto"}if(null==this.RE||this.RE!=h)this.RE=h,this.pb.style.whiteSpace=h?"pre-wrap":"pre";if(null==this.Jga||this.Jga!=
d)this.Jga=d,this.pb.style.textAlign=0!=(d&a.zf.PAa)?"right":0!=(d&a.zf.bda)?"center":"",0!=(d&a.zf.MAa)||0!=(d&a.zf.OAa)||0!=(d&a.zf.RAa)?(this.pb.style.textOverflow="ellipsis",this.pb.style.overflow="hidden"):(this.pb.style.textOverflow="clip",this.pb.style.overflow="visible");if(null==this.nvb||this.nvb!=c.O())this.nvb=c.O(),this.pb.style.left=c.O()+"px";if(null==this.ovb||this.ovb!=c.M())this.ovb=c.M(),this.pb.style.top=c.M()+"px";if(null==this.fC||this.fC!=c.ba())this.fC=c.ba(),this.pb.style.height=
c.ba()+"px";if(null==this.pvb||this.pvb!=c.$())this.pvb=c.$(),this.pb.style.width=c.$()+"px";if(null==this.gtb||this.gtb!=l.O())this.gtb=l.O(),this.ta.style.left=l.O()+"px";if(null==this.htb||this.htb!=l.M())this.htb=l.M(),this.ta.style.top=l.M()+"px";if(null==this.nu||this.nu!=l.ba())this.nu=l.ba(),this.ta.style.height=l.ba()+"px";if(null==this.QDa||this.QDa!=l.$())this.QDa=l.$(),this.ta.style.width=l.$()+"px"};t.Ve=function(a,b){this.v=document.createElement("div");this.v.setAttribute("LANSAHandle",
this.fc);this.pb=document.createElement("div");var c=this.pb.style;c.position="absolute";c.outline="none";c.overflowX="hidden";c.overflowY="hidden";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.borderLeftWidth="0px";c.borderTopWidth="0px";c.borderRightWidth="0px";c.borderBottomWidth="0px";c.cursor="inherit";c.textDecoration="inherit";this.ta=document.createElement("div");c=this.ta.style;c.position="absolute";c.backgroundSize="contain";
c.backgroundPosition="center center";c.backgroundRepeat="no-repeat";this.v.appendChild(this.pb);this.v.appendChild(this.ta);return t.j.Ve.call(this,a,b)};t.xW=function(){var a=this;this.E1();a.pb.addEventListener("paste",function(b){a.xba(b);b.preventDefault()},!1)};t.ipb=function(){var a="";t.j.ipb.call(this);"rgba(0,0,0,0)"==this.WTa&&""!=this.v.style.boxShadow&&(a=this.v.style.boxShadow);this.pb.style.textShadow=a};t.LL=function(a){t.j.LL.call(this,a);return!this.wUa};t.xba=function(){}});
