window.LANSA.addSrc("hint",function(e,c,a,b,h){function t(a){this.lu=a;this.sad=!1;this.pcc=new c.ja(0,0,0,0)}function p(a){this.lu=a;this.yYa=this.pb="";this.nd=null}e.Bb("PRIM_PPNL");e.gd(function(){},"PRIM_HINT",{});c.oYb=function(a){r.w.call(this);this.lu=a;this.$sb=this.N0=this.Zi=this.Zz=this.mu=this.RV=null;a=b.yL();e.Bb("PRIM_PANL");e.Bb("PRIM_LABL");this.RV=new c.hm;this.RV.Ia(this);this.RV.mb(new c.ja(0,0,0,0));this.mu=new c.Kr;this.Zz=new c.Kr;this.mu.Ia(this.RV);this.Zz.Ia(this.RV);this.$sb=
new c.tb;this.$sb.sB(!0);this.N0=new c.tb;this.N0.sd(b.Q().G_);this.N0.Jn(0);this.N0.$m(0);this.N0.lm(0);this.N0.Kl(0);this.N0.Qr(a);this.RV.io(this.N0);this.Zz.io(this.$sb)};var r=c.u(c.oYb,c.Sw);r.Pd=function(){return this.RV.Pd()};r.JQa=function(c,e,f){this.N0.sd(b.Q().G_);c.O();c.M();this.hc(c.$()+4);this.Jc(c.ba()+4);this.RV.hc(c.$());this.RV.Jc(c.ba());this.Zz.hc(c.$());this.Zz.Jc(c.ba());this.mu.hc(c.$());this.mu.Jc(c.ba());this.Zz.bc(this.lu.tR);this.mu.bc(this.lu.mu);0==this.Zz.Kb().length?
(this.mu.Ta(0),this.mu.Qa(0),this.mu.Mn(a.xh.Gq)):(this.Zz.Ta(2),this.Zz.Qa(2),this.mu.Ta(e.ba()),this.mu.Qa(10),this.mu.Mn(a.xh.nea));this.aXc(f.sad);this.l5(c.O(),c.M(),h,h,null)};r.lma=function(a){this.RV.gg(100);return r.j.lma.call(this,a)};r.Egb=function(a){return r.j.Egb.call(this,a)};r.IS=function(){this.mka()&&this.qn()};c.wVb=function(){g.w.call(this);this.JXa=7;this.eW=this.V6=0;this.ro=this.npa=this.opa=null;this.dXa=3;this.XQ=this.JM=this.W6=null;this.QM=0;this.PTa=b.Qaa(-1,-1);this.JM=
new c.oYb(this);b.nI().Bja().Fa(this,a.K.$Z,this.S8)};var g=c.u(c.wVb,c.Wi);g.zb=function(){b.nI().Bja().Bz(this,a.K.$Z);g.j.zb.call(this)};g.U=function(){this.npa=this.opa=null;this.M4(null);this.Fhb();b.ea(this.JM);this.JM=null;g.j.U.call(this)};g.s7a=function(a){this.QM|=a};g.f3=function(a){this.QM&=~a};g.mtd=function(a,b){this.QM=this.QM&~a|(b?a:0)};g.Lkd=function(){return this.XQ};g.M4=function(c){if(this.XQ!=c){this.XQ&&(b.Q().su(this.XQ,!1),this.XQ.va(this,this.TAb));if(this.XQ=c)this.XQ.ya(this,
this.TAb),this.XQ.wB(!0);this.l(a.a.g)}};g.Fid=function(){return this.ro};g.Hid=function(){return this.opa};g.Did=function(){return this.npa};g.Snd=function(){null==this.W6&&(this.W6=[]);return this.W6};g.Mkd=function(){return this.mu};g.Nkd=function(){return this.tR};g.IJa=function(){return b.yp().qpa/200};g.wjd=function(){return 1};g.xrd=function(){return 2};g.xjd=function(){return 1};g.yrd=function(){return 1};g.lsd=function(){return 6};g.msd=function(){return 4};g.RBc=function(){return 0!=(this.QM&
1)};g.qd=function(){return 0!=(this.QM&8)};g.TMb=function(){return 0!=(this.QM&16)};g.oMb=function(){return 0!=(this.QM&32)};g.SMb=function(a){var c=!1;a=b.Q().lB(a);null!=a&&a.i$a()&&(c=!0);return c};g.Fhb=function(){if(this.W6){for(;0<this.W6.un();){var a=this.W6.Nr(0);b.ea(a)}delete this.W6;this.W6=null}};g.vha=function(a){this.SMb(a)||(this.N0b(a),this.ro==a&&null==this.opa&&null==this.npa)||(this.ro=a,this.npa=this.opa=null,this.tR=this.mu="",this.V6=this.eW=0,this.k1b(),null!=this.ro&&null!=
this.ro.ib()&&this.ro.lq(),this.RBa())};g.Idd=function(a,b,c,d){this.SMb(a)||(this.N0b(a),this.ro==a&&this.opa==b&&this.npa==d)||(this.ro=a,this.opa=b,this.npa=d,this.tR=this.mu="",this.V6=this.eW=0,this.k1b(),this.RBa())};g.N0b=function(a){this.ro!=a&&(null!=this.ro&&this.ro.va(this,this.zAb),null!=a&&a.ya(this,this.zAb))};g.ppb=function(a){this.ro==a&&this.RBa()};g.Kxb=function(c){var e,f=null;e=b.Hl();var d=b.Ycb(e),g=b.Q().jgb(e);if(null==g||g!=this.XQ)null==d||d.nFc()||(d=null),null!=d&&(f=d.Od()),
null!=d&&d.qd()&&null!=f&&(null==this.ro||this.ro.Od()!=f)&&(f=d.Od().kjc(e,a.Cta.EFb))&&(f.yd(a.R.Ywa),this.ro==f&&(d=f)),this.ro!=d&&this.vha(null),this.TMb()?b.wcb(this.PTa,e)?++this.V6>=this.IJa()&&(this.V6=this.IJa(),this.M4(null),this.f3(16),this.eW=0,this.tR=this.mu=""):(this.PTa=e,this.V6=0,this.ro&&this.ro.SIb()&&(this.tR=this.mu="",this.eW=0,this.M4(null),this.f3(16))):(null!=this.ro&&(d=!1,b.wcb(this.PTa,e)||(this.PTa=e,this.ro&&this.ro.SIb()&&(this.V6=this.eW=0),d=!1,this.eW<this.JXa&&
this.V6<this.IJa()?this.eW=0:c=!1),++this.eW>=this.JXa&&!d&&(this.eW=this.JXa,this.V6<this.IJa()?this.JQa():c=!1)),c&&3<=++this.dXa&&(this.dXa=3)),null==b.KP()&&this.Fhb()};g.Ked=function(){return!1};g.Hed=function(){return!1};g.NId=function(){};g.FAd=function(){};g.DNc=function(){this.RBc()||this.Fhb();this.f3(1);this.vha(null)};g.CNc=function(a){b.Q().lka()||(this.s7a(32),this.ppb(a),this.f3(32))};g.ENc=function(){(0>b.Uh(a.Da.kCa)||0>b.Uh(a.Da.apa)||0>b.Uh(a.Da.uTa))&&this.vha(null)};g.nHd=function(){};
g.RBa=function(){if(null!=this.ro)if(this.TMb())this.JQa();else{if(3>this.dXa||this.oMb())this.eW=this.JXa,this.Kxb(!1)}else this.M4(null),this.f3(16)};g.JQa=function(){var b,c,e=new t(this),d=null;this.ro&&(c=new p(this),this.ro.yd(a.R.Zwa,c,null),d=c.nd,b=c.pb,c=c.yYa);0==b.length&&null===d?(this.mu=b,this.tR=c,this.M4(null),this.f3(16)):(this.d_c(d,b,c,e),this.dXa=0)};g.ECc=function(){this.M4(null);this.JM&&this.JM.mka()&&this.JM.qn();this.f3(16)};g.d_c=function(a,e,f,d){null==a&&(a=this.JM);if(a!=
this.JM||this.oMb()||0<e.length&&this.mu!=e){var g=b.Nv(0,0),p=b.Nv(0,0),p=new c.ja(0,0,0,0);this.mu=e;this.tR=f;this.f3(2);p=this.i6b(this.mu);this.qd()&&0<this.tR.length&&(g=this.i6b(this.tR),0==g.ba()&&(g=this.j6b(this.tR)));0==p.ba()&&(p=this.j6b(this.mu),0<this.tR.length&&p.hc(p.$()+10));e=b.Qaa(d.pcc.O(),d.pcc.M());b.wcb(e,b.Qaa(0,0))&&(e=b.Hl(),e.yk(e.Eb()+15));p=this.ltc(e,p,g);this.qd()&&(this.M4(a),a==this.JM?this.JM.JQa(p,g,d):(d=b.Qaa(p.O(),p.M()),a==this.XQ&&a.Di()&&a.lma(d),a.l5(d.Db(),
d.Eb(),h,h,null)));this.s7a(16)}};g.j6b=function(a){var e=b.Nv(0,0),f=this.JM.Pd(),d=new c.ja(0,0,0,0);b.ey(a,d,0,f);e.hc(d.$()+6);e.Jc(d.ba()+4);return e};g.i6b=function(a){for(var e=b.Nv(0,0),f=String.fromCharCode(13),d=this.JM.Pd(),g=a.indexOf(f),h=0;;)if(0<=g){var p;0!=g&&(p=a.substr(0,g));a=a.substr(g+1);0<p.length&&(g=new c.ja(0,0,0,0),b.ey(p,g,0,d),e.hc(Math.max(e.$(),g.$())));h++;g=a.indexOf(f)}else{0<a.length&&(g=new c.ja(0,0,0,0),b.ey(a,g,0,d),e.hc(Math.max(e.$(),g.$())),h++);break}1<h&&
(this.s7a(2),g=new c.ja(0,0,0,0),b.ey("W",g,0,d),e.hc(e.$()+6),e.Jc(g.ba()*h+4));return e};g.ltc=function(a,e,f){var d=b.NF(),g=new c.ja(0,0,0,0),h=d.$()-1,p=d.ba()-1,d=new c.ja(d.O()+1,d.M()+1,h,p),p=d.dY(d),d=p.$();p.ba();if(e.$()<d){var k=a.Db();k+e.$()>d&&a.rl(p.na-e.$());g.Lb(a.Db(),a.Eb());g.ph(e.$(),e.ba());0<f.ba()&&g.RZ(0,f.ba());f.$()>g.$()&&g.RZ(f.$()-g.$(),0);0<f.$()&&e.$()+10>f.$()&&g.RZ(10,0);return g}if(e.$()<h)return k=a.Db(),k+e.$()>h&&(k=h-e.$()),g.Lb(k,a.Eb()),g.ph(e.$(),e.ba()),
g.RZ(0,f.ba()),g;g=this.mtc(e,p,a);g.RZ(0,f.ba());return g};g.mtc=function(a,e,f){var d=b.NF(),g=d.$()-2,h=d.ba()-2,h=new c.ja(d.O()+1,d.M()+1,g,h),d=[b.IP(),b.IP(),b.IP(),b.IP()],g=[];g.push(3);g.push(2);g.push(1);g.push(0);var p,k,n,r,h=e.dY(h);h.$();h.ba();e=a.$()*a.ba();p=h.O();k=h.M();d[0].Lb(p,k);d[0].ph(f.Db()-p,f.Eb()-k);d[1].Lb(f.Db(),k);d[1].ph(h.na-f.Db(),f.Eb()-k);d[2].Lb(p,f.Eb());d[2].ph(f.Db()-p,h.pa-f.Eb());d[3].Lb(f.Db(),f.Eb());d[3].ph(h.na-f.Db(),h.pa-f.Eb());for(k=h=n=0;4>k;k++){p=
g[k];r=d[p].$()*d[p].ba();n=Math.max(n,r);if(e<r){h=p;break}n==r&&(h=p)}d=d[h];g=a.ba();a=Math.min(a.$(),d.$());e=(e/a+g-1)/g*g;switch(h){case 0:d.Lb(f.Db()-a,f.Eb()-e);d.ph(a,e);break;case 1:d.Lb(f.Db(),f.Eb()-e);d.ph(a,e);break;case 2:d.Lb(f.Db()-a,f.Eb());d.ph(a,e);break;case 3:d.Lb(f.Db(),f.Eb()),d.ph(a,e)}return d};g.k1b=function(){this.qd();var a=null!=this.ro&&null!=this.ro.Ma()&&this.ro.Ma().vP()&&this.ro.qd();this.QM=this.QM&-9|(a?8:0)};g.TAb=function(b,c){switch(c.Ya){case a.a.ub:case a.a.Vb:this.M4(null)}};
g.S8=function(){b.Q().lLa()||b.Q().lka()||this.Kxb(!0)};g.zAb=function(b,c){switch(c.Ya){case a.a.ub:case a.a.Vb:this.vha(null)}}},{rp:["PRIM_PPNL"]});
