LANSA.addComponent({id:"VF_FP026O",ot:"rp",tp:"Reusable Part",de:"\OC=Node group (VLFONE)",tl:14015000},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")){cL=l.gCL();}var Fd={F1:{nm:"STD_INT",ft:"I",ln:4,dc:0,ec:"J",lb:{"ENG":"Std Integer","FRA":"?","JPN":"?"}[cL],h1:{"ENG":"Standard","FRA":"?","JPN":"?"}[cL],h2:{"ENG":"Integer","FRA":"?","JPN":"?"}[cL],h3:{"ENG":"Field","FRA":"?","JPN":"?"}[cL],de:{"ENG":"Standard Integer field","FRA":"?","JPN":"?"}[cL],dv:0,ia:["FE","RB"]}};var cO=l.rC(oI,
{an:"VF_AC001O",fd:Fd,pt:{uHscroll:{da:"r"},uVscroll:{da:"r"},uNodeJSFileName:{da:"r"},uButtonPanelLocation:{da:"r"},uButtonHeight:{da:"r"},uButtonWidth:{da:"r"},uButtonSpacing:{da:"r"},VLFONESharedSession:{da:"r"},VLFONESharedSessionStarted:{da:"rw"},VLFONESharedSessionAvailable:{da:"rw"},VLFONEReusableSession:{da:"r"},VLFONEReusablePoolMaximum:{da:"r"}},mt:{zInt_SetProperty:{ps:{"P":{pt:"i"}}}},co:function(){cO.aN.call(this);this.aF("VF_FP026O",Fd);var C0=this.cR("UHSCROLL","PRIM_BOLN");var C1=this.cR("UVSCROLL","PRIM_BOLN");
var C2=this.cR("UNODEJSFILENAME","PRIM_ALPH");var C3=this.cR("UBUTTONPANELLOCATION","PRIM_ALPH");var C4=this.cF("UBUTTONHEIGHT",Fd.F1.Dc);var C5=this.cF("UBUTTONWIDTH",Fd.F1.Dc);var C6=this.cF("UBUTTONSPACING",Fd.F1.Dc);var C7=this.cR("VLFONESHAREDSESSION","PRIM_BOLN");var C8=this.cR("VLFONESHAREDSESSIONSTARTED","PRIM_BOLN");var C9=this.cR("VLFONESHAREDSESSIONAVAILABLE","PRIM_BOLN");var C10=this.cR("VLFONEREUSABLESESSION","PRIM_BOLN");var C11=this.cF("VLFONEREUSABLEPOOLMAXIMUM",Fd.F1.Dc);C0.iC();
C1.iC();C2.iC();C3.iC();C4.aD();C4.iC();C5.aD();C5.iC();C6.aD();C6.iC();C7.iC();C8.iC();C9.iC();C10.iC();C11.aD();C11.iC();this.aH("CREATEINSTANCE",this,e1);}});var cA=cO.aN.prototype;function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#COM_OWNER.CreateInstance",46);r.ln=46;{r.ln=49;m.UBUTTONPANELLOCATION.set("RIGHT");r.ln=50;m.UBUTTONHEIGHT.set(20);r.ln=51;m.UBUTTONWIDTH.set(137);r.ln=52;m.UBUTTONSPACING.set(1);r.ln=53;m.VLFONEREUSABLEPOOLMAXIMUM.set(5);}r.ln=55;r.e();};cO.mthZINT_SETPROPERTY=function(p0)
{var m=this.REF,r=l.mR(this,cO,"zInt_SetProperty",58);var P0=r.cPD("P");P0=p0;var C0=r.cR("UVALUE","PRIM_ALPH");C0.iC();r.ln=58;{r.ln=64;if(l.n.le(P0.getPROPERTYNUMBER(),200)){r.ln=66;cA.mthZINT_SETPROPERTY.call(this,P0);r.e();return;}r.ln=73;{var v1=P0.getPROPERTYNUMBER();if(r.ln=75,l.n.eq(v1,201)){r.ln=76;m.UHSCROLL.set(l.s.eq(l.s.UpperCase(P0.getVALUE()),"TRUE"));}else if(r.ln=78,l.n.eq(v1,202)){r.ln=79;m.UVSCROLL.set(l.s.eq(l.s.UpperCase(P0.getVALUE()),"TRUE"));}else if(r.ln=81,l.n.eq(v1,203))
{r.ln=82;m.UNODEJSFILENAME.set(P0.getVALUE());}else if(r.ln=84,l.n.eq(v1,204)){r.ln=85;m.UBUTTONPANELLOCATION.set(P0.getVALUE());}else if(r.ln=87,l.n.eq(v1,205)){r.ln=88;m.UBUTTONHEIGHT.set(l.s.AsNumber(P0.getVALUE()));}else if(r.ln=90,l.n.eq(v1,206)){r.ln=91;m.UBUTTONWIDTH.set(l.s.AsNumber(P0.getVALUE()));}else if(r.ln=93,l.n.eq(v1,207)){r.ln=94;m.UBUTTONSPACING.set(l.s.AsNumber(P0.getVALUE()));}else if(r.ln=96,l.n.eq(v1,208)){r.ln=97;m.VLFONESHAREDSESSION.set(l.s.eq(l.s.UpperCase(P0.getVALUE()),"TRUE"));
}else if(r.ln=99,l.n.eq(v1,209)){r.ln=100;m.VLFONEREUSABLESESSION.set(l.s.eq(l.s.UpperCase(P0.getVALUE()),"TRUE"));}else if(r.ln=102,l.n.eq(v1,210)){r.ln=103;m.VLFONEREUSABLEPOOLMAXIMUM.set(l.s.AsNumber(P0.getVALUE()));}r.ln=106;}r.e();return;}r.ln=110;};cO.getUHSCROLL=function(){return this.REF.UHSCROLL.get();};cO.getUVSCROLL=function(){return this.REF.UVSCROLL.get();};cO.getUNODEJSFILENAME=function(){return this.REF.UNODEJSFILENAME.get();};cO.getUBUTTONPANELLOCATION=function(){return this.REF.UBUTTONPANELLOCATION.get();
};cO.getUBUTTONHEIGHT=function(){return this.REF.UBUTTONHEIGHT.get();};cO.getUBUTTONWIDTH=function(){return this.REF.UBUTTONWIDTH.get();};cO.getUBUTTONSPACING=function(){return this.REF.UBUTTONSPACING.get();};cO.getVLFONESHAREDSESSION=function(){return this.REF.VLFONESHAREDSESSION.get();};cO.getVLFONESHAREDSESSIONSTARTED=function(){return this.REF.VLFONESHAREDSESSIONSTARTED.get();};cO.setVLFONESHAREDSESSIONSTARTED=function(v){this.REF.VLFONESHAREDSESSIONSTARTED.set(v);};cO.getVLFONESHAREDSESSIONAVAILABLE=function()
{return this.REF.VLFONESHAREDSESSIONAVAILABLE.get();};cO.setVLFONESHAREDSESSIONAVAILABLE=function(v){this.REF.VLFONESHAREDSESSIONAVAILABLE.set(v);};cO.getVLFONEREUSABLESESSION=function(){return this.REF.VLFONEREUSABLESESSION.get();};cO.getVLFONEREUSABLEPOOLMAXIMUM=function(){return this.REF.VLFONEREUSABLEPOOLMAXIMUM.get();};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"STD_INT"});}},{rc:["VF_AC001O"],rp:["PRIM_BOLN","PRIM_ALPH","PRIM_FLD"],dp:["PRIM_ALPH"]});
